### ISSUE TITLE
After upgrade to 4.0, image is not found

### ISSUE THREAD

**Issue by slim0287** [tsightler/ring-mqtt#102]
I upgraded to 4.0 on Home Assistant running on my Raspberry Pi 4 (32-bit).  I followed these steps:

1. Upgrade “Ring Devices via MQTT” to 4.0 via Supervisor
2. Reset Configuration to defaults
3. Hit “Start” on “Ring Devices” Add-On and nothing happens
4. Check system log and see the following:

`20-09-05 16:06:45 ERROR (SyncWorker_2) [supervisor.docker] Can't create container from addon_a98c085d_ring_mqtt: 404 Client Error: Not Found ("No such image: tsightler/ring-mqtt-ha-addon:4.0.0")`

The other feature I noted is that the Snapshot I did before the upgrade (220 MB) was a lot larger than the Snapshot I made after the upgrade (129 MB).

**Comment by tsightler** [comment]
I'm moving this issue to the addon Github page as this issue is specific to the addon and not the ring-mqtt.  Please follow it [there](https://github.com/tsightler/ring-mqtt-ha-addon/issues/16)
