### ISSUE TITLE
Error without a docker volume

### ISSUE THREAD

**Issue by dels78** [tsightler/ring-mqtt#108]
I am using the ring-mqtt script via the docker installation

** Describe the bug **
I was using the script fine for a while then I noticed it stopped working after an update, but was out of town. I came back home and spent a few hours trying to figure it out today but the docker container just wouldn't start and didn't give any log output. 

I was getting those lines in my Mosquitto logs:
1599529182: Socket error on client mqttjs_6acefa8c, disconnecting.

I ended up figuring out how to add the environment variable for DEBUG and found this out:

2020-09-08T01:38:18.941Z ring-mqtt Starting connection to MQTT broker...
2020-09-08T01:38:19.131Z ring-mqtt **Exit code: Error: EACCES: permission denied, open '/data/ring-state.json'**
2020-09-08T01:38:19.140Z ring-mqtt MQTT connection established, processing locations...
2020-09-08T01:38:20.133Z ring-mqtt Exit code: 0

I was able to fix the problem by mounting a volume to the container, which also helped with the persistence of the refresh token, but the documentation says we shouldn't have to have it so either it needs to be updated to show it is now needed, or the actual bug should be fixed.

Thanks!

**Comment by tsightler** [comment]
Hmm...strange, I've been running it in my lab environment without this issue for some time.  The /data directory exist in the container and the process is running as root so I'm not sure how this can happen.  It should just write the file to the non-persistent layer of the container.  Are you perhaps running the container the the filesystem as read-only?

**Comment by dels78** [comment]
I am actually running the container as a non-privileged user, it could be why it doesn't want to write to that directory if it is owned by root in the first place. The filesystem is not read-only though.

**Comment by tsightler** [comment]
Yep, I realized after I posted that read-only would actually give a read-only filesystem error (EROFS), not EACCES.  But indeed, I was going to ask if you were using a non-privileged user because I was able to reproduce with that since the /data directory in the container is owned by root and isn't writable by non-root users.  I guess I could just change the /data directory to 777 in the Docker build which would allow it to work even if someone ran it with non-privileged user and no mount.

**Comment by dels78** [comment]
That would indeed solve the problem for crazy old sysadmins like me :) 

Thanks for the help! I love your work!

**Comment by tsightler** [comment]
Pushed a new docker image with this change, tested, and it works so just run a docker pull and you too can run without persistent storage even with a non-privileged user, although, of course, if you have persistent storage now I'm not sure why you would ever switch back, it really does help with token expiration issues and persistent storage may very well become required in the future as I have a few other features where storing some persistent state would be useful.

**Comment by dels78** [comment]
Indeed, I am not planning to switch, I merely wanted to let you know of the problem as I figured it was some sort of corner case and it could help others.

Thanks again!
