### ISSUE TITLE
Support for Changed_by attribute

### ISSUE THREAD

**Issue by miguelarios** [tsightler/ring-mqtt#124]
I see that my `alarm_control_panel.ring_alarm` entity has an attribute called `changed_by` but currently that is `null`. Would be cool to have this pulled.

**Comment by tsightler** [comment]
As far as I can tell there is no way to provide this attribute via the MQTT Alarm Control Panel component.

I could perhaps include some type of information in the info sensor data (assuming it's possible to get from the API), but what would you actually like to see here?

**Comment by miguelarios** [comment]
Well I was trying to mimic the Ring notifications that call out who has disarmed or armed the alarm system. This could potentially help in setting the house for a certain person. I was still brainstorming.

**Comment by tsightler** [comment]
OK, makes sense.  I'd need to investigate how to get this information as I've not seen it as part of the data event.  But first I need to see if I add a json_attributes_topic with the change_by value if it shows up.  Otherwise I guess I can add it to the info sensor.  I'll look into it.

**Comment by Ramias1** [comment]
Came here looking for the exact same thing.  I got ring-mqtt working with my Ring doorbell and sending status to MQTT plugin on my Indigodomo system.  Don't have the alarm yet but thinking of getting one.  Would love to have a signal that triggers a different Sonos station based on which alarm disarm code was used.

**Comment by tsightler** [comment]
Unfortunately I can't really figure out a way to do this.  As far as I can tell the only place to see the user which did something is from the event history, which I can grab without too much trouble, however, the "source entity" is just an ID number and I can't figure out any way using the API to translate this into something reasonably usable.  Perhaps I just haven't found the place to query, that's certainly possible, but I've poked at all the virtual devices, I can see the user IDs in the code vault, but that still doesn't give me any real names to use.

Based on this, I'm going to consider this something that can't be implemented for now and close this feature request.  If someone can figure out a way to determine the actual user from the users unique ID, I might consider implementing this again.

**Comment by Ramias1** [comment]
Thanks for looking at this.  As long as user IDs are consistent overtime I can use that and translate that to names myself.

that would still be useful for my use case.

**Comment by SamB-GB** [comment]
Since this feature request it a bit older and things may have developed I wanted to re-open to see if it would be possible to implement this yet?
