### ISSUE TITLE
Starting ring-mqtt during boot

### ISSUE THREAD

**Issue by akipal** [tsightler/ring-mqtt#125]
Thank you for your great work first.
I managed to make it work.
But I don't know how to start ring-mqtt during boot.
I am using MacOs so systemctl is not working.
is there other way for MacOS?

**Comment by tsightler** [comment]
I haven't used a Mac in nearly 2 decades so I have no idea, but certainly this is not a bug in this project, so I've removed the bug label.  My understanding is that Mac has a feature called launchd which, while using a very different configuration model, provides functionality similar to systemd.  A quick Google found the link below, which shows using systemd on Linux to run a node script, and the the equivalent on Mac using launchd:

https://www.endyourif.com/node-js-as-a-background-service/

Another option would be to install Docker on you Mac and use it's restart policies.  But pretty much all of this is beyond the scope of this project, but Google is your friend.
