### ISSUE TITLE
Home Assistant Automations Do Not Trigger

### ISSUE THREAD

**Issue by Curtisjk** [tsightler/ring-mqtt#130]
I am attempting to create automations in Home Assistant based off when the alarm is armed or disarmed. I have attempted testing the "Alarm armed home" trigger but doesn't appear to work.

Are these triggers pre-created by Home Assistant, or specified as part of the ring MQTT discovery?

If these are not in the control of ring-mqtt could you please advise on the best way to create arm/disarm triggers? I have created some triggers using the entity state which work well, but haven't worked around the problem on the interim "pending" state which is set when entry delay is in progress.

Many thanks
Curtis

**Comment by tsightler** [comment]
Triggers, events, etc. are the domain of Home Assistant, not ring-mqtt.  I don't even know what "Alarm armed home" trigger even refers to, or where to find that in HA.  In general, questions about Home Assistant automation are best presented to the Home Assistant forums as there is nothing specific to ring-mqtt as it simply uses the Home Assistant MQTT Alarm Panel integration.

For myself, I just use state based triggers, which it seems you also have working as well.  I don't really understand the issue you mention regarding pending state as you can just ignore that state if you don't want to do anything with it so it's not really clear to me how this is a problem.

**Comment by Curtisjk** [comment]
@tsightler these are the options I am presented within Home Assistant:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/2105186/102098183-cb8eb380-3e1e-11eb-8d11-0907c53af180.png">

Regarding the 'pending' state - I specifically wanted to create an automation for when the alarm is set to "Home and armed" to "Disarmed". However if there's an entry delay the state flow goes `armed_home` -> `pending` -> `disarmed`

**Comment by tsightler** [comment]
Ah, automation rules built in the UI, I see.  I just write all of my rules in YAML as I never remember that you can do it in the UI these days.  I've seen at least one report on the forums that device triggers were not working for disarmed, I have no idea why, but I'd have to blame HA as ring-mqtt is responsible for doing nothing other than updating state, which obviously works.  Maybe there's a bug in the HA MQTT Alarm Component (that user reported that triggers for arming worked, but disarmed didn't work).

For the pending state, I'd guess you might need to use a [wait template](https://www.home-assistant.io/docs/scripts/#wait) in the action to wait for the pending state to clear and then check the status again and continue your automation only of it's disarmed, but this is really a Home Assistant question.

**Comment by Curtisjk** [comment]
Thanks. I have raised a question over on the Home Assistant forums
