### ISSUE TITLE
Feature request: snapshot

### ISSUE THREAD

**Issue by McMornan** [tsightler/ring-mqtt#135]
Hi,

First let me thank you for your great effort! I have several ring cams and a doorbell. Motion and alarms are detected very well! (I am using the docker image with openhab3)

The ring-client-api offers the option to get a snapshot of a camera. Do you think it would be possible to add that functionality ? I think it is possible to post binaries (pictures) as a mqtt payload.

Lars

**Comment by tsightler** [comment]
Are you asking for use with Home Assistant or something else?  The primary reason that I haven't implemented this up to this point is that for most MQTT use cases there's not much value and, while it's possible with the Home Assistant MQTT Camera component, this functionality is already included in the standard Home Assistant integration for Ring cameras so it seemed redundant.

**Comment by McMornan** [comment]
Hi,

A Screenshot from the camera when motion has been detected would be sufficient. I am using openhab. 

Lars

**Comment by tsightler** [comment]
Do you have a link to an example of an OpenHAB binding?  I don't know much about OpenHAB myself, is it OK with a topic that just dumps a jpg binary via MQTT?

**Comment by McMornan** [comment]
Hi,

I use the mqtt messages and map them to item states. It looks like this:

 Thing topic nodeCamVorbau "Ring Cam Vorbau" {
    Channels:
        Type switch : motion "Motion" [ stateTopic="ring/location/camera/camid/motion/state" ]
        Type number : uplink "Uplink Quality" [ stateTopic="ring/location/camera/camid/info/state", transformationPattern="JSONPATH:$.wirelessSignal",unit="db" ]
        Type datetime : last_seen "last seen" [ stateTopic="ring/location/camera/camid/info/state",transformationPattern="JSONPATH:$.lastUpdate" ]
    }

So all I need is an additional message which contains the binary in an usable image format. (e.g. iotctl can send desktop snapshots via MQTT) e.g. ring/location/camera/camid/snapshot. It would be ok to only send the snapshot when the camera motionstate switches to ON.

 So I guess the answer to your question is: yes. A JPG dump would be ok.

thanks
Lars

**Comment by tsightler** [comment]
OK.  It doesn't look too difficult, and it's been on the fringes of the to-do list for a while.  Unfortunately, I haven't had much time to work on this project lately, but maybe this weekend I can squeeze a few minutes to take a stab at the super simplest implementation and see if it just happens to work straight away.

**Comment by McMornan** [comment]
Thank you very much !

**Comment by tsightler** [comment]
I've pushed 4.3.0 which includes this feature.  Please note that it must be explicitly enabled using the new "enable_snapshots" option (or equivalent environment option for Docker).  During script startup it sends the most recent snapshot (the same as you see when opening the Ring app), and, after that, it sends updated snapshots only on new motion events.  I'm thinking about enhancing it to allow defining an automatic snapshot refresh interval.

I tested it with Home Assistant and it seems to work quite well, far better than I expected.  If I bring up both the Ring app and the Home Assistant dashboard with the cameras, I get almost identical behavior.  Please give it a spin and let me know how it works for you.

**Comment by McMornan** [comment]
Hi, 

thanks for your efforts !

I updated my docker container to latest version (using the BRANCH environment variable). 
And now I get snapshot images when motion has been triggered in a cam, thank you very much ! 

Now I only have to figure out how I can convert the MQTT message to an Image I can use in openhab ... what format are the snapshots in, jpeg ?

thanks,
Lars

**Comment by McMornan** [comment]
Hi,

found it. The homeassistant binding autodiscovers the snapshot topic. Works very well !

Thanks again and keep up the great work !

Lars

**Comment by tsightler** [comment]
I'm not even sure of the format, but I assume it's jpeg.  I'm not converting the format, the ring-client-api simply returns the image from the Ring API and I just dump that raw image data to the MQTT message.  Looking at the image on the Ring web client, it appears they are JPEG, and I can't image they are converting it just for that use.  Sounds like you managed to get it working.

I'll close this now since it seems to be working.
