### ISSUE TITLE
Feature request: ZWave events for switches

### ISSUE THREAD

**Issue by idyedov** [tsightler/ring-mqtt#139]
I’m currently exploring the idea of using ring security as the primary zwave hub, and handling all automation through home assistant. The only thing stopping me right now is lack of “double tap” events on my switches.

Does ring expose those events in any way that could be routed to mqtt or is it just not possible?

**Comment by tsightler** [comment]
I don't have any idea if Ring supports these events as I have no idea how double-tap functions are exposed via Z-wave or the Ring API, but I can say that I don't see any chance that such events would be exposed via ring-mqtt today as today each device has to be coded to expose any supported function. Personally I think the Ring hub is a poor choice for a Z-wave hub unless you have only very basic needs.  The automation functions are quite limited and device support is lacking.  As a supplement to other Ring functions it's OK (for example, integrating with Z-wave locks, or if you want to turn on a Z-wave light in concert with other Ring lights), but it's not that useful for much else.

I have no plans to try to make ring-mqtt fully functional for all Z-wave devices and functions as that is way beyond the scope of this project and there are plenty of great, low-cost options for controlling Z-wave devices.

**Comment by idyedov** [comment]
thanks for the quick response! I figured as much given that it's not exposed in the ring app at all, but wanted to check anyway.

regarding automation, ring-mqtt actually makes it pretty good as you can configure your automations in home assistant rather than in ring

**Comment by tsightler** [comment]
Of course it's possible to use ring-mqtt for this, I just think using Ring as a Z-wave hub is probably one of the worst ways to connect Home Assistant to Z-wave devices.
