### ISSUE TITLE
Invalid addon repository

### ISSUE THREAD

**Issue by nutsofamily** [tsightler/ring-mqtt#140]
https://github.com/tsightler/ring-mqtt.git

I get an invalid reposiroty when adding to Hassio on PI4

**Comment by iceman23e** [comment]
You need to add the add-on [here](https://github.com/tsightler/ring-mqtt-ha-addon).

**Comment by nutsofamily** [comment]
Thanks. Ring working now. Sure would be nice if we could figure LIVE VIEW somehow.
