### ISSUE TITLE
Error in logs just started showing up

### ISSUE THREAD

**Issue by j6s33m** [tsightler/ring-mqtt#141]
21-02-10 23:17:52 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of ring alarm hassio integration

**Comment by tsightler** [comment]
What version of the addon are you using?  The addon hasn't used `"startup": "before"` since the 3.x versions.  Current version is 4.3.0.  Please upgrade your addon to the latest version.

**Comment by j6s33m** [comment]
Super strange because I'm on 4.3. I keep all my addons up to date.

**Comment by tsightler** [comment]
Perhaps you still have an old repository configured in your addon store which should be removed?  The hint is here:

> Please report this to the maintainer of **_ring alarm hassio integration_**

I never used the phrase "ring alarm hassio integration" for the name of my addon, but that exact wording was used as the name of the original addon created by rs1932 back in the earliest days of the ring-mqtt project.  I can only guess that you must still have his repo configured in the addon store.

**Comment by j6s33m** [comment]
That looks to be the case...just deleted. Thanks!

**Comment by tsightler** [comment]
Thanks for the update.  Closing this now.
