### ISSUE TITLE
Detect when alarm is attempted to be armed but requires a bypass

### ISSUE THREAD

**Issue by calisro** [tsightler/ring-mqtt#151]
I'm looking to be able to detect when the Ring app or the keypad is used to arm the alarm and a sensor is open requiring a bypass..  the intention here is if someone arms it outside of Home assistant and it doesn't automatically arm because one of the sensors is open I would like to generate a notification. Is there any way to do this? I know I can do it easily if the alarm was armed within home assistant. 

And all my digging it looks like the state of the devices remain disarmed but I might be missing something.

**Comment by tsightler** [comment]
I don't see any way you could practically do this, especially with the app as arm events are always immediate and it's the app itself that determines if sensors require bypass and keeps you from arming unless you hit the bypass option.  Basically, there's no event outside of the app.

For the panel, it might theoretically be possible to do something with the arming delay.  I believe that Home Assistant will show the state as armed immediately, even if you have a delay set for both home and away mode arming.  For this case you could maybe do something crude like detect if the state went from disarmed, to armed/home away, and then back to disarmed before the delay time had passed (or within a few seconds +/- of the delay time).  Of course, this has the potential to catch weird cases where you intentionally armed and then disarmed the alarm in a short period, but if that's uncommon it might be partially workable.
