### ISSUE TITLE
Sensors in Bypass Mode

### ISSUE THREAD

**Issue by stevemutch** [tsightler/ring-mqtt#152]
Firstly great work, this API was exactly what i needed to link into Node Red and control many other devices with the Ring device statuses.

I'm looking to do the following and wondered if the necessary trigger is available to achieve this.

When an attempt is made to arm the alarm but there are doors open (ie need bypassed) that I can detect the doors opened and call them out on Alexa with "Xyz door is open, please close it to arm the alarm"

If I look on the Ring app and try to arm the alarm while a door is open it pops up and asks me if i want to bypass it. 

With Ring-MQTT i have retained the latest values so have up to date info on sensor statuses and thus can use that to determine which sensors are going to be bypassed.

What i need is a trigger when the alarm is trying to arm but before it is armed.

Is that available and hope this makes sense?

Thanks

Steve

**Comment by tsightler** [comment]
Duplicate with same answer:  https://github.com/tsightler/ring-mqtt/issues/151.
