### ISSUE TITLE
Breaking change to `ring-client-api`

### ISSUE THREAD

**Issue by dgreif** [tsightler/ring-mqtt#159]
Hey @tsightler,  just wanted to give you a heads up that I just released what is _technically_ a breaking change on the client api, but I didn't mark it as such because I think you are the only one using the value that changed 😅.  See https://github.com/dgreif/ring/commit/79b28fb81645b9c8c634c090797ae3d2d21e1dd5#diff-984c608fc44d43d3897f059051d474b6217a9296f9c8f807172ec66bd89f1d33R27-R28.  I had `switch.multilevel.beams` named as `BeamsSwitch` before, but the new Outdoor Smart Plug uses `switch.beams`.  You should be able to add `RingDeviceType.BeamsMultiLevelSwitch` right after this line: https://github.com/tsightler/ring-mqtt/blob/dde93f9a7ffaad92fea34af8f085f070fd3170a4/ring-mqtt.js#L84

Let me know if you run into any issues!

**Comment by tsightler** [comment]
Thanks @dgreif, I have a few queued updates that I hope to get out in the next week so I'll get this in there as well,

**Comment by tsightler** [comment]
Pushed an update with this change so closing this now.
