### ISSUE TITLE
Arm/Disarm with code feature

### ISSUE THREAD

**Issue by Anri1967** [tsightler/ring-mqtt#171]
Hello. I was just wondering if arming and disarming with code is available yet or is it being worked on? Any suggestions on how to incorporate maybe with another keypad or another Home Assistant Card?

**Comment by tsightler** [comment]
I don't currently plan to add this anytime soon.  This project is mostly about exposing Ring devices via MQTT.  This makes the assumption that users which are authorized to connect to MQTT are authenticated, or, if you choose to expose this integration via other methods (for example via Home Assistant UI) those those methods provide their own authentication.

However, assuming you are using Home Assistant, you can always manually define an alarm control panel vs using the automatically discovered one and this allows you to define a code for both arming and disarming.  See [this post](https://github.com/tsightler/ring-mqtt-ha-addon/issues/13#issuecomment-808827575) for details on how to do this.
