### ISSUE TITLE
"Failed to enable unit: Unit file ring-mqtt.service does not exist."

### ISSUE THREAD

**Issue by DueHack12** [tsightler/ring-mqtt#172]
I keep getting this error, even though i used `ls` and saw that it was in fact there. Anyone else with this problem?

**Comment by tsightler** [comment]
It's not clear to me what exactly you are attempting to do when you get this error.  Are you trying to perform a standard install (i.e. non-docker)?  I haven't attempted a standard install in a long time, however, I don't think the service file should have any issues as it's pretty basic.  I've had no other reports of issues with the unit file but it's not the common method for running this project these days, so only a small fraction of users actually leverage it.

**Comment by DueHack12** [comment]
> Are you trying to perform a standard install (i.e. non-docker)?

Yes, this is what I am doing. I am running on ubuntu. I got it to work, but I had to run the `.js` file seprate.

**Comment by tsightler** [comment]
Did you copy the unit file to the correct location and run systemctl daemon-reload?  It's just a sample unit file, you can always just make one manually following any examples for Ubuntu, but the provided one should work fine.  I just tested it on an Ubuntu 20.04 setup and it worked fine.

**Comment by DueHack12** [comment]
What do you mean copy the file to correct location?

**Comment by tsightler** [comment]
Basically, did you follow these instructions:  https://github.com/tsightler/ring-mqtt#starting-ring-mqtt-during-boot

More specifically, as the instructions note, the ring-mqtt.service file has to be copied to the systems unit file directory, usually /lib/systemd/system, otherwise systemd will not be able to find it.

**Comment by tsightler** [comment]
Closing due to no response.  The included unit file is just an example anyway, you can always manually create one any example for your Linux distro.
