### ISSUE TITLE
Feature request: arming state

### ISSUE THREAD

**Issue by JOHLC** [tsightler/ring-mqtt#173]
Hello again,

Would it be possible to implement the home assistant alarm 'arming' state? 

E.g. When you set to armed away.
Ring alarm is pending for 30 seconds before it is actually armed. 

As far as I know home assistant supports arming mode/status 

Thanks!

**Comment by tsightler** [comment]
I looked into this one time before but couldn't figure out a way to do it because the Ring API doesn't appear to report the exit delay.  For example, if you look in the app, and set away mode, it will have the delay, but even the Ring app shows "armed" state, not pending or exit delay state.  I couldn't find anything in the API that showed the exit delay state so I was unable to implement this.

**Comment by JOHLC** [comment]
Thanks for looking into it!

**Comment by tsightler** [comment]
Took another really quick look at this and I see that there is actually a property `transitionDelayEndTimestamp` which is the time when the new mode actually takes effect, even though the value in the data element immediately reflects the new target mode, thus it's at least technically possible to implement this, but I'd have to implement logic that would basically store this timestamp and trigger a state change from pending to armed, once the time expired and assuming the arming event wasn't cancelled.

Nothing too hard, but there's no such event framework there right now and I don't know how soon I'll be able to get around to it as I really don't have much time for this project right now, but I'll leave it open and try to get to it in a future update.

**Comment by tsightler** [comment]
This feature will be in the 4.6.0 verison which should push in the next 1-2 weeks, but if anyone wants to give it a try now you can test it in the dev branch.  It seems to work for me just fine.

**Comment by tsightler** [comment]
Version 4.6.0 has been released and includes support for arming state status during exit delay.

**Comment by JOHLC** [comment]
You're amazing, thanks for your time!
