### ISSUE TITLE
node: --unhandled-rejection= is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by jamess5** [tsightler/ring-mqtt#189]
Hi,

Since about 8 hours ago, ring-mqtt has stopped working. When I check the logs, I have the following:

```
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
Running ring-mqtt...
node: --unhandled-rejection= is not allowed in NODE_OPTIONS
```

Not sure if this is related to an update, as I haven't changed any of my config.

Many thanks,
James

**Comment by tsightler** [comment]
There was a small blip in my automatic build process where 4.5.6 was accidentally published to production yesterday for 2-3 minutes, before it was really ready (it's currently released on the main project but not for the addon as it's mostly a test).  Perhaps your system managed to pick up the update in this short window?  If you perform a repository reload from the addon screen you should get the option to "upgrade" back to 4.5.5 which should fix it.

**Comment by jamess5** [comment]
Hi @tsightler - thanks for the prompt response. I reloaded the repository as you suggested, and it looks like it is working again now. Thanks for your help!
