### ISSUE TITLE
FAILED to reach ring server

### ISSUE THREAD

**Issue by mar005** [tsightler/ring-mqtt#2]
Hi @tsightler 

Getting this error as of a few days ago. Not sure if ring changed their URL.

`ring Failed to reach Ring server at https://oauth.ring.com/oauth/token.  Trying again in 5 seconds... +15ms `

**Comment by tsightler** [comment]
I'm not having any such issues and it seems unlikely that the URL would have changed based on the fact that the app still seems to use this URL.  Not only that, but the authentication is handled far below my code, in the ring-client-api module.  Admittedly, the ring-client-api code has progressed significantly in the last few months and is all the way up to 5.9.0, while the current code is using 4.2.1.  However, this seems mostly to add support for camera streams, etc. (things not supported in the ring-mqtt code).  

Even just sticking that URL in a browser gives the expected response.  I would suggest checking your environment and troubleshooting by hitting the URL with curl:

```
# curl https://oauth.ring.com/oauth/token
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}

```

**Comment by mar005** [comment]
This was just a dns issue on my side
