### ISSUE TITLE
Ring update motion sensitivity setting via api

### ISSUE THREAD

**Issue by calisro** [tsightler/ring-mqtt#201]
Is it possible programmatically in the ring api to update the motion sensitivity high medium low? I have a use case where I'd like to turn down the sensitivity on one motion detector for when I'm armed home. I'd like to be able to do that programmatically when the alarm gets armed. Internet back to medium or low when it's armed away or disabled.

If that is possible would you consider adding that to the home assistant integration?

**Comment by tsightler** [comment]
Spent some time looking into this and, while it is clearly possible to set this value via the Ring API, there's no native support in ring-client-api and that means I'd have to know the exact JSON needed to do this.  Unfortunately, the only way I know to pull this is to use something like mitmproxy and capture data from the Ring app setting the value.  However, the Ring app uses certificate pinning, so to use it with mitmproxy requires rooting some device and using something like XPOSED to modify the app to accept another certificate.

While I could probably do all of this, I don't have the time or desire to put that much work into this feature.  I'll continue to monitor ring-client-api, and if it adds any functions to set this I'll consider adding this functionality, but for now I'm closing this as not possible.

**Comment by calisro** [comment]
Thanks fr looking into.  I get the complexity.  If I can figure out the JSON, i'll report here as well.

**Comment by tsightler** [comment]
Thanks, if you can figure it out I believe it would be trivially easy to add, especially now that Home Assistant has some more flexible MQTT integrations like "number" and "select".
