### ISSUE TITLE
ring changed app api location

### ISSUE THREAD

**Issue by drewstreib** [tsightler/ring-mqtt#209]
Ring has apparently changed the location of an app.ring.com api that is referenced by the underlying node ring library, breaking functionality of ring-mqtt (at least for me, but the nature of the break means that it must be broken for everybody else too? Or at least ones that make use of this endpoint.)

See https://github.com/dgreif/ring/issues/699

**Comment by tsightler** [comment]
Duplicate:

https://github.com/tsightler/ring-mqtt-ha-addon/issues/56
