### ISSUE TITLE
Multiple Disarm Codes?

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#211]
Is there a way to use either multiple disarm codes, or pull the disarm codes from ring? My wife and I each have our own account with our own codes and it would be nice if we could each use our own code instead of sharing.

**Comment by tsightler** [comment]
As far as I can tell, it's not possible to read the codes from Ring but, even if it was possible, the Home Assistant MQTT Alarm Control Panel integration only has a setting for a single code and it's just a front-end feature in Home Assistant, the code being entered is not actually sent to the backend.

If you and your wife are using different logins to access Home Assistant, then you could manually create two different Alarm Control Panels for each user by manually defining them in configuration.yaml as [documented here](https://github.com/tsightler/ring-mqtt-ha-addon/issues/13#issuecomment-808828600) and then use the user controls in Home Assistant to display a different alarm tab with the panel configured with that users code.

**Comment by broyuken** [comment]
That seems a little unnecessarily complicated to just have a second code lol. I'll just have her use mine in the rare cases that she actually loads up HA
