### ISSUE TITLE
Invalid value for number.X_snapshot_interval

### ISSUE THREAD

**Issue by timota** [tsightler/ring-mqtt#213]
** Describe the bug **
After upgrade to the 4.6.X series  version of an addon, i start seen message below in a logs. Unfortunately im running addon, and i dont know how to start it in a debug mode. 
Some side info:
HASSIO: core-2021.7.4
RingMqtt: 4.6.2

For me it looks like some missconfiguration during entity initialisation (Mqtt autodiscovery). See screenshot below.
<img width="396" alt="Screenshot 2021-07-28 at 19 52 43" src="https://user-images.githubusercontent.com/11276397/127379838-6abc7b05-7028-4e36-b48e-0121ef0dc05d.png">

On the right - should be default value of interval or at least it should be defined, but it doesn't. If is set that number(snapshot_interval) - messages stop.

**Debug Logs**
```
2021-07-28 19:42:29 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.front_door_snapshot_interval: 300 (range 0.0 - 100.0)
2021-07-28 19:42:59 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.front_door_snapshot_interval: 300 (range 0.0 - 100.0)
2021-07-28 19:43:29 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.front_door_snapshot_interval: 300 (range 0.0 - 100.0)
```

MQTT config/state

```
{
    "name":"Front Door Snapshot Interval",
    "unique_id":"3045115be9c7_snapshot_interval",
    "availability_topic":"ring/50a8dc7f-3359-4fb5-7b19-fffedee1048e/camera/3045115be9c7/status",
    "payload_available":"online",
    "payload_not_available":"offline",
    "device":{
        "ids":["3045115be9c7"],
        "name":"Front Door",
        "mf":"Ring",
        "mdl":"Doorbell 2"
    },
    "command_topic":"ring/50a8dc7f-3359-4fb5-7b19-fffedee1048e/camera/3045115be9c7/snapshot_interval/command",
    "state_topic":"ring/50a8dc7f-3359-4fb5-7b19-fffedee1048e/camera/3045115be9c7/snapshot_interval/state"
}
```

State topic is empty after restart.

`ring/50a8dc7f-3359-4fb5-7b19-fffedee1048e/camera/3045115be9c7/snapshot_interval/state`

**Comment by tsightler** [comment]
Hmm...good one, looks like the MQTT number integration defaults to a maximum value of 100.  I'll have to modify the discovery value to include a higher maximum value.  I need to fix that code anyway to cancel and reinitialize when people change the value, so I'll include the fix with that in the next few days.

Thanks for the report and the good details!

**Comment by tsightler** [comment]
Pushed out 4.6.3 which should address this issue.  Please let me know if you still experience issues and I'll reopen the issue.  Thanks again for the report.

**Comment by timota** [comment]
Cool, thank you. Looks like issue gone.
