### ISSUE TITLE
"Things" connected to the ring light Bridge no longer appear

### ISSUE THREAD

**Issue by Grey-Lancaster** [tsightler/ring-mqtt#214]
Since the update yesterday that fixed the 404 error no of my entities connected to the light bridge appear. I suppose somewhere along the road the device description changed in the logs to GUID's and I really cannot make heads or tails of an entry.  I have rebooted the bridge and it works fine in the ring App

Thanks,
Grey

Some screenshots...

![ring1](https://user-images.githubusercontent.com/20055899/127381257-04c096c4-47c5-4e73-a6cf-40cd385200d1.JPG)
![ring2](https://user-images.githubusercontent.com/20055899/127381388-b52f47ed-5e20-410d-a830-74d45e337e31.JPG)
![ringbridge](https://user-images.githubusercontent.com/20055899/127381412-bd9c8f95-5174-40b4-905e-42f915da370b.JPG)

**Comment by tsightler** [comment]
What version were you running before?  There were no changes to light support between 4.6.0 and 4.6.2, and I had users that tested the light support for 4.6.0 with no issues (I don't have lights, so it's hard for me).

My concern is that the new locations API that we had to switch to might not be returning beam lights anymore as I don't even see them in the device list in your screenshots above.

**Comment by Grey-Lancaster** [comment]
I believe I was up to date 4.6.1

Papa Lanc

________________________________

**Comment by tsightler** [comment]
And they were working at that point?  There were zero code changes in ring-mqtt from 4.6.1 to 4.6.2, literally only a version bump and an entry in the changelog, and a wording change to a static HTML file used for the token generation app.

This makes me concerned that the API changes introduced by Ring yesterday somehow broke existing support in ring-client-api for smart lighting.

Did you do anything else other than upgrade?  Perhaps maybe re-authenticate?  Or are you using the same token as before?

**Comment by Grey-Lancaster** [comment]
Hi, sorry have been on the road.  Thanks for the quick replies. Yes, I tried like 3 tokens yesterday going after the 404 error.  I am pondering if this is the Alexa API.  Has in it did not support the pathlights for routines and I was so happy to turn on my fountain pump when someone was in the yard vs having it run all day.  Being able to see the battery level was great also

{FWIW Pathlight motion now shows up in the alexa app}
![ring3](https://user-images.githubusercontent.com/20055899/127395709-a4e7b711-d7df-4868-b7a3-46c663c33947.JPG)

**Comment by tsightler** [comment]
OK, as I haven't had any other reports of this issue so far, and I know there are other users with Smart Lighting who I think would have chimed in either here, or on the Homebridge plugin, I guess I'm wondering if there's any chance you authenticated using a different account than the addon was using previously.  Perhaps an account that has not been granted access to the lights?

I ask this because I noticed in the screenshot you provided that it says "Account does not have access to set volume on base station", this indicates that you are not using the primary account for sure.  This is of course OK, but any account you use needs to have the devices shared with it.  Just for a test, you might want to try using the primary account and see if that happens works.

Honestly, that's just a shot in the dark because I don't know what else it could be since nothing else on the addon side has changed.

**Comment by Grey-Lancaster** [comment]
Well that did it.  I have always used the secondary accout with the add-on.  No clue.  Tried to look at ring.com for permissions but none of the lights show up as devices under either login...
Thanks for all you do !
Grey
![ring4](https://user-images.githubusercontent.com/20055899/127409535-29877cab-0938-43dc-9128-87c90bece3c1.JPG)

**Comment by Grey-Lancaster** [comment]
No clue what changed but according to a post in community it never worked
Hey @ajs. For the Smart Lighting system, there is not a way to add shared users to the devices at this time, so this would be the reason why. I will make sure to pass on your feedback and desire to have shared users on this system to the appropriate teams for you though!

**Comment by tsightler** [comment]
It may be that the API updates that Ring pushed out yesterday tightened up the security around lighting.  Perhaps the feature wasn't available in the app but the devices were clearly available in the API we were previously using or it wouldn't have worked for you.  Unfortunately, that API was completely removed as part of yesterday's updates, and I'm guessing the new API enforces these sharing permissions on the backend.  I may need to make a note of it in the readme.
