### ISSUE TITLE
'dict object' has no attribute 'batteryLevel' when rendering '{{value_json["batteryLevel"]}}'

### ISSUE THREAD

**Issue by jcgoette** [tsightler/ring-mqtt#219]
I think this is the correct repo for this bug. If not, I apologise and will be happy to move as necessary. If this is an MQTT issue and not a Ring issue, I apologise for that as well. 😅 

### Describe the bug
Warning-level logger issue that seems to be related to ring-mqtt and [potentially these lines](https://github.com/home-assistant/core/blob/73bc0267e9b40ef170080011e2a31b454f888f5d/homeassistant/helpers/template.py#L1401-L1422) being referenced via ring-mqtt and/or MQTT?

### Debug Logs
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1366
First occurred: 9:33:37 PM (28 occurrences)
Last logged: 9:51:27 PM

Template variable warning: 'dict object' has no attribute 'batteryLevel' when rendering '{{value_json["batteryLevel"]}}'
```

**Comment by tsightler** [comment]
It's just a warning message, it has no other impact (it was a change to log this as a warning in 2021.4).  It will be addressed before HA makes this an error in 2021.10 but it's otherwise totally cosmetic.

**Comment by jcgoette** [comment]
[Documentation for future.](https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates)

**Comment by tsightler** [comment]
Thanks for the info, I'm already quite aware of it, I just don't care too much.  Maybe I will care by October.  :)

**Comment by jcgoette** [comment]
I figured you're aware, just adding doc for anyone that comes across this in their searches. ☺️

**Comment by tsightler** [comment]
Sorry if I sound grumpy about it, I just think this is a change they could have implemented without breaking the common MQTT discovery case.
