### ISSUE TITLE
Error running docker run

### ISSUE THREAD

**Issue by TheCellMC** [tsightler/ring-mqtt#22]
Hi,
I've followed the instructions and have the files for the bridge stored in /opt/ring-alarm-mqtt.

However, whenever I run this command, I get the following error.

`sudo docker run  -e "MQTTHOST={host name}" -e "MQTTPORT={host port}" -e "MQTTRINGTOPIC={host ring topic}" -e "MQTTHASSTOPIC={host hass topic}" -e "MQTTUSER={mqtt user}" -e "MQTTPASSWORD={mqtt pw}" -e "RINGUSER={ring user}" -e "RINGPASS={ring pq}" ring-alarm-mqtt/ring-alarm-mqtt`

```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-16T06_37_26_415Z-debug.log
```

Any help would be greatly appreciated.

**Comment by tsightler** [comment]
I think this is due to a small bug which snuck in when I merged the docker support as I somehow overwrote the changes to package.json.  I've committed a fix for that in the current master tree, so please reclone and try again.  Let me know if it still doesn't work for you.

**Comment by TheCellMC** [comment]
Thanks, that worked
