### ISSUE TITLE
New State

### ISSUE THREAD

**Issue by trounce1** [tsightler/ring-mqtt#222]
Hi,

I asked for this a while ago and i think it was mis interpreted https://github.com/tsightler/ring-mqtt-ha-addon/issues/50

I would just like there to be a way to detect that the alarm has tried to arm so that it can be a triggerable state in HA

Is this possible?

Cheers

**Comment by trounce1** [comment]
like publishing a state whenever the alarm has attempted to arm

**Comment by tsightler** [comment]
I still don't think I understand what you are requesting. There's is no "try to arm" state, the alarm either arms or rejects the request to arm, that's it.  If you attempt to arm via the addon and it fails, then this can be detected by checking if the alarm entered the requested state or not.

However, if you attempt to arm via some other means, such as the Ring app or the keypad, I can't find any way to know that such an event even occurred, there's nothing in event history and I don't see any data events with such a status, so I don't see how I can do anything with that.

If you are asking only for arming attempts via the addon then this would technically be possible, but you should be able to do this simply enough already within the automation with something like wait_for_trigger on the state of the alarm, i.e. if you attempt to set armed state, and then wait_for_trigger on that state for a few seconds, and that times out, then it didn't work.

**Comment by tsightler** [comment]
@trounce1 Could you please reply to my comments above?  If you are unable to explain to me the use case then this request isn't going anywhere, just like the last one.

**Comment by tsightler** [comment]
Closing due to no reply.  If I understand the request properly it might be addressed in the future with a feature I have planned that allows for enabling bypass granularly vs the automatic bypass that is currently available, but it could be a while before that feature sees the real world due to limited time to work on it.

**Comment by trounce1** [comment]
@tsightler so the aim i want to be able to do is, when i go to set the alarm from the panel, if a door or window is open that shouldnt be, it will trigger an action. but to be able to trigger, i need to detect the 'failed to arm due to sensors not being closed' state.

**Comment by tsightler** [comment]
Wow, a response ~3 years later, I can tell this is a critical feature for you!  :)

What do you mean by "set the alarm from the panel"?  Do you mean the Ring keypad, or the virtual alarm control panel in HA?

**Comment by trounce1** [comment]
Yes the keypad. The physical one

**Comment by tsightler** [comment]
Can you provide an example of what exactly you would want to do with an automation in this case?
