### ISSUE TITLE
MQTT not pulling in new Ring devices

### ISSUE THREAD

**Issue by j6s33m** [tsightler/ring-mqtt#229]
I followed your instructions with the release of 4.7.0 and have restarted HASS, deleted and reconfigured the MQTT integration and the Ring devices are now not loading into HASS at all. Is there a new MQTT setup I need?

**Comment by tsightler** [comment]
There are no changes required to the MQTT setup, nothing has changed in regards to how the MQTT connection works, you should not have to delete or reconfigure MQTT in any way, only a restart was recommended.  Even the restart was not required, it just helps to avoid some error messages in the logs, which people seem to freak out about.  Without logs it's difficult to guess what the problem might be.

**Comment by j6s33m** [comment]
,-------------------------------------------------------
,| Ring Devices via MQTT                               |
,|                                                     |
,| Report issues at:                                   |
,| https://github.com/tsightler/ring-mqtt              |
,-------------------------------------------------------
,ring-mqtt.js version: 4.7.0
,Node version v14.17.5
,NPM version 6.14.14
,git version 2.26.3
,-------------------------------------------------------
,Running ring-mqtt...
,  ring-mqtt Using configuration file: /data/config.json +0ms
,  ring-mqtt Configuration file not found, attempting to use environment variables for configuration. +3ms
,  ring-mqtt Reading latest data from state file: /data/ring-state.json +1ms
,  ring-mqtt Attempting connection to Ring API using saved refresh token. +75ms
,  ring-mqtt Connection to Ring API successful +1s
,  ring-mqtt Starting connection to MQTT broker... +3ms
,  ring-mqtt MQTT connection established, processing locations... +51ms
,  ring-mqtt File /data/ring-state.json saved with updated refresh token. +1ms
,  ring-mqtt Home Assistant state topic homeassistant/status received message: offline +42ms
,  ring-mqtt -------------------------------------------------------------------------------- +2s
,  ring-mqtt New location: XXXXX (xxxxx) +1ms
,  ring-mqtt TypeError: this.initMotionEntity is not a function
,  ring-mqtt     at new Beam (/app/ring-mqtt-docker/devices/beam.js:14:22)
,  ring-mqtt     at getDevice (/app/ring-mqtt-docker/ring-mqtt.js:109:20)
,  ring-mqtt     at updateRingData (/app/ring-mqtt-docker/ring-mqtt.js:209:36)
,  ring-mqtt     at processTicksAndRejections (internal/process/task_queues.js:95:5)
,  ring-mqtt     at async processLocations (/app/ring-mqtt-docker/ring-mqtt.js:267:5) +1s

**Comment by SenexCrenshaw** [comment]
Same here.  I added in a new device "kitchen pir" it sees it but never adds it...... It also just stops at that last line.

```
2021-08-17T14:30:55.061Z ring-mqtt   New device: kitchen pir (sensor.motion)
2021-08-17T14:30:55.061Z ring-mqtt               020e5985-e722-48f8-bb83-74350b77839e
2021-08-17T14:30:55.061Z ring-mqtt   Unsupported device: bridge.flatline
2021-08-17T14:30:55.062Z ring-mqtt --------------------------------------------------------------------------------
2021-08-17T14:30:55.062Z ring-mqtt New location: XXXX (XXXX)
2021-08-17T14:30:55.593Z ring-mqtt TypeError: this.initMotionEntity is not a function
    at new Beam (/app/ring-mqtt-docker/devices/beam.js:14:22)
    at getDevice (/app/ring-mqtt-docker/ring-mqtt.js:109:20)
    at updateRingData (/app/ring-mqtt-docker/ring-mqtt.js:209:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async processLocations (/app/ring-mqtt-docker/ring-mqtt.js:267:5)
2021-08-17T14:30:56.037Z ring-mqtt Account has access to set volume on base station, enabling volume control
```

**Comment by tsightler** [comment]
Ah yes, stupid bug on my part.  As mentioned in the release notes/changelog, I don't own any Ring smart lighting so can't easily test it.  I pushed a fix to the "dev" branch.  Can you please try it out?  In the config just change the "branch" config parameter from "addon" to "dev" and let me know the result.  If it works I'll get a 4.7.1 release out soon as I already have one other bug in there as well.

**Comment by jondy22** [comment]
The fix worked for me. Thanks!

**Comment by SenexCrenshaw** [comment]
woot! That worked. Thanks for all the work on this. its great!

**Comment by j6s33m** [comment]
Glad it seems to be working. I'll wait for 4.7.1 push today (hopefully) to confirm that my problem is solved. Since I'm not using HASS Supervisor, I can't test your fix as described above.

**Comment by tsightler** [comment]
How are you running it?  If via Docker you can add "BRANCH=dev" environment variable to do the same thing.

**Comment by j6s33m** [comment]
That fixed it. Thanks!

**Comment by tekmaven** [comment]
Fix worked for me as well.  Should be good to release it.  Thank you for all the great work on ring-mqtt!  👍  🥇

**Comment by tsightler** [comment]
Since this issue was causing a critical failure I went ahead and pushed 4.7.1, so it's out now.  You can remove the dev branch setting and upgrade and hopefully everything will be good.

If you see any other issues with smart lighting devices please feel free to open a new issue.

**Comment by j6s33m** [comment]
Since the 4.7.1 update, I'm seeing ring-mqtt crash almost every two hours and quickly restart. Here's the error I'm seeing in the logs:

> ring-mqtt Exit code: TypeError: Cannot read property 'hasOwnProperty' of undefined +4s | stdout

**Comment by tsightler** [comment]
I would suggest opening a new issue for investigation.  That's going to be a difficult one without more data.

**Comment by tsightler** [comment]
You could also try the dev branch again as it already has some fixes that might address the issue as the previous code was missing some checks around optional entities which could certainly impact smart lighting devices, although I don't understand how it wouldn't just crash immediately.

**Comment by j6s33m** [comment]
I actually switched it back to dev about 3 hrs ago and am still experiencing the crash. Again...it's really strange because it only happens every 1-2 hrs. I'm trying to get more logs for you, but my ring-mqtt is extremely chatty (with a lot of devices) and portianer has a hard time handling requests for thousands of rows of logs.

**Comment by tsightler** [comment]
Just about 15 minutes ago I pushed a set of fixes that I had running locally that might address this so maybe the next restart will be the one to fix it when it pulls in the latest dev.  I'm not seeing this on my own instance so I assume it must be related to some device I don't have and beams/smart lighting is the most likely culprit since it has optional entities and uses hasOwnProperty during data processing, but I still don't understand how it would work at all if that's the case.

**Comment by j6s33m** [comment]
Here are some more logs from earlier. This section of logs _**did not**_ cause the container to crash, but you can see the 'hasOwnProperty' error below in bold and the logs before / after it.

> 2021-08-18T15:35:46.821646741Z   ring-mqtt Backyard ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/211e566e-6ee8-4d0e-bd43-5395c48f5829/motion/state OFF +4s
> 2021-08-18T15:35:46.822246077Z   ring-mqtt Backyard ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/211e566e-6ee8-4d0e-bd43-5395c48f5829/light/state OFF +0ms
> 2021-08-18T15:35:46.822308618Z   ring-mqtt Backyard ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/211e566e-6ee8-4d0e-bd43-5395c48f5829/beam_duration/state 60 +0ms
> 2021-08-18T15:35:46.822753325Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/motion/state OFF +1ms
> 2021-08-18T15:35:46.822913125Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/light/state OFF +0ms
> 2021-08-18T15:35:46.822967792Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/light/brightness_state 100 +0ms
> 2021-08-18T15:35:46.823083171Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/beam_duration/state 60 +0ms
> 2021-08-18T15:35:46.823237309Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/info/state {"batteryLevel":98,"batteryStatus":"charged","commStatus":"ok","lastCommTime":"2021-08-18T14:39:02Z","lastUpdate":"2021-08-18T14:39:02Z","serialNumber":"RBPS12018BK001869","tamperStatus":"ok"} +1ms
> 2021-08-18T15:35:46.823379964Z   ring-mqtt Pathlight - Lounge Chairs ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/20b845bc-cb23-4c01-81a5-b24299d8789d/battery/attributes {"batteryLevel":98,"batteryStatus":"charged"} +0ms
> 2021-08-18T15:35:46.823736542Z   ring-mqtt TypeError: Cannot read property 'hasOwnProperty' of undefined
> 2021-08-18T15:35:46.823807958Z   ring-mqtt     at Beam.publishData (/app/ring-mqtt-dev/devices/beam.js:63:32)
> 2021-08-18T15:35:46.823847664Z   ring-mqtt     at Beam.publish (/app/ring-mqtt-dev/devices/base-socket-device.js:29:18) +30s
> 2021-08-18T15:35:46.829333198Z   ring-mqtt Pathlight - Top Steps ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/4940a6a5-6ed0-4dad-bd15-1e3dd394662b/motion/state OFF +6ms
> 2021-08-18T15:35:46.829620325Z   ring-mqtt Pathlight - Top Steps ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/4940a6a5-6ed0-4dad-bd15-1e3dd394662b/light/state OFF +0ms
> 2021-08-18T15:35:46.829689945Z   ring-mqtt Pathlight - Top Steps ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/4940a6a5-6ed0-4dad-bd15-1e3dd394662b/light/brightness_state 100 +0ms
> 2021-08-18T15:35:46.829731440Z   ring-mqtt Pathlight - Top Steps ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/4940a6a5-6ed0-4dad-bd15-1e3dd394662b/beam_duration/state 0 +0ms
> 2021-08-18T15:35:46.829890001Z   ring-mqtt Pathlight - Top Steps ring/a156f9e6-15f8-4583-b009-bf4d98f92118/lighting/4940a6a5-6ed0-4dad-bd15-1e3dd394662b/info/state

**Comment by tsightler** [comment]
Yeah, that's one of the fixes that has been pushed, there was no check to see if the entity existed prior to attempting to publish, so it caused the undefined error, but I would not expect this to be a catastrophic error, it would have been happening all along.  That message should be fixed in current dev however.

**Comment by j6s33m** [comment]
> Yeah, that's one of the fixes that has been pushed, there was no check to see if the entity existed prior to attempting to publish, so it caused the undefined error, but I would not expect this to be a catastrophic error, it would have been happening all along. That message should be fixed in current dev however.

Will keep you posted to see if I get another crash, but so far so good.

**Comment by tsightler** [comment]
Hi @j6s33m do you happen to have an update?  I'd like to get a 4.7.2 out there if this seems to have fixed the issue for you.

**Comment by j6s33m** [comment]
Yes it appears that your updates fixed my container from crashing. It's been about 30 hrs since my last crash.

Thank you!
