### ISSUE TITLE
Schlage Encode Door Lock not showing up in MQTT

### ISSUE THREAD

**Issue by tekwreck** [tsightler/ring-mqtt#239]
I have a Schlage Encode door lock added to my Ring Alarm and I can manage it from my Ring Dashboard but its not showing up as a list of entities with my HA integration. Anyway I can help troubleshooting making that work.

**Comment by tsightler** [comment]
Isn't the Encode a wifi smart lock?  Only Z-wave locks connected via the alarm base station are supported.  Wifi locks are not accessible via the Ring API, rather the Ring app consumes these 3rd party devices directly via their own APIs directly (via Amazon Key I believe, but perhaps others).   Unfortunately, this means that this project cannot support those devices as it only has access to the Ring API.

**Comment by tsightler** [comment]
I will update the documentation to make it more clear that only Z-wave based locks are supported.  Wifi smart locks integrated via Amazon Key are not supported.
