### ISSUE TITLE
Snapshot Interval not turning off/accepting 0

### ISSUE THREAD

**Issue by seanmccabe** [tsightler/ring-mqtt#244]
Was testing using the snapshot interval to intermittently get snapshots from my Ring Viewcam (battery operated). Having turned this on (and missed typed) for 10 seconds intervals I then began getting constant snapshots (every 10 seconds) as expected.
However, I was then unable to turn this off through Home Assistant. Attempting to clear the field (back to what it was) just gave me an onscreen error (line turned to red, to indicate invalid input). 
Gives error in HA:
`Payload '' is not a Number`
I also then tried to set it to 0 (thinking perhaps this means turn off), but this was also not accepted.

Attempted to restart the Ring-MQTT docker container as this has snapshots set to motion. This did not remove the value from HA.

I eventually managed to use another MQTT program I have to publish:
`command = 0` to '.../snapshot_interval' to cease the constant pushing.

Hoping by entering this, perhaps a switch, can be added to turn off snapshots, or it can be accepted that entering 0, or clearing the fields issues a 0 command.

**Comment by tsightler** [comment]
Not really sure what you are asking for, the snapshot interval setting is not currently dynamic, it is either enabled or disabled on startup based on the config value (if you disable it in the config the value doesn't go away in HA, but it should also not have any effect unless you change it).  As documented, if you enable it with interval setting, you can set it to any value between 10-3600 seconds.  Values below 10 seconds, including 0, are not allowed.

Currently I have no plans to make this a dynamic setting, but as a workaround you could probably just set it to 3600 seconds.  One snapshot per hour is unlikely to negatively impact battery life in any significant way.

**Comment by seanmccabe** [comment]
Yer suppose I was asking for the ability to turn it off dynamically if it is activated.

Would be handy if the battery gets down to a low level and want to extend it as much as possible if you are unable to charge.
Or in my case, I only want it on intermittently. 
I.e. Was hoping to turn it on to take a snapshot when a certain trigger is activated (doorbell pressed, motion detected on another camera (not Ring)) and then send the snapshot as an attachment and turn it off again when motion stopped, or door opened. 
Sort of as a work around to not being able to manually trigger a snapshot on demand.

Suppose once an hour isn't bad, and it won't do anything in terms of any other automation.

**Comment by tsightler** [comment]
It would probably have to be implemented as a switch because, right now, I reject any values lower than 10.  For example, above you said you used another tool, but that doesn't really make sense because the code actually rejects values under 10 from any tool (I just checked it to be 100% sure) and it simply logs that it's out of range.  The only way to turn the feature off today is to change the config and restart.

Accepting 0 is a less than ideal solution because there's no way in HA to tell the number object to accept only 10 or higher but then to also accept 0.  Of course, I could modify the code to ignore values between 1-9, which it already does, but right now it's also blocked in the UI using the min/max settings for the number entity.  If I allows 0-9, but just ignore 1-9 then I'll get bug reports on that because people will try it and it won't work, so it's not a great option.

Honestly, the easiest thing to do is probably just to allow a higher value, something like 999,999, which is almost 12 days.  Then you can just re-publish a value whenever you want a snapshot.  It's almost like snapshot on demand without it being so obvious.

**Comment by seanmccabe** [comment]
Mmmm I don't know how I turned it off then, I definately used an MQTT broweser to edit the value, or delete them and they stopped, but just tried it again and I didn't work.
Unfortunately it seems once that interval is set, you can't then turn it off, which poses a bit of a problem. 

I've done as you've suggested this time around (since I can't seem to remove the config) and set it to the highest value. Probably don't need something as high as 999 999, even 7 days would be suitable I think and it gives a nice round period. 12 Days is an odd amount as its not quite a fortnight, but more than a week. Just personal OCD preference ;)

Alternative, would be, could you accept -1, to clear the config, easier than ignoring 1-9, and a bit more difficult for most people to enter/stumble upon.  Doing so could clear the config?

**Comment by tsightler** [comment]
An earlier version, before I switched to using a number entity in HA, may have allowed setting 0, I don't remember for sure, but the feature was never intended to be dynamic, it's either on or off.

However, extending the time is super easy, something I could do in the next update.  The 3600 limit was just an arbitrary value.

**Comment by seanmccabe** [comment]
Would appreciate that :)

**Comment by seanmccabe** [comment]
Got the "_ondemand_" snapshot functionality working so that works great.
Will update my values once you do the update, but no rush :)

**Comment by tsightler** [comment]
Version 4.8.0 allows the snapshot interval to be set to 604,800 seconds max.  That's one snapshot every 7 days.  In the future I'll consider accepting 0 or having some switch to turn interval snapshot on/off (honestly, the entire logic is spaghetti code that needs to be rewritten with a more solid concept) but that should be a decent workaround for now.  One snapshot every 7 days is almost the same as being turned off.

**Comment by seanmccabe** [comment]
I've just updated and all seems to work flawlessly, great job :)
