### ISSUE TITLE
Now showing in Homekit

### ISSUE THREAD

**Issue by bryangauvin** [tsightler/ring-mqtt#25]
Hello,
    I finally got this up and running and its showing in HA and the alarm panel is working. However its not translating into Homekit. I only have excludes and no includes on the config. Any idea what is holding it up from loading into Homekit?

**Comment by tsightler** [comment]
This script doesn't have anything to do with Homekit and I don't use Homekit so this isn't really the appropriate place to post issues with Homekit integration.  You'd probably be better off asking on the Home Assistant forum.

You could always setup Homebridge with the [homebridge-ring](https://www.npmjs.com/package/homebridge-ring) plugin to integrate with Homekit as it has more features anyway.

**Comment by broyuken** [comment]
You need to disable auto start for HomeKit in ha and set a delay via an automation so that the devices are loaded in ha before HomeKit starts. I did a 15 second delay and it worked for me.
