### ISSUE TITLE
Polling with very high frequency

### ISSUE THREAD

**Issue by Ramias1** [tsightler/ring-mqtt#264]
ring sets their DNS TTL very low.  This also seems to poll every few seconds.  The ring-client-api supports configuring polling intervals > 2 seconds.  Could you please consider adding those options as docker env variables?

Thank you

**Comment by tsightler** [comment]
Only camera dings are polled every 2 seconds, everything else for cameras is every 20 seconds, alarm events use a websocket so don't poll at all.  What good is polling for motion/ding events slower than every 2 seconds?  What is the use case?

**Comment by Ramias1** [comment]
ah good point.  In my case I use this with a secondary home automation system via MQTT and my primary for HomeKit uses the Homebridge plugin.  So I have two systems hitting Ring every two seconds.  But I only need real time on one.  Probably an edge case.  Thanks

**Comment by tsightler** [comment]
I'm not super interested in adding even more options, especially for edge cases, as I already think there are too many options.  I guess I'd suggest just forking the project and building your own custom image with the values tweaked for your use case.
