### ISSUE TITLE
Support MQTTS and Client Certificates

### ISSUE THREAD

**Issue by jamesonuk** [tsightler/ring-mqtt#281]
I have my MQTT server setup but it is using MQTTS and client certificates for authentication.

I have had a play with mqtt JS and connecting is just a case of adding 
```
  key: fs.readFileSync('my.key.pem'),
  cert: fs.readFileSync('my.cert.pem'),

  // Necessary only if the server uses a self-signed certificate.
  ca: [ fs.readFileSync('root.ca.pem') ],
```
to the connect options in
```
// Initiate the connection to MQTT broker
function initMqtt() {
    const mqtt_user = CONFIG.mqtt_user ? CONFIG.mqtt_user : null
    const mqtt_pass = CONFIG.mqtt_pass ? CONFIG.mqtt_pass : null
    const mqtt = mqttApi.connect({
        host:CONFIG.host,
        port:CONFIG.port,
        username: mqtt_user,
        password: mqtt_pass
    });
    return mqtt
}
```
(I think host needs to also have the protocol so I think it needs to be "mqtts://host" I used mqttApi.connect('mqtts://my-server:8883', { --> }) for testing)

What I haven't been able to figure out is how the `CONFIG` stuff works or what else might need updating as a result but adding these options would be really helpful to allow me to use my MQTT setup

**Comment by tsightler** [comment]
Won't be added any time soon since it's not needed for 99.99% of users.  Might entertain a pull request if it's easy to setup and document.  Otherwise, you could run a local MQTT broker that only listens on localhost and bridge it to your primary broker via TLS and certificate auth.
