### ISSUE TITLE
Standalone run quits with rtsp-simple-server error

### ISSUE THREAD

**Issue by xraken** [tsightler/ring-mqtt#284]
**Describe the bug**  
I am trying to run ring-mqtt.js from bash prompt but it quits with an ENOENT error. I am getting a bunch of data pushed to MQTT but ring-mqtt.js quits right after that.
$ /usr/bin/node ./ring-mqtt.js
Error: spawn rtsp-simple-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn rtsp-simple-server',
  path: 'rtsp-simple-server',
  spawnargs: [
    '/home/user/ring-mqtt/lib/../config/rtsp-simple-server.yml'
  ]
}

**Describe your environment**  
$ uname -srnvam
Linux nashost 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ /usr/bin/node -v
v14.18.1

**Describe your settings and what you've tried**  
$ cat config.json
{
    "host": "mosq",
    "port": 1883,
    "mqtt_user": "xxx",
    "mqtt_pass": "xxx",
    "ring_token": "xxx",
    "disarm_code": "",
    "beam_duration": 0,
    "enable_cameras": true,
    "snapshot_mode": "none",
    "livestream_user": "",
    "livestream_pass": "",
    "enable_modes": false,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ],
    "beams_duration": 0
}
$cat /home/user/ring-mqtt/lib/../config/rtsp-simple-server.yml
readTimeout: 5s
readBufferCount: 1024

rtspDisable: no
protocols: [tcp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: yes

hlsDisable: yes

api: yes
apiAddress: 127.0.0.1:8880

paths:
  all:
    fallback:
    disablePublisherOverride: no
$
**Debug Logs**  
$ DEBUG=ring-* /usr/bin/node ./ring-mqtt.js
  ring-mqtt Using configuration file: ./config.json +0ms
  ring-mqtt Attempting connection to Ring API using refresh token from file: ./config.json +60ms
  ring-mqtt Connection to Ring API successful +2s
  ring-mqtt Starting connection to MQTT broker... +1ms
  ring-mqtt Config file saved with updated refresh token. +24ms
  ring-mqtt MQTT connection established, processing locations... +4ms
  ring-mqtt -------------------------------------------------------------------------------- +1s
  ring-mqtt New location: YYY (xxx) +0ms
  ring-mqtt   New device: Name (33) +2ms
  ring-mqtt               doorbell +0ms
  ring-mqtt -------------------------------------------------------------------------------- +0ms
  ring-mqtt Ring location/device data updated, sleeping for 5 seconds. +0ms
  ring-rtsp ------------------------------------------------------------------------- +0ms
  ring-rtsp Starting rtsp-simple-server process... +0ms
  ring-mqtt ERROR - Uncaught Exception +2s
Error: spawn rtsp-simple-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn rtsp-simple-server',
  path: 'rtsp-simple-server',
  spawnargs: [
    '/home/user/ring-mqtt/lib/../config/rtsp-simple-server.yml'
  ]
}
  ring-mqtt The ring-mqtt process is shutting down... +1s
  ring-mqtt Setting all devices offline... +1ms
  ring-disc Publishing new device id: 33 disc +0ms
  ring-disc HASS config topic: homeassistant/binary_sensor/xxx_motion/config +0ms
  ring-disc {
  ring-disc   name: 'Name Motion',
  ring-disc   unique_id: '33_motion',
  ring-disc   state_topic: 'ring/xxx/camera/33/motion/state',
  ring-disc   device_class: 'motion',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/motion/attributes',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/switch/xxx_stream/config +2ms
  ring-disc {
  ring-disc   name: 'Name Live Stream',
  ring-disc   unique_id: '33_stream',
  ring-disc   state_topic: 'ring/xxx/camera/33/stream/state',
  ring-disc   command_topic: 'ring/xxx/camera/33/stream/command',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/stream/attributes',
  ring-disc   icon: 'mdi:cctv',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/switch/xxx_event_stream/config +1ms
  ring-disc {
  ring-disc   name: 'Name Event Stream',
  ring-disc   unique_id: '33_event_stream',
  ring-disc   state_topic: 'ring/xxx/camera/33/event_stream/state',
  ring-disc   command_topic: 'ring/xxx/camera/33/event_stream/command',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/event_stream/attributes',
  ring-disc   icon: 'mdi:vhs',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/select/xxx_event_select/config +0ms
  ring-disc {
  ring-disc   name: 'Name Event Select',
  ring-disc   unique_id: '33_event_select',
  ring-disc   state_topic: 'ring/xxx/camera/33/event_select/state',
  ring-disc   command_topic: 'ring/xxx/camera/33/event_select/command',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/event_select/attributes',
  ring-disc   options: [
  ring-disc     'Ding 1',      'Ding 2',
  ring-disc     'Ding 3',      'Ding 4',
  ring-disc     'Ding 5',      'Motion 1',
  ring-disc     'Motion 2',    'Motion 3',
  ring-disc     'Motion 4',    'Motion 5',
  ring-disc     'On-demand 1', 'On-demand 2',
  ring-disc     'On-demand 3', 'On-demand 4',
  ring-disc     'On-demand 5'
  ring-disc   ],
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/binary_sensor/xxx_ding/config +2ms
  ring-disc {
  ring-disc   name: 'Name Ding',
  ring-disc   unique_id: '33_ding',
  ring-disc   state_topic: 'ring/xxx/camera/33/ding/state',
  ring-disc   device_class: 'occupancy',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/ding/attributes',
  ring-disc   icon: 'mdi:doorbell-video',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/sensor/xxx_info/config +0ms
  ring-disc {
  ring-disc   name: 'Name Info',
  ring-disc   unique_id: '33_info',
  ring-disc   state_topic: 'ring/xxx/camera/33/info/state',
  ring-disc   device_class: 'timestamp',
  ring-disc   value_template: '{{ value_json["lastUpdate"] | default("") }}',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/info/state',
  ring-disc   icon: 'mdi:information-outline',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-disc HASS config topic: homeassistant/sensor/xxx_wireless/config +0ms
  ring-disc {
  ring-disc   name: 'Name Wireless',
  ring-disc   unique_id: '33_wireless',
  ring-disc   state_topic: 'ring/xxx/camera/33/info/state',
  ring-disc   device_class: 'signal_strength',
  ring-disc   unit_of_measurement: 'dBm',
  ring-disc   value_template: '{{ value_json["wirelessSignal"] | default("") }}',
  ring-disc   json_attributes_topic: 'ring/xxx/camera/33/wireless/attributes',
  ring-disc   availability_topic: 'ring/xxx/camera/33/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '33' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +1ms
  ring-disc HASS config topic: homeassistant/sensor/xxx_battery/config +0ms
  ring-disc {
  ring-disc   name: 'Name Battery',
  ring-disc   unique_id: '3_battery',
  ring-disc   state_topic: 'ring/xx/info/state',
  ring-disc   device_class: 'battery',
  ring-disc   unit_of_measurement: '%',
  ring-disc   state_class: 'measurement',
  ring-disc   value_template: '{{ value_json["batteryLevel"] | default("") }}',
  ring-disc   json_attributes_topic: 'x/attributes',
  ring-disc   availability_topic: 'x/status',
  ring-disc   payload_available: 'online',
  ring-disc   payload_not_available: 'offline',
  ring-disc   device: {
  ring-disc     ids: [ '1111' ],
  ring-disc     name: 'Name',
  ring-disc     mf: 'Ring',
  ring-disc     mdl: 'Unknown Model'
  ring-disc   }
  ring-disc } +0ms
  ring-mqtt Exit code: 2 +3s

**Comment by tsightler** [comment]
An enoent error simply means that the file is not found.  That implies that you have not installed rtsp-simple-server in a path that the script can find.  This is a requirement for the standard install to work and is one if the documented steps.

I believe on the forum you said you were running HA core in Docker so why not use the recommended Docker install which includes everything you need in the image?

**Comment by xraken** [comment]
I was just trying out the simple command line version to get it going first. Anyway for future reference for anyone running into the same issue, installing rtmp-simple-server with this command resolved the problem:

`curl -L -s "https://github.com/aler9/rtsp-simple-server/releases/download/v0.17.6/rtsp-simple-server_v0.17.6_linux_amd64.tar.gz" | sudo tar zxf - -C /usr/local/bin rtsp-simple-server`
