### ISSUE TITLE
Devices not found

### ISSUE THREAD

**Issue by McMornan** [tsightler/ring-mqtt#287]
**Describe the bug**  
I installed the latest ring-mqtt docker image (4.8.5) on my synology system (havebeen running 4.8.0 without a problem so far for the past weeks) After the upgrade the system starts normally - but after location discovery no devices are found. 

**Describe your environment**  
Synology NAS 915+ (20 GB Ram, 4 core intel)

**Describe your settings and what you've tried**  
I asked google and only found the "no device" issue with HA (I use openhab). So I have restarted the container at least 10 times, and replaced the ring token in the environment variable twice with a brand new token.

stopping the 4.8.5 container and starting the 4.8.0 works immediately ...

**Debug Logs** 
![log](https://user-images.githubusercontent.com/27871438/138585825-bc7b3886-8014-45cc-b370-817da68e0202.jpg)

**Comment by tsightler** [comment]
What devices do you have?  If it's only cameras have you definitely set the ENABLECAMERAS variable correctly?  Please post your environment settings for the Docker container.

**Comment by McMornan** [comment]
Hi,

you were right of course ... while copying my environment settings to post them here I noticed I had forgotten "enablecameras" in the environment .... duh :(  Added it, worked immediately.

May I suggest you printout a summary of recognized environment variables during startup ? Might have brought me on the right track, without stealing your time.

cheers,
Lars

**Comment by McMornan** [comment]
solved
