### ISSUE TITLE
RTSP-Simple-Server not accepting runOnDemandCloseAfter

### ISSUE THREAD

**Issue by Bradley225** [tsightler/ring-mqtt#289]
Hi, I am using Ring-MQTT with Home Assistant in a standard install. 

After days of debugging and editing the file RTSP-Simple-Server.js to understand the reason for Bad Request 401 when adding to the RTSP-Simple-Server list of cameras I can tell that for some reason when runOnDemandCloseAfter is included I am getting 401 response code and if I take it out and leave "source": "publisher" and also the runOnDemand argument in the json object passed to got.post then I can get everything up and running (200).

IS there any reason that the server would reject runOnDemandCloseAfter as I have not changed anything at first from the file as it was and I got 401. I have tried to make the value for runOnDemandCloseAfter a string but still the same. I have tried adding runOnDemandCloseAfter in the yml file and also even by calling edit after calling add to list.

Anyone give me a possible reason why?

**Comment by tsightler** [comment]
Have you tried with rtsp-simple-server 0.17.3?  That's the version in the Docker image and the only version I have personally tested with (just another reason why I'll probably dump standard installs going forward).  It looks like there were some changes to the API in 0.17.4 and greater than might possibly cause this, although you indicate that you tried to changing the value to string.

**Comment by Bradley225** [comment]
You were right - downgrading to 0.17.3 and putting back to an integer allowed me to move forward properly.

Thank you for the project.

**Comment by tsightler** [comment]
While I welcome the change to rtsp-simple-server to support duration strings, so you can use things like "5s" of 5000000000 for the value, which is clearly more human readable, I think a change that completely breaks prior API users was at least worthy a minor version bump.  Oh well, for now I'll just update the docs for the standard installation to indicate that only the specific rtsp-simple-server v0.17.3 is supported.  Thanks!
