### ISSUE TITLE
Cameras/Snapshots suddenly not working

### ISSUE THREAD

**Issue by 400HPMustang** [tsightler/ring-mqtt#294]
#### Describe the problem
Hello. I am having a problem with my camera feeds and snapshots. Both are not working and showing as broken on my dashboard. 

![image](https://user-images.githubusercontent.com/45641587/148631741-9a62c599-2568-4b23-a75f-080490f4f664.png)

![image](https://user-images.githubusercontent.com/45641587/148631751-efad3137-5384-4edd-82ad-54d1c8ed7303.png)

## System Health

version | core-2021.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4595
Installed Version | 1.18.0
Stage | running
Available Repositories | 1003
Installed Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | beta
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 58.4 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Check Home Assistant configuration (3.9.0), SSH & Web Terminal (10.0.1), Mosquitto broker (6.0.1), Ring-MQTT with Video Streaming (4.8.5), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 39
views | 11
mode | storage

</details>

#### Describe any steps you've taken to attempt to resolve the problem
I've restarted Home Assistant, restarted the add-on, and also generated a new refresh token. 

#### Debug Logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] ring-mqtt.sh: executing... 
-------------------------------------------------------
| Ring-MQTT with Video Streaming                      |
| Addon for Home Assistant                            |
|                                                     |
| Report issues at:                                   |
| https://github.com/tsightler/ring-mqtt-hassio-addon |
-------------------------------------------------------
[cont-init.d] ring-mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
-------------------------------------------------------
ring-mqtt.js version: 4.8.5
Node version v14.17.6
NPM version 7.17.0
git version 2.32.0
-------------------------------------------------------
Using discovered MQTT Host: core-mosquitto
Using discovered MQTT Port: 1883
Using discovered MQTT User: addons
Using discovered MQTT password: <hidden>
-------------------------------------------------------
Running ring-mqtt...
2022-01-08T04:36:06.208Z ring-mqtt Using configuration file: /data/options.json
2022-01-08T04:36:06.210Z ring-mqtt Reading latest data from state file: /data/ring-state.json
2022-01-08T04:36:06.211Z ring-mqtt WARNING - Unhandled Promise Rejection
SyntaxError: /data/ring-state.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1115:22)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at main (/app/ring-mqtt/ring-mqtt.js:529:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by tsightler** [comment]
> SyntaxError: /data/ring-state.json: Unexpected end of JSON input

This error indicates that the ring-state.json file is not able to be parsed.  This is a simple json file that stores the token state for authentication.  No idea what happened to this file, it's updated regularly when tokens are refreshed, but for some reason your file can't be read anymore.  You can just delete this file and restart the addon, or remove and re-install the addon, and then re-authenticate.

**Comment by 400HPMustang** [comment]
I apologize for what might be a really dumb question but how do I find that file to delete it? If at all possible I'd rather not remove and reinstall the addon

**Comment by tsightler** [comment]
State data is stored withing the addon container so you'll need to open a shell and use docker cli to connect to the container and delete the file.  Assuming you have something like the SSH & Web Terminal addon installed you should be able to run something like:

`docker exec -it addon_03cabcc9_ring_mqtt /bin/bash`

Once you get a prompt in the container you can cd to the /data directory and delete the file there.

If you're not comfortable doing this then remove/reinstall is likely far easier.  Reinstall should take only a few minutes, you can copy the existing config, delete and the addon, re-add it from the store, and then place the config, start it up and re-authenticate.  It won't delete any of your existing devices/entities.

**Comment by 400HPMustang** [comment]
Deleting that file and then reauthenticating worked. Thank you very much.

**Comment by tsightler** [comment]
Thanks for letting me know.  This issue has been reported once or twice before, although I've never seen it myself unless I intentionally corrupt the file.  I think it's because the current code just overwrites the existing file and, if something goes wrong with the write, there's no way to get the old data back.  In a future version I plan to implement this via write-file-atomic and also improve recovery in the event of a corrupt or damaged file so that it at least doesn't require a manually deleting the file.
