### ISSUE TITLE
Delayed start is needed for Ring Alarm entities to show in HomeKit

### ISSUE THREAD

**Issue by GoWithitRoger** [tsightler/ring-mqtt#30]
For those of us wanting Ring Alarm entities to show not just in HA, but also through to HomeKit (via the HA HomeKit capabilities), it seems that a delayed start of HomeKit is needed. 

This isn’t a bug in this Ring Alarm project. But I think it would be helpful if this issue was mentioned in the documentation here. 

A delayed start being needed for Z-wave is covered in the HA HomeKit documentation. And I’ve suggested some mention being added there of this being an issue with MQTT entities, too. But even with that it wouldn’t be clear this Ring Alarm customization needs it. (I’m only assuming MQTT needs it, but it may be particular to the Ring Alarm functionality.)

I was able to get it working with a 10 second delay. But there might be a more elegant way using ‘somethingsomething.network_ready‘

**Comment by tsightler** [comment]
While I really believe this is up to the HomeKit component to fix (they should support dynamically discovered devices) I've added a small section to the README and referenced the HomeKit docs.

**Comment by respectTheCode** [comment]
I believe this has been fixed by the entity change in 104. Now that entities start with an `unavailable` state instead of missing completely HomeKit sees the entities on startup and everything works correctly.

When I upgraded to 104 my alarm showed up in HomeKit and it didn't before.

**Comment by tsightler** [comment]
Sounds good, thanks for the update.
