### ISSUE TITLE
Outdoor Siren switch is not working

### ISSUE THREAD

**Issue by Mincka** [tsightler/ring-mqtt#303]
### Describe the bug
When I turn on the **Outdoor Siren** in HA, nothing happens and the switch goes back to off a few seconds after.
It should be noted that when I use the general siren switch (associated with the alarm), the siren starts on the base station then starts on the outdoor siren, which is fine. If I need to trigger the alarm manually, I will use the general switch. I just want to let you know that the dedicated feature for the outdoor siren is not working as expected.
Thank you for this project.

### Describe your environment
I use the official HA add-on with HA, latest version.

### Describe your settings and what you've tried
No specific configuration.

### Debug Logs
In HA:

```
ring/xxx/alarm/yyy/siren/state

Received 09:38:10
QoS: 0
Payload: ON
Received 09:38:10
QoS: 0
Payload: OFF
Received 09:38:50
QoS: 0
Payload: OFF
Received 09:39:23
QoS: 0
Payload: OFF
Received 09:40:06
QoS: 0
Payload: OFF
Received 09:40:06
QoS: 0
Payload: ON
Received 09:40:07
QoS: 0
Payload: OFF
```

When looking in the addon log when switching on the outdoor siren:
```
2022-01-18T08:49:40.308Z ring-mqtt [Sirène extérieure Ring] Received set siren state ON
```

**Comment by tsightler** [comment]
The only siren that has been tested is the Dome Z-wave siren, which is Ring compatible.  I had assumed that the Ring outdoor siren would also work if it identifies itself as the same device, but somehow it doesn't surprise me that Ring would do something different as that seems to be par for the course.

Unfortunately I don't own an outdoor siren and really don't have a need for one it's unlikely I can fix this unless you can provide the device discovery data for it and it might also require some debugging.

**Comment by Mincka** [comment]
Thank your for your reply. Let me know if the following is enough or you also need the ring-device-data-cli output.

Here's the websocket response for the device status on the website. Maybe it will help you.
Timestamps, GUIDs and others IDs were removed but let me know if you need anything.

```
{
	"9": {
		"general": {
			"v2": {
				"acStatus": "error",
				"adapterType": "zwave",
				"adapterZid": "xxx",
				"batteryLevel": 100,
				"batteryStatus": "full",
				"catalogId": "xxx",
				"categoryId": 34,
				"commStatus": "ok",
				"commandTypes": {
					"communication-poll": {
						"requiresTrust": false
					},
					"reconfigure.start": {
						"requiresTrust": false
					},
					"siren-backlight.disable": {
						"requiresTrust": false
					},
					"siren-backlight.enable": {
						"requiresTrust": false
					},
					"siren-test.start": {
						"requiresTrust": false
					},
					"siren-test.stop": {
						"requiresTrust": false
					},
					"siren.start": {
						"requiresTrust": false
					},
					"update-node-neighbors.start": {
						"requiresTrust": false
					}
				},
				"deviceFoundTime": xxx,
				"deviceType": "siren.outdoor-strobe",
				"fingerprint": "xxx",
				"firmwareUpdate": {
					"eligibility": "eligible",
					"state": "up-to-date"
				},
				"impulseTypes": {
					"comm.ping.received": {
						"trusted": false
					},
					"tampered": {
						"trusted": false
					},
					"tampered-cleared": {
						"trusted": false
					}
				},
				"lastCommTime": xxx,
				"lastUpdate": xxx,
				"linkQuality": "ok",
				"managerId": "zwave",
				"manufacturerName": "Ring",
				"name": "SirÃ¨ne extÃ©rieure Ring",
				"placement": "unassigned",
				"pollInterval": 43200,
				"roomId": 2,
				"serialNumber": "xxx",
				"setupByPluginStatus": "complete",
				"setupByUserStatus": "complete",
				"subCategoryId": 0,
				"tags": [
					"kitted",
					"scanned"
				],
				"tamperStatus": "ok",
				"zid": "xxx"
			}
		},
		"device": {
			"v1": {
				"auxBattery": {
					"level": 0,
					"status": "none"
				},
				"backlightState": "disabled",
				"brightness": 0.75,
				"maxSirenDuration": 3,
				"maxVolume": 4,
				"sirenStatus": "inactive",
				"volume": 4
			}
		},
		"adapter": {
			"v1": {
				"ackChannel": 2,
				"address": "xxx",
				"dsk": [
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x,
					x
				],
				"fingerprint": {
					"extraVersions": [],
					"firmware": {
						"subversion": 11,
						"version": 1
					},
					"hardwareVersion": 1,
					"libraryType": 3,
					"manufacturerId": 838,
					"productId": 1025,
					"productType": 1793,
					"protocol": {
						"subversion": 12,
						"version": 7
					}
				},
				"homeId": "xxx",
				"nodeId": 6,
				"reconfigureState": "idle",
				"routeSpeed": "40kb/s",
				"rssiTimestamp": xxx,
				"securitySchemes": [
					"s2Authenticated"
				],
				"signalStrength": [
					{
						"nodeId": 1,
						"quality": "ok",
						"rssi": -85,
						"status": "valid",
						"zid": "xxx"
					}
				],
				"signalsMetadata": {
					"lastUpdateReason": "db-threshold-exceeded",
					"skippedUpdates": 0
				}
			}
		},
		"pending": {}
	}
}
```

Few screenshots so you can map commands with features:
![image](https://user-images.githubusercontent.com/6184289/150671938-439fba11-ef4a-4f53-aa64-340ec12e751f.png)
![image](https://user-images.githubusercontent.com/6184289/150671944-3a85feb4-cabe-45f9-8bed-4539e54494ab.png)
![image](https://user-images.githubusercontent.com/6184289/150672272-bf7435d3-1d42-40a9-85a4-24f3ad64185e.png)
![image](https://user-images.githubusercontent.com/6184289/150671952-371a6929-7dae-43de-bca0-19dd8273185a.png)
![image](https://user-images.githubusercontent.com/6184289/150671961-1e6edc25-70f0-4a8a-b1c6-590a01f4f474.png)
![image](https://user-images.githubusercontent.com/6184289/150671968-2fc7c601-8932-4b03-bae5-062388ac61f0.png)


Finally, here's a sample command for the LED Test without Siren:
```
{
	"channel": "message",
	"msg": {
		"msg": "DeviceInfoSet",
		"datatype": "DeviceInfoSetType",
		"body": [
			{
				"zid": "xxx",
				"command": {
					"v1": [
						{
							"commandType": "siren-test.start",
							"data": {
								"duration": 5000,
								"audio": false
							}
						}
					]
				}
			}
		],
		"dst": "xxx",
		"seq": 4
	}
}
```

LED Setting On with these settings:
![image](https://user-images.githubusercontent.com/6184289/150672330-ce132418-ce4e-43b8-a3b9-309077de0188.png)
LED Off, same message with enabled:false
```
{
	"channel": "message",
	"msg": {
		"msg": "CreateDeviceScheduleV2",
		"dataType": "CreateDeviceScheduleTypeV2",
		"body": [
			{
				"zid": "xxx",
				"type": "sirenBacklightSchedule",
				"name": "OutdoorSirenDuskToDawn",
				"enabled": true,
				"daysActive": [
					"sunday",
					"monday",
					"tuesday",
					"wednesday",
					"thursday",
					"friday",
					"saturday"
				],
				"startTime": 0,
				"startTimeBase": "sunset",
				"stopTime": -90,
				"stopTimeBase": "sunrise",
				"startDeviceInfoSet": {
					"command": {
						"v1": [
							{
								"commandType": "siren-backlight.enable",
								"data": {}
							}
						]
					}
				},
				"stopDeviceInfoSet": {
					"command": {
						"v1": [
							{
								"commandType": "siren-backlight.disable",
								"data": {}
							}
						]
					}
				}
			}
		],
		"seq": 6
	}
}
```

Volume and duration:
![image](https://user-images.githubusercontent.com/6184289/150672374-1978146a-5a06-4b3b-8941-a565aaabe5a7.png)
Possible durations: 1 to 10 minutes
Silent = volume: 0
Loudest = volume: 4
```
{
	"channel": "message",
	"msg": {
		"msg": "DeviceInfoSet",
		"datatype": "DeviceInfoSetType",
		"body": [
			{
				"zid": "xxx",
				"device": {
					"v1": {
						"maxSirenDuration": 3,
						"volume": 4
					}
				}
			}
		],
		"dst": "xxx",
		"seq": 9
	}
}
```

I can provide all the others commands with payload details that you need. I just don't want bother my neighbors on Sunday. 😝
Actually, I gave details for all main commands I guess. Only siren.start is missing. I will provide it when possible but I think it won't have any specific options.

**Comment by tsightler** [comment]
My gut says that I just need to call siren-test.start and siren-test.stop commands.  This didn't do anything for the Dome siren, but maybe that's used only for the Ring siren.

**Comment by Mincka** [comment]
I need to check what's behind the big "Sound Siren" button. It looks like mapped to siren.start and this one may also trigger notifications on connected phones. And it looks like there's a "Silent Siren" button described in the doc and I am curious to see what's the related command since I don't see a siren.stop command. I will know soon.

I provided additional commands if you wish to add configuration (controls) sensors and switches for advanced automation scenarios.
E.g. Using scenes to set the siren at a specific volume and durations depending on the time of the day, or the type of event.
For instance, if someone is home or if it's night, I may want to reduce the volume and duration of the siren.

Moreover, exposing the siren-test as a HA service (through siren.turn_on or a custom one to support audio true/false) would be a powerful way to instrument the siren for precise events. 
I would be able to sound the siren 1 second only or make "beep-beep" with a loop by calling the service.
```
service: siren.turn_on
data:
  duration: '1000'
target:
  entity_id: siren.ring_outdoor_siren
```

I don't think it would make sense to support everything that is possible using the app, but support for siren.start, siren-test.start, siren-test.stop through services with data payload, plus config/controls sensors for audio settings like volume and duration would be really useful (to me at least).

**Comment by tsightler** [comment]
For siren switches the code typically just triggers the "test" function because the doesn't create in notifications, so most likely just siren-test.start and siren-test.stop that I need but I'd have to modify the code to behave differently based on whether it is a Ring vs Dome siren.

I don't really understand your requests about HA services.  This project is about integrating Ring via MQTT and it interfaces with HA via MQTT as well.  I'm not aware of any method to create services via MQTT entities.  You can easily create automations that do what you want without any services.

**Comment by Mincka** [comment]
Sorry, that's a misunderstanding on my part. I didn't understand that you don't call the API yourself but you use `ring-client-api` for that.
It means that the features I am talking about should be made available upstream first.
And, indeed, there is already an issue related to the support of the Outdoor Siren [here](https://github.com/dgreif/ring/issues/615).

**Comment by tsightler** [comment]
I can definitely add Outdoor Siren support to ring-mqtt without any special support in ring-client-api, the request there is more about ring-homebridge (the ring-client-api is a child project of the ring-homebridge addon project).  And none of that has anything to do with Home Assistant services.  This project has no direct interaction with Home Assistant, only with MQTT, so I don't believe I can register any services in Home Assistant other than the ones already provided by the various MQTT entities.

**Comment by Mincka** [comment]
Forget my idea about HA services. I will try to put it differently: would it be possible to publish a message using MQTT to set off the siren **while specifying its duration**? Currently, the switch implementation in HA is bound to the publication of a message without data or with predefined (hardcoded) data. It's ok, you couldn't do it otherwise, that's just a switch.

My idea for this case would be to publish messages with data/attributes directly, maybe by using `mqtt.publish`.

In this API command, you can see I can specify the duration (and LED/audio) when I start the siren test:
```
"commandType": "siren-test.start",
"data": {
"duration": 5000,
"audio": false
}
```

Does it require updates in this project and/or dependencies?

**Comment by tsightler** [comment]
I won't be adding anything like this, simple on-off is good enough and you can implement duration in whatever automation tool is calling the switch.

**Comment by tsightler** [comment]
I've included an attempt to fix this for 4.9.1.  As I don't have one of these devices I'm not really sure of the behavior if you issue siren-test.start without any duration (some devices only go for 30 seconds by default), but I'm going to consider this good enough.

**Comment by Mincka** [comment]
Thank you. I will let you know if it fixes the issue when the next release of the addon is published.

**Comment by tsightler** [comment]
Sorry, accidentally clicked close on this, instead of comment.  Any chance you could test the dev branch?  If you're using the addon it's just a matter of changing the branch config option from "addon" to "dev" and restarting.  The code now simply detects if the device is a outdoor siren and uses the "siren.start-test" and "siren.stop-test" commands instead of the standard on/off messages used for Z-wave sirens.  I don't know if these require any parameters to work.

**Comment by Mincka** [comment]
Confirmed as fixed. When the switch is triggered in the interface, the outdoor siren goes off in **Test mode** and it is reflected directly in the mobile / web application. Thank you again.

**Comment by tsightler** [comment]
Thanks for testing!
