### ISSUE TITLE
Video Doorbell 2 battery draining when integration is enabled #100

### ISSUE THREAD

**Issue by dhi20** [tsightler/ring-mqtt#314]
Hi,
I've used this integration for a while and found it very reliable. Starting in late Dec / early Jan the battery on my hardwired doorbell started to lose charge.

It appears when the camera part of the integration is enabled (enable_cameras: true) the integration is answering all motion events. This can be seen in the ring app (screenshot attached).

Setting enable_cameras: false resolves the issue and the battery starts to increase again,

Is anyone else having the same issue?

Note the attached screenshot shows what happens when enable_cameras: is changed from false to true (between 9.50am and 10.01am).

Thanks
Daniel

## System Health

version | core-2022.2.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.91
arch | aarch64
timezone | Pacific/Auckland

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.20.0
Stage | running
Available Repositories | 948
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2022, 1:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.01.0
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 29.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), ESPHome (2022.1.2), File editor (5.3.3), Grafana (7.4.1), InfluxDB (4.3.0), Mosquitto broker (6.0.1), TasmoAdmin (0.16.0), Terminal & SSH (9.3.0), phpMyAdmin (0.7.0), Ring-MQTT with Video Streaming (4.9.0), Home Assistant Google Drive Backup (0.105.2), MariaDB (2.4.0), ioBroker (0.8.0), Eufy Security Add-on (0.7.0), RTSP Simple Server Add-on (v0.17.6), Node-RED (10.3.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 10
views | 12
mode | storage

</details>

![Screenshot_20220128-144908_Ring](https://user-images.githubusercontent.com/38461182/151474230-16104aff-73ff-4ea8-be4b-997d34e9dac6.jpg)

**Comment by tsightler** [comment]
Expected behavior.  I answered you on the issue in the addon project.

**Comment by heisenberg2980** [comment]
> Expected behavior. I answered you on the issue in the addon project.

@tsightler having the same issue with my Ring Doorbell 4 where the battery is slowly draining as soon as I start this addon until I have to manually charge it. I have looked at the addon project but the issues are disable on that project, can you please share the link to the issue in the addon project so I can have a look at the answer? Is it expected that the battery of the Ring Doorbell drops while using this addon so it needs to be manually charged even when the doorbell is hardwired?

**Comment by heisenberg2980** [comment]
@dhi20 do you have the link to the issue @tsightler mentioned in his last comment by any chance?
