### ISSUE TITLE
Cannot add new Ring Glass Break Sensors.

### ISSUE THREAD

**Issue by onlize** [tsightler/ring-mqtt#327]
Hello.

Ring has new "Glass Break Sensors." I am trying to add them and the system does not see it. I removed and re-created MQTT integration in HomeAssistant, but it did not help.

What am I doing wrong? Can you help?
Thank you.

**Comment by tsightler** [comment]
As ring-mqtt doesn't magically support all devices Ring releases without somebody doing the actual work to add them, what you are doing wrong is having the wrong expectation of a free project maintained by someone in their spare time.

Regardless, support for glassbreak sensors is currently available in the dev branch and is already discussed [here](https://github.com/tsightler/ring-mqtt/discussions/322) https://github.com/tsightler/ring-mqtt/discussions/322).

**Comment by onlize** [comment]
Thank you for the reply and sorry if I asked a question that I shouldn't have. I assumed that this is as any other sensor should just work. Now I see that this will be a different class of sensors. 

I appreciate all work you do for the community.

**Comment by tsightler** [comment]
Sorry, probably an interpretation issue on my part, the message just came across a little entitled, but now that I'm looking at it again, I probably overreacted.  Sometimes it's frustrating to work on a project that you basically just built for yourself, then decided to share in case other people wanted to play with it, and then have people constantly have expectations on what you should do with it, how quickly things should be supported.  I apologize for reacting poorly, it wasn't a fair reaction and I need to do better about it.

**Comment by onlize** [comment]
Don't worry about this.
