### ISSUE TITLE
How do I get to use the sensors within home assistant. 

### ISSUE THREAD

**Issue by Garrycollins1978** [tsightler/ring-mqtt#329]
I have the Ring-MQTT integration working and the live camers feed works fine, but how can u get to use the alarm sensors eithe ron a card or for automation?

**Comment by tsightler** [comment]
Sorry, but I don't have the time available to provide generic support for Home Assistant, I'd suggest the Home Assistant documentation and forums for that.  Assuming you have properly setup and configured the MQTT integration in Home Assistant, the MQTT devices/entities will show up as any other device/entity in HA (Configuration...Devices and Services and then on the Devices and Entities tab).
