### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by Originalme** [tsightler/ring-mqtt#339]
When installing via the addon store method on the latest hassio operating system, the installation fails with the error below.

`WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of ring alarm hassio integration`

**Comment by tsightler** [comment]
I have no idea what you are installing, that is not the name of the official addon that I maintain and the official addon has not used "startup: before" in many years.  Please verify that you are installing from official source:

https://github.com/tsightler/ring-mqtt-ha-addon

**Comment by Originalme** [comment]
You are correct, I should have checked my old repo. It looks like someone cloned this and referenced yours in their documents. I apologize, I should have double-checked before submitting.
