### ISSUE TITLE
Event preroll

### ISSUE THREAD

**Issue by DerekL0576** [tsightler/ring-mqtt#347]
I've added this under assistance because it's not really a bug and I'm not sure if it's something that can even be added as a new feature.

My Ring doorbell records 8 seconds before a motion event and this is inserted at the start of the event videos on the ring account.  The problem is, I think they do this on the fly when viewing or downloading the video on the Ring site or app.

When I try to record the live feed in HA on a motion event, the start of the video is missing a reference key frame so it's garbled for around the first 2 seconds.  Obviously the video only starts from the motion event and is missing the 8 seconds preroll video.

When viewing the latest event feed in HA, the video is exactly the same as my local recording.  Garbled at the start and missing the 8 seconds preroll.

Could this preroll video ever be accessed by ring-mqtt and inserted at the start of the event stream like Ring does?

**Comment by DerekL0576** [comment]
I just wanted to add that manually recorded live stream video is perfect, it's only garbled at the start if I start recording on a motion event.

**Comment by tsightler** [comment]
I'm going to convert this to a discussion as this is not really an issue.
