### ISSUE TITLE
Two-Factor Auth Support?

### ISSUE THREAD

**Issue by statuskwolek** [tsightler/ring-mqtt#35]
Based on https://github.com/dgreif/ring/wiki/Two-Factor-Auth - it looks like the unofficial API for Ring (https://github.com/dgreif/ring) added support for 2FA.  Any chance this could be included somehow (did a quick scan of the code and didn't notice anything that indicated it was already supported)

It's also possible I've been awake for a while and missed it entirely.

**Comment by statuskwolek** [comment]
See, look at that - there's already a PR for it (https://github.com/tsightler/ring-alarm-mqtt/pull/34)

**Comment by tsightler** [comment]
Finally found time to work on this and merge this into the main branch along with another batch of updates/features.
