### ISSUE TITLE
Front_Door_Snapshot recording ignores Snapshot Interval.

### ISSUE THREAD

**Issue by petermh87** [tsightler/ring-mqtt#350]
## Important note regarding camera support    
The ring-mqtt project does not magically turn Ring cameras into 24x7 CCTV cameras suitable for continuous streaming.  Ring cameras are designed to work with Ring cloud servers for on-demand streaming based on detected events (motion/ding) or interactive viewing.  Even when using ring-mqtt, all streaming still goes through Ring cloud servers and is not local.  Using this project for continuous streaming is not a supported use case and attempts to do so will almost certainly end in disappointment.  Any support cases opened for issues with continuous streaming (i.e. more than one streaming session back-to-back) will be closed as unsupported.  This includes use with NVR tools like Frigate or motionEye.

## Please read before opening a bug report
This is a community project and opening an issue indicates that you are prepared to interact as a community member.  Note that this does not mean that I expect you to be a developer or a super tech guru, but you must at least be willing to put some time and effort into helping me understand your environment, answer questions, provide logs, and do so in a reasonably timely manner.  In general I will do my best to help whenever I can, but I answer these issues on my own personal time and my effort to do so will largely be commensurate to the effort that you put in.  I'm sorry for being so blunt, but recently, the number of people that opened issues with a single sentence, or that open an issue and then never respond to any requests for additional information, has grown to the point that it really makes working on this project less than enjoyable, and that puts the entire project at risk.

I don't want to discourage users from opening an issue if there is a problem, I promise that, if the appropriate effort is made, I will do my best to meet that effort, assuming available time.  Please remember that I am not associated with Ring in any way, other than the fact that I own some of their products, I can't help you solve problems with your Ring devices and I can't do anything about their limitations, I suffer with those limitations just like you do.  The goal of this project is simply to make it as easy as possible to integrate the features of Ring products the home automation platform of your choice.

### Describe the bug
A clear and concise description of the issue.  Please enter a brief summary of the issue in the title above as well.
I am attampting to save the snapshot image whenever it is updated in accordance with the Interval timing (defaults to 180secs)

I have created an automation below....which looks for an update on front_door_snapshot.attributes.picture entity and calls the downloader service to save to a local file.

```
alias: Ring - Save Snapshot
description: ''
trigger:
  - platform: state
    entity_id: camera.front_door_snapshot
    attribute: entity_picture
condition: []
action:
  - service: downloader.download_file
    data:
      url: >-
        https://duckdns.org domain{{
        states.camera.front_door_snapshot.attributes.entity_picture }}
      subdir: Ring/Snapshot
      filename: '{{ now().strftime("%Y-%m-%d-at-%H-%M-%S") }}.jpg'
      overwrite: false
mode: single
```

I am using the duckdns address in my url as I have a loopback function in a pi-hole instance I have set up (tested and working as file created in local storage and accessible from browser address bar)

The issue I am having is that the picture.entity function only seem to change state every 5 minutes (coincides with the refresh of the eventId on the event_select??) and ignores the interval entered into the snapshot_interval entity (tested at 30 secs, 1 min, 3 mins)

I have monitored the camera.front_door_snapshot on my dashboard and this does update with the interval timings; however this doesn't cause the front_door_snapshot.atributes.entity_picture to update.

### Describe your environment
Please include details on your enviornment, including OS versions, platform, etc.
HASSOS running on a proxmox instance. 
4CPUs and 8GB of ram allocated (with plenty of overhead)

### Describe your settings and what you've tried
Please make sure to share you configuration settings (other than sensitive information like token, etc) and anything you have done to attempt to solve the problem to this point.

```
enable_cameras: true
snapshot_mode: all
livestream_user: username
livestream_pass: Password
enable_modes: false
enable_panic: false
beam_duration: 0
disarm_code: ''
mqtt_host: MQTT IP
mqtt_port: 'MQTT Port'
mqtt_user: MQTT_username
mqtt_password: MQTT_pasword
branch: addon
debug: ring-*
ring_token: ''
location_ids:
  - ''
```

### Debug Logs
In many cases the only way to effectively troubleshoot an issue is to review the logs, without this, I'll mostly just be guessing at the problem.  Please run the script with DEBUG=ring-* enabled (note this is enabled by default for the addon and Docker versions) and collect logs.  Logs will likely contain potentially sensitive information so you probably do not want to post them publicly on Github, which I certainly understand.  Please feel free to send the logs, or a link to download them, to my personal email address, which is the same username at gmail and be sure to reference the open issue by number or link.

**Comment by tsightler** [comment]
The entity_picutre attribute is simply the attribute to access the Home Assistant camera proxy, the only part of it that changes is the access token, which is rotated I believe every 5 minutes, which is probably what you are seeing.  You should probably trigger on the timestamp attribute which is updated each time a new image is sent via MQTT.  You should also be able to use the [snapshot service](https://www.home-assistant.io/integrations/camera/#service-snapshot) rather than downloader, I think that would be far easier.  It should be available for all camera entities, including the MQTT camera, so it should work with snapshots just fine, although I haven't personally tested it in a LONG time.

As these are HA questions, and thus better asked on HA forums than here, I'm closing this issue.
