### ISSUE TITLE
Motion Binary Sensor Not Updating Unless Person Detected

### ISSUE THREAD

**Issue by broyuken** [tsightler/ring-mqtt#374]
### Describe the bug
A clear and concise description of the issue.  Please enter a brief summary of the issue in the title above as well.

I have my ring camera set up in the ring app to have motion events record, and person events record and notify. I've noticed that the binary motion sensor in HA doesn't update unless there is a person there. Just generic motion does not seem to trigger it. I'm not sure if this is a bug in ring-mqtt or if ring just doesn't send the event unless I have other motion events turned on in the ring app. 

If this is an unexpected result, I will gladly provide logs to troubleshoot this, however I suspect this is a limitation on the ring side and would just like confirmation.

**Comment by tsightler** [comment]
This is a change in behavior from prior versions due to the move to push notifications.  It's covered both in the Upgrading to 5.x document referenced in the release notes and in the wiki based documentation.  Open to suggestions on how it could be made more clear.

**Comment by broyuken** [comment]
I was going to say this still happens when regular motion events are turned on, but someone turned off the switch that the camera runs off…

The documentation is clear, but I forgot about that  since I wasn’t using this functionality prior to version 5.
