### ISSUE TITLE
WARNING - Unhandled Promise Rejection ReferenceError: err is not defined

### ISSUE THREAD

**Issue by pixeldrew** [tsightler/ring-mqtt#376]
https://github.com/tsightler/ring-mqtt/blob/1b7cfe113ce791ff96876036846f855dae604a2b/lib/state.js#L40-L45

err is referenced but not definition in the catch

**Comment by tsightler** [comment]
Thanks!  I'll address this in dev prior to the next release.

**Comment by tsightler** [comment]
Fix has been included in dev branch.
