### ISSUE TITLE
Live stream is broken again after core update 2022.6.1

### ISSUE THREAD

**Issue by bkr1969** [tsightler/ring-mqtt#385]
## Important note regarding camera support    
The ring-mqtt project does not magically turn Ring cameras into 24x7 CCTV cameras suitable for continuous streaming.  Ring cameras are designed to work with Ring cloud servers for on-demand streaming based on detected events (motion/ding) or interactive viewing.  Even when using ring-mqtt, all streaming still goes through Ring cloud servers and is not local.  Using this project for continuous streaming is not a supported use case and attempts to do so will almost certainly end in disappointment.  Any support cases opened for issues with continuous streaming (i.e. more than one streaming session back-to-back) will be closed as unsupported.  This includes use with NVR tools like Frigate or motionEye.

## Please read before opening a bug report
This is a community project and opening an issue indicates that you are prepared to interact as a community member.  Note that this does not mean that I expect you to be a developer or a super tech guru, but you must at least be willing to put some time and effort into helping me understand your environment, answer questions, provide logs, and do so in a reasonably timely manner.  In general I will do my best to help whenever I can, but I answer these issues on my own personal time and my effort to do so will largely be commensurate to the effort that you put in.  I'm sorry for being so blunt, but recently, the number of people that opened issues with a single sentence, or that open an issue and then never respond to any requests for additional information, has grown to the point that it really makes working on this project less than enjoyable, and that puts the entire project at risk.

I don't want to discourage users from opening an issue if there is a problem, I promise that, if the appropriate effort is made, I will do my best to meet that effort, assuming available time.  Please remember that I am not associated with Ring in any way, other than the fact that I own some of their products, I can't help you solve problems with your Ring devices and I can't do anything about their limitations, I suffer with those limitations just like you do.  The goal of this project is simply to make it as easy as possible to integrate the features of Ring products the home automation platform of your choice.

### Describe the bug
The stream will not start.  Previous breakage caused the entire camera to become unavailable until reload, now it becomes unavailable for a few seconds, then resets itself.  Still no stream.

### Describe your environment
HA core 2022.6.1

### Describe your settings and what you've tried
Please make sure to share you configuration settings (other than sensitive information like token, etc) and anything you have done to attempt to solve the problem to this point.

### Debug Logs
2022-06-03T13:58:04.889Z ring-attr [Front Door] ring/2148f1ae-7761-49f2-44eb-f1afb06c1b58/camera/e04f43a47a81/snapshot/attributes {"timestamp":1654264685}
2022-06-03T13:58:17.120Z ring-rtsp INF [RTSP] [conn 172.30.32.1:48134] opened
2022-06-03T13:58:17.126Z ring-rtsp INF [path e04f43a47a81_live] runOnDemand command started
2022-06-03T13:58:17.130Z ring-rtsp [Front Door] Sending command to activate live stream ON-DEMAND
2022-06-03T13:58:17.141Z ring-mqtt [Front Door] Received set live stream state ON-DEMAND
2022-06-03T13:58:27.126Z ring-rtsp INF [path e04f43a47a81_live] runOnDemand command stopped
2022-06-03T13:58:27.127Z ring-rtsp INF [RTSP] [conn 172.30.32.1:48134] closed (source of path 'e04f43a47a81_live' has timed out)
2022-06-03T13:58:27.128Z ring-rtsp [Front Door] Deactivating live stream due to signal from RTSP server (no more active clients or publisher ended stream)
2022-06-03T13:58:27.134Z ring-mqtt [Front Door] Received set live stream state OFF
2022-06-03T13:58:27.134Z ring-mqtt [Front Door] Stopping live stream session on workerId 1)

**Comment by bkr1969** [comment]
Well, seems to be working now.

**Comment by amaisano** [comment]
I actually have this same problem. Ironically, it is also my Front Door camera. Same exact logs. The stream won't start and the camera configuration won't save in Generic Camera integration for this one camera.

**Comment by freekeys** [comment]
I’m getting this too. Can we reopen? Or should I start a new issue?

**Comment by bkr1969** [comment]
> I’m getting this too. Can we reopen? Or should I start a new issue?

It seems like with every core update this integration will be glitchy. I’ve found that stopping and restarting the add-on usually fixes it. Also try going in to configuration in the generic camera and submit without making any changes.

**Comment by tsightler** [comment]
I've had absolutely zero issues with any recent HA upgrades, and, based on the fact that there are basically zero reports of any issues in the last 6 months, even though this addon has ~5000 users now, it's pretty unlikely that the issues are widespread because, trust me, people love to open issues for almost any minor problem.

**Comment by freekeys** [comment]
This wasn’t a real issue for me - the add-on just needed restarting. Thanks!
