### ISSUE TITLE
Lock not showing proper state in 0.104

### ISSUE THREAD

**Issue by alexmorford** [tsightler/ring-mqtt#40]
I'm running 0.104.0b5 and it looks like some changes have been made to MQTT regarding lock states. My two Schlage locks through Ring are now always showing unlocked even though they are locked. I usually wouldn't bring something like this up, but it looks like they are making a permanent change in MQTT integration.

**Comment by tsightler** [comment]
Gotta love Home Assistant, making breaking changes for no particularly valid reason at all.  While it looks pretty easy to fix, I'm not sure how to implement this without breaking compatibility with older HA versions.  Sometimes I think I should just rip out the HA auto-discovery code completely and force people to manually configure the MQTT devices and keep up with all the changes.

**Comment by broyuken** [comment]
A version check to see which version of HA the user is running?

**Comment by tsightler** [comment]
This code commonly runs in a container and can even run on another host entirely.  It has no knowledge of HA and the only way it could learn the version is via MQTT.  I'm not aware of any way to get the HA version via MQTT.

So I'll probably have to resort to something uglier, like a config option, unless i can figure out a way to make it work with 104 without breaking prior version (I have one idea here).

The next problem is finding the time to even work on it and it doesn't help that i don't have a lock so can't test it.

**Comment by broyuken** [comment]
I’ll help in any way I can, I have a schlage lock connected to ring alarm.

**Comment by plw4** [comment]
I don't know how to use github very well, so I cloned your repository and changed the deviceState to LOCKED and UNLOCKED, then cloned the hassio addon repository, changed it to pull from my own repository, and changed to using that addon in hassio.  That got the locks showing the states that HA understands.

**Comment by tsightler** [comment]
Yeah, it's trivial to make it work with 104, but i don't see an obvious way to make it work with 104 without breaking previous versions and not everyone enjoys having new brokenness every few weeks by following the lastest HA version.

**Comment by broyuken** [comment]
Could you just say if you use an old version of HA, use the old version of your code? If using an old version just don’t upgrade.

**Comment by plw4** [comment]
I'm learning as I go here... Did older HA check the state topic? If not, would changing the state sent here do anything to it?  From my very limited understanding, it looks like it just used the payload / command value before. I guess if people use this outside of HA then they'd notice the difference.

**Comment by tsightler** [comment]
Yes, older HA checked the state topic, the only difference is, the payload for state vs command topic had to be the same, so the command to lock to door defaulted to "LOCK", which was also the state returned when the door was locked.

I understand why this wasn't ideal, the state itself is "LOCKED", not "LOCK", but it matched the behavior of other devices like switches, where the command and state were the same "ON" or "OFF".

Now, with 104, the default payload for the command topic is still "LOCK" and "UNLOCK", but the default payload for the state topic "LOCKED" and "UNLOCKED".

The "simple" solution is to just set the state payload back to "LOCK" and "UNLOCK" to make 104 revert to the same behavior as the prior versions (this is what is mentioned in the release notes).  This works, but my code is also doing MQTT discovery to make the devices appear automatically in HA.  If I attempt to create discovered items using parameters that don't exist in the old version, the older versions completely reject the device.

I think what I can do, although it's ugly, is send the config as is, and then, if it's a lock, attempt to "resend" the config with the extra parameters.  If it prior to 104 you'll the second attempt will just error, but if it's 104 it will revert to previous behavior.

That being said, maybe the suggestion to just update the code and tell people that are using older versions to either upgrade HA or use a previous version of this code is really good enough.  My experience says that will just create more issues being open as 95% of people don't upgrade, but perhaps that's getting better.

I have a whole backlog of stuff to do to this code, so I need to find a few hours to work on it.  I'll try to do that this weekend.

**Comment by plw4** [comment]
Gotcha.  Regarding the older versions, keep in mind that the Ring integration was broken in HA and it got fixed in 104.  I feel like a lot of us that use this also use the Ring integration, so we're more motivated to upgrade than any other particular release.

**Comment by tsightler** [comment]
That's fair, as long as everyone else keeps in mind that this is just a side project that I threw together for my own use that I thought others might find useful and I never really expected it to grow to having 100's of users opening issues and expecting fixes right away!  :)

Not that I think you are doing that at all, but I think I've become a little too jaded over the last year because of the attitude of a few people that acted like I owed it to them to help them solve their problem with my code I shared freely.  I'll do my best to work on the backlog over the next few days and get a new version published.

**Comment by broyuken** [comment]
@tsightler I look forward to your changes to get this working again and to see what additional functionality you build in as you have time. This is 100% just a hobby for most of the developers on here and most of us sincerely appreciate what you do. Take your time, and it'll be ready when you have time to make it ready. In the meantime @plw4 I have added your repository to HA and am using that as a band-aid until this repo is updated. Thank you for having a fix so quickly on something so important (locks for my house)

**Comment by alexmorford** [comment]
I pulled from @plw4 's repository as well and that worked well for me. @tsightler Thanks for all you've done on this project!

**Comment by plw4** [comment]
Ok, just be warned that I may start breaking it by trying to pull in the 2FA changes in the next few days.  I just did this because I don't know how else to make changes to things installed in hassio.  I haven't the slightest clue what I'm doing so don't go deleting the Ring app ;)

**Comment by tsightler** [comment]
Thanks all, obviously there was nothing but good in this particular thread, I just had some really bad experiences with a few people last year around this project and it honestly sucked away the joy of working on it so it became a completely back-burner project for me.  I need to remember that 99% of the people using it are not the problem and set some time aside to get this project back on track.

I will look to merge all of this over the weekend and hopefully get a fully working version for 104 that also includes 2FA and a few other things.

**Comment by alvinpetitt** [comment]
@tsightler while you may not hear from those of us that are appreciative of your "hobby work", please know that most of us are sincerely thankful.

**Comment by chastbi** [comment]
This addon is one of my favorite things in HA and your support of it is very appreciated. Ring motion sensors as room presence detection is key in my lighting automations. Plw4's fix for locks is working for me as well for the time being. Thanks so much to you both.

**Comment by InstigatorX** [comment]
Any suggestions on what we can change independently to workaround while you work it? I have a ton of automations that leverage unlock/lock and wife is crawling up my butt. :) This is great work, btw. Don't let the 0.01% ruin the fun of this for you.

**Comment by sktaylortrash** [comment]
In the section
    if (/^lock($|\.)/.test(data.deviceType)) {
       switch(data.locked) {
            case 'locked':
                deviceState = 'LOCK'
                break;
            case 'unlocked':
                deviceState = 'UNLOCK'
                break;
            default:
                deviceState = 'UNKNOWN'
        }
    }

Change - deviceState = 'LOCK' to deviceState = 'LOCKED'
and deviceState = 'UNLOCK' to deviceState = 'UNLOCKED'

**Comment by tsightler** [comment]
I have pushed v2.0 which includes the required changes for this as well as a few other features such as 2FA and support for additional 3rd party Z-wave devices.  As I don't have a lock could someone please test this feature and let me know that it is working correctly?

**Comment by chastbi** [comment]
My Z-Wave Schlage Lock is working perfectly. Thank you!

**Comment by alexmorford** [comment]
My Z-Wave Kwickset 988 is working as well. Thanks!

**Comment by alvinpetitt** [comment]
Running Hassio, how can I install the update?

**Comment by alexmorford** [comment]
If you are using https://github.com/rs1932/ring-alarm-hassio-addon, I think all you would need to do is stop the add-on, rebuild, and then re-start the add-on.

**Comment by alvinpetitt** [comment]
I actually did an uninstall/reinstall but that didn't help. Still the same version (0.52).

**Comment by alexmorford** [comment]
The version of the add-on will not change. @tsightler doesn't actually maintain the add-on. The creator simply made an add-on that pulls off tsightler's GitHub

**Comment by alvinpetitt** [comment]
I'm still getting an error:

`Ring Alarm Integration
Node Version
v12.14.0
NPM Version
6.13.4
git version 2.24.1
added 241 packages from 141 contributors and audited 669 packages in 36.416s
5 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
up to date in 9.151s
5 packages are looking for funding
  run `npm fund` for details
fixed 0 of 0 vulnerabilities in 669 scanned packages
2020-01-20T02:20:35.945Z ring-alarm-mqtt Exit code: 1

**Comment by tsightler** [comment]
What do you mean by "still" getting an error?  There are no fixes in this update for any errors, only some minor updates to make the lock status work with HA 0.104 and a few additional enhancements.  If you were getting errors before, this update is unlikely to fix anything.

**Comment by alvinpetitt** [comment]
Sorry. I'm only getting the error now that I reinstalled. It was working before, then had the issue that Ring changed things. Now that I've reinstalled, obviously I've boogered something up.

**Comment by tsightler** [comment]
I see.  As I don't currently support the hassio plugin myself, it's possible it could be something wrong with the interaction with the new parameters and/or the the docker support as I haven't tested those and those features were submitted by other users.  Can anyone else verify if the plugin still works for them with hassio?

**Comment by plw4** [comment]
Yea I went back to your plugin with Hassio and it’s fine.

**Comment by alvinpetitt** [comment]
So, I'm confused as to what I need to do. All works fine when I have 2FA off, only accessing my account with username and password. If I turn 2FA back on, I get the error specified above:

2020-01-20T02:20:35.945Z ring-alarm-mqtt Exit code: 1

Again, I'm running Hassio. What do I need to do to get this to work with 2FA turned on? Thanks in advance.

**Comment by tsightler** [comment]
I'm quite confident the hassio plugin has not been updated to include support for the parameters required to use 2FA.  As noted in the documentation (you read it, right?), you have to run a command from the CLI to get a token and then enter that token as the "ring_token" parameter which the plugin probably does not currently have since I literally just released this update today and I don't maintain the plugin, the plugin simply uses my code.

I'd suggest opening an issue/enhancement request on the plugin maintainers git repo, although I'm not sure how easy it will be to support 2FA with the plugin since you have to manually run a command to initially get the token.

**Comment by broyuken** [comment]
I modified the hassio plugin to accept the additional ring_token parameter, and it's in the config.json file (verified by going into the container and checking it out) and ring_user and ring_pass are both blank. When I restart HA however, ring is unavailable. Any ideas on where I could begin to troubleshoot? I saw your thing about debugging, but I'm not sure how to enable that inside of HA.

**Comment by tsightler** [comment]
Since this issue is resolved I'm going to close this.

@broyuken as your issues are related to the hassio plugin, which isn't supported in this tree, I'd suggest opening an issue there and seeing if you can get help.  In general, you should be able to attach to the container and run the script with debug from in there, but, since I don't use hassio or Docker myself, I'm probably going to be of very little help.

**Comment by broyuken** [comment]
I added the location to the hassio plugin and it works great. I’m all good here, thanks!
