### ISSUE TITLE
What do these controls do?

### ISSUE THREAD

**Issue by radiocolin** [tsightler/ring-mqtt#400]
#### Describe the problem
What do these switches do?

##### Describe your environment
Ring-mqtt docker image on Rpi4, wired doorbell camera

I don't understand the "controls" for the doorbell camera and I can't find anything clear about it in the documentation. What do these controls do?

<img width="336" alt="Screen Shot 2022-07-18 at 11 30 54 AM" src="https://user-images.githubusercontent.com/992033/179547262-7b1b17ae-02be-4293-bb24-67cfb2aed47d.png">

**Comment by tsightler** [comment]
Please do not open issues just to ask questions about how something works, use discussions Q&A thread instead.  For the most part I think these settings controls are fairly self-explanatory just from the labels, however, the features are described in the Configuration Details and Video Streaming sections of the wiki.
