### ISSUE TITLE
Question about still image URL

### ISSUE THREAD

**Issue by Stefan300381** [tsightler/ring-mqtt#426]
Hi all,

I just found this awesome project, thanks a lot for this!

One thing I don't understand at all, even after reading the wiki, is how the still image URL works.
RTSP works fine, but I'd like to get a still image when someone rings my doorbell.
Of course I could use ffmpeg to create a still image from the rtsp stream, but it seems you implemented this already.
I should add that I'm not a HA user, instead I rely on openHAB.

Here is my example URL: https://localhost:8123{{ states.camera.haustür_snapshot.attributes.entity_picture }}"}
https really correct?
What's this attribute string?

thanks in advance

Stefan

**Comment by tsightler** [comment]
The still_image_url attribute can only be used by Home Assistant users.  It's basically a way for Home Assistant to retrieve the latest snapshot from the snapshot camera from the Home Assistant built in camera proxy URL.  If you are using this with some other tool, like OpenHAB, then you'd need to figure out a way to get a still image from the snapshot camera to display.  Unfortuantely, I don't have the ability to help you with that, but the snapshots are available via MQTT via the snapshot topic, so it should be possible in theory, based on the given capabilities of the system.
