### ISSUE TITLE
Ring MQTT HA Add On

### ISSUE THREAD

**Issue by gdg316** [tsightler/ring-mqtt#429]
I added this to my Home Assistant - Have All configured except having issue with Saving Video When Door Bell is Pressed and I have tried several times
any help or guidance would be helpful

**Comment by tsightler** [comment]
You already asked this in a discussion thread and, more importantly, you completely ignored everything that was asked when opening an issue, not even a cursory attempt to describe what things you've already tried.  Based on that, I'm closing this issue, but I will respond to you in the discussion thread.

**Comment by gdg316** [comment]
I Have a New issue integration not working

![image](https://user-images.githubusercontent.com/67116557/185796786-cb8b5cf7-879a-475d-bff3-f13bd6da9959.png)
