### ISSUE TITLE
Intergation Not working states Unavailable

### ISSUE THREAD

**Issue by gdg316** [tsightler/ring-mqtt#433]
## Important note regarding camera support    
The ring-mqtt project does not magically turn Ring cameras into 24x7 CCTV cameras suitable for continuous streaming.  Ring cameras are designed to work with Ring cloud servers for on-demand streaming based on detected events (motion/ding) or interactive viewing.  Even when using ring-mqtt, all streaming still goes through Ring cloud servers and is not local.  Using this project for continuous streaming is not a supported use case and attempts to do so will almost certainly end in disappointment.  Any support cases opened for issues with continuous streaming (i.e. more than one streaming session back-to-back) will be closed as unsupported.  This includes use with NVR tools like Frigate or motionEye.

## Please read before opening a bug report
This is a community project and opening an issue indicates that you are prepared to interact as a community member.  Note that this does not mean that I expect you to be a developer or a super tech guru, but you must at least be willing to put some time and effort into helping me understand your environment, answer questions, provide logs, and do so in a reasonably timely manner.  In general I will do my best to help whenever I can, but I answer these issues on my own personal time and my effort to do so will largely be commensurate to the effort that you put in.  I'm sorry for being so blunt, but recently, the number of people that opened issues with a single sentence, or that open an issue and then never respond to any requests for additional information, has grown to the point that it really makes working on this project less than enjoyable, and that puts the entire project at risk.

I don't want to discourage users from opening an issue if there is a problem, I promise that, if the appropriate effort is made, I will do my best to meet that effort, assuming available time.  Please remember that I am not associated with Ring in any way, other than the fact that I own some of their products, I can't help you solve problems with your Ring devices and I can't do anything about their limitations, I suffer with those limitations just like you do.  The goal of this project is simply to make it as easy as possible to integrate the features of Ring products the home automation platform of your choice.

### Describe the bug
A clear and concise description of the issue.  Please enter a brief summary of the issue in the title above as well.

### Describe your environment
Please include details on your enviornment, including OS versions, platform, etc.

### Describe your settings and what you've tried
Please make sure to share you configuration settings (other than sensitive information like token, etc) and anything you have done to attempt to solve the problem to this point.

### Debug Logs
In many cases the only way to effectively troubleshoot an issue is to review the logs, without this, I'll mostly just be guessing at the problem.  Please run the script with DEBUG=ring-* enabled (note this is enabled by default for the addon and Docker versions) and collect logs.  Logs will likely contain potentially sensitive information so you probably do not want to post them publicly on Github, which I certainly understand.  Please feel free to send the logs, or a link to download them, to my personal email address, which is the same username at gmail and be sure to reference the open issue by number or link.

![image](https://user-images.githubusercontent.com/67116557/185796949-573cbcb0-c829-41ef-bf4f-f3bb3c70efd6.png)

**Comment by tsightler** [comment]
Sorry, but I'm closing this since you failed provide even a tiny amount of useful information or any of the information that is requested when opening an issue.

**Comment by gdg316** [comment]
sorry but everything stopped working and states unavailable I will see if I can find the debug option

**Comment by tsightler** [comment]
Posting a screenshot showing sensors unavailable is roughly as useful as posting a picture of a car that won't start and asking what is wrong with it.  Realistically, what do you actually think anyone could do to help you with that limited information?  Then, when I try to ask for more details, all you ever provide is generic responses, to take the car analogy further, so far our interactions have been roughly like this:

Q: What happened when you tried to start the car?
A: It didn't start

Q: What exactly where you trying to do with the car?
A: Start the car

Useful information would be contextual details like if the car made any sound when you tried to start it, have you checked the battery, how long since you last used the car, etc.

Opening an issue here assumes that you have done some basic troubleshooting, checked logs in both ring-mqtt and Home Assistant, and can at least provide those logs and details of what you've tried so far, which is why all of this information is requested when opening an issue.

**Comment by gdg316** [comment]
I fixed it issue was with Mosquito Broker - Not Communicating correctly also got Video(MP4 and snapshot jps downloading to Media Folder after automation is triggered

**Comment by tsightler** [comment]
I'm glad you were able to get it to work.
