### ISSUE TITLE
Video Devices unavailable, error when refreshing token

### ISSUE THREAD

**Issue by alex-iain-barnett** [tsightler/ring-mqtt#436]
Since updating, all Ring video devices are unavailable (Doorbell & 2 Ring cameras). Other devices (ring alarm etc) are working as expected. 

I have tried regenerating the token, restarting the addon & completely reinstalling. Unfortunately I did not backup before updating. 

When restarting, errors are thrown when refreshing the token. Log attached. 

Environment details:
Raspberry Pi 4b
Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest

[errorlog.txt](https://github.com/tsightler/ring-mqtt/files/9416966/errorlog.txt)

**Comment by alex-iain-barnett** [comment]
Forgot to include config, screenshot attached.
![ringmqttconfig](https://user-images.githubusercontent.com/65832995/186446118-8521f691-63c5-40d8-96d1-3e93f9fe5736.png)

**Comment by tsightler** [comment]
The error log you posted is from the Home Assistant native Ring integration, which only support cameras.  These error have nothing to do with ring-mqtt and clearly the token is not the problem with ring-mqtt since the alarm devices are working.

**Comment by alex-iain-barnett** [comment]
Apologies, clearly got myself all mixed up! Appreciate the time and the great addon.
