### ISSUE TITLE
Stuck on the first line of the wiki - command doesn't work

### ISSUE THREAD

**Issue by rightsaidfred99** [tsightler/ring-mqtt#437]
docker run -it --rm --mount type=bind,source=<host_path>,target=/data --entrypoint /app/ring-mqtt/init-ring-mqtt.js tsightler/ring-mqtt

All I get is 

-bash: host_path: No such file or directory

?

Edit: for those who aren't as technically minded like me, replace "host_path" with the volume path as you did in docker.

**Comment by tsightler** [comment]
Based on the error message it appears that you did not replace the placeholder <host_path> value with an actual valid path on the host as described in the instructions.

**Comment by rightsaidfred99** [comment]
to be fair it says this; 

Prior to running the container for the first time you should edit the <host_path>/config.json file with the appropriate information.

But that is not useful to someone brand new to setitng this up technically. I know this is not support but have no idea what the host path should be pointing too...a directory or the hostname running HA? Or localhost

**Comment by tsightler** [comment]
But this is documented in the [Persistent Storage](https://github.com/tsightler/ring-mqtt/wiki/Installation-(Docker)#persistent-storage) section of the installation instructions, which is prior to the section on running the docker commands.
