### ISSUE TITLE
Ring Control Panel Unavailable Intermittently

### ISSUE THREAD

**Issue by Greigh** [tsightler/ring-mqtt#440]
### Describe the bug
I am having issues with the Ring MQTT. I have this set up on my Home Assistant, and it seems to become "Unavailable" after a while **ONLY on my Ring Alarm system so for my "alarm_control_panel.home_alarm" entity**. I see this in an Overview Dashboard card showing as a gray button. The issue seems to be intermittent as it sometimes happens after 15 minutes, sometimes after a couple of hours, etc. 

### Describe your environment
I have a Home Assistant platform running with a VM with Oracle Virtual Box on Windows 11. Everything is up to date to the latest. Please let me know if there's anything else you need from this. 

### Describe your settings and what you've tried
I have to refresh the token in the Web UI every time it does this. Currently, I believe I have everything set by default in the configuration. I'm not sure if this is changed, but I have Enable Cameras, Enable Modes, and Enable Panic on. The branch is "addon," and the debug is "ring-*". Please let me know if there's anything else you need to know! 

### Debug Logs
Logs seem to be empty because I just generated a new token (?). I will see if I can gather some logs and send them over when it happens again.

**Comment by Greigh** [comment]
I forgot to mention that I use Mosquitto broker.

**Comment by tsightler** [comment]
Thanks for the details but without full logs there's not much that can be done and there's really little reason to open an issue until you can provide them.  I'll leave this open for a day or two, but if you can't provide logs in that time this will be closed.

**Comment by tsightler** [comment]
Closing as it's been 72 hours with no logs provided.  Feel free to reopen when you can provide full logs.
