### ISSUE TITLE
Issues with Initial Install

### ISSUE THREAD

**Issue by WisChrendel** [tsightler/ring-mqtt#46]
I am having issues installing this. I followed all the steps carefully and when I try to start the service it creates a few symlinks and then I get 
`Failed to execute operation: Too many levels of symbolic links`
I tried everything to fix that and couldn't figure it out, so then I went the docker route and I keep getting this error 

```
> ring-alarm-mqtt@1.0.1 start /srv
> node ring-alarm-mqtt.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ring-alarm-mqtt@1.0.1 start: `node ring-alarm-mqtt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ring-alarm-mqtt@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-30T04_53_36_721Z-debug.log
```

New to all this so trying to troubleshoot for hours and I just can't figure it out!

**Comment by tsightler** [comment]
Can you please tell me where you are getting those commands for docker or post exactly what command you are running to start docker (it should be "docker run" with all the required parameters as documented in the README).

Regarding the symlink issue, when exactly are you getting this?  It sounds like you've somehow not properly installed the service file, but you can always just manually start the script and see if at least that is working.  The service file is just for starting automatically during boot.

**Comment by WisChrendel** [comment]
Strangely enough I could not get it to work at all last night. When I tried it today it worked immediately I must have changed something before going to bed last night. thanks for creating this, makes Hass 100% worth it for me
