### ISSUE TITLE
Snapshot intervalDuration logic isn't working properly

### ISSUE THREAD

**Issue by lemeshovich** [tsightler/ring-mqtt#489]
### Describe the Bug

After installing your HA addon, my Ring Spotlight Cams with Battery started to turn on the IR light every 30 sec, this entails very fast battery drain. Seems like that logic isn't working properly:
https://github.com/tsightler/ring-mqtt/blob/e8f2c7364a41acaccc3d8228a6d26dcb323747e7/devices/camera.js#L313

### Steps to Reproduce

Use Ring Spotlight Cam Battery with your addon

### Expected Behavior

According to your JS logic, addon should request new snapshot for Ring Battery devices every 600 seconds, not 30

### Log Output

```shell
2022-11-05T02:09:29.575Z ring-mqtt [CAM-Ring-Dinner] Successfully retrieved updated snapshot
.
.
2022-11-05T02:09:59.551Z ring-mqtt [CAM-Ring-Dinner] Successfully retrieved updated snapshot
.
.
2022-11-05T02:10:29.828Z ring-mqtt [CAM-Ring-Dinner] Successfully retrieved updated snapshot
```

### Config File

```shell
mqtt_url: mqtt://auto_username:auto_password@auto_hostname
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: false
enable_panic: false
branch: addon
debug: ring-*
location_ids:
  - ""

```

### Install Type

HASS Addon

### Version

v5.0.5

### Operating System

HASS OS

### Architecture

amd64

### Machine Details

VMware

Could you fix this please, or ideally to add the addon configuration setting to determine ourselves frequency of the new snapshot requests.

**Comment by lemeshovich** [comment]
One more strange thing, when im starting live video feed in HomeAssistant, cameras IR light turns ON and it will not turns OFF even if ill close the live video feed. Only addon restart can fix permanent IR backlight.

**Comment by lemeshovich** [comment]
@tsightler

**Comment by tsightler** [comment]
If you don't like the default value, just change it.  It's just the default, you can change the interval value per-camera and it will be remembered as it's stored in the state file.

> One more strange thing, when im starting live video feed in HomeAssistant, cameras IR light turns ON and it will not turns OFF even if ill close the live video feed. Only addon restart can fix permanent IR backlight.

This addon has no control over the IR light, it starts and stops streams, that's it, the camera controls whether IR the light is on or not.  If the light is on then it's very likely the stream is still active.  Assuming you are viewing via Home Assistant then this is already explained in the FAQ as Home Assistant keeps the stream alive for 5 minutes after you view it in HA.

**Comment by lemeshovich** [comment]
can you please explain how can i change the default value of requesting new snapshots?

**Comment by tsightler** [comment]
Just go to the device in Home Assistant and the snapshot interval is there, it shows the current value and you can change it to whatever value you like, along with the other settings such as snapshot mode, etc.

**Comment by lemeshovich** [comment]
Do you mean generic camera device? I cant find such as options there

**Comment by tsightler** [comment]
The snapshot camera that is automatically created.  That's where all the settings for snapshots are.  The generic IP camera that has to be manually created has no settings because it's only for the live/event stream.

**Comment by lemeshovich** [comment]
maybe im blind, but i have no snapshot devices
![nosnapshot](https://user-images.githubusercontent.com/17667824/200147797-3b664709-5f8b-41b0-a381-ff405ec2a99e.png)
in Media>Camera there is also only Generic Camera devices that i created manualy

**Comment by tsightler** [comment]
Then how are you even using the addon?  If there are no devices in this list you won't get access to things like the snapshots or the switch to turn the light on/off, etc.  If you have no devices there then you don't have a properly working addon.  It wouldn't have "snapshot" in the device name, it would just be the name of your camera same as in the Ring app (looks like CAM-Ring-Dinner, in your case).  If you are not seeing these devices then you need to verify your MQTT setup.

**Comment by lemeshovich** [comment]
Im using the defauld Ring HA service to turn the light on/off, etc. Also i can see the live feed and still_image snapshots from your addon, so seems like it is working. Im using the default HA Mosquitto Broker MQTT addon. I folloved your [instruction](https://github.com/tsightler/ring-mqtt/wiki/Video-Streaming) when installing the addon

**Comment by tsightler** [comment]
Where do you see the still_image_snapshots from?  They can only exist in the snapshot camera as it's just a template value that access the still image from this camera.  In the device screen try searching for "ring" instead of "snap" and see what devices are there.

**Comment by tsightler** [comment]
Another option is to select the entities tab, rather than the devices tab, and search for snap there, the entity itself should have snapshot in the name.

**Comment by lemeshovich** [comment]
I just reallized that i had no MQTT service installed, i had only Mosquitto addon. Now i can see all the settings including snapshot request rate. Sorry for bothering and thanks for the replies
