### ISSUE TITLE
Please Add Location Environment Variable

### ISSUE THREAD

**Issue by 53milesperburrito** [tsightler/ring-mqtt#49]
Hi there,

Thanks for creating this!

Would you mind adding an environment variable to specify which ring locations are monitored for those of us using docker?

Thanks!

**Comment by 53milesperburrito** [comment]
I added a solution for your consideration here:
https://github.com/tsightler/ring-mqtt/pull/50

**Comment by tsightler** [comment]
Thanks, I need to update for the removal of username/password so I'll work this in to that update.

**Comment by tsightler** [comment]
I merged this with some minor modifications to handle the case where the environment variable isn't defined (everything except RINGTOKEN should be optional).
