### ISSUE TITLE
Question regarding streaming server

### ISSUE THREAD

**Issue by jjanderson** [tsightler/ring-mqtt#491]
Hello,

Thanks for the great add-on. Nice work!

I just have a question regarding the docs where it says:

"Ring video streaming support is implemented by running a local RTSP server provided by the excellent [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) project."

Is this simple rtsp server bundled with your add-on or do we have to install it ourselves?

If we nede to isntall a streaming server, can we not use something like Agent DVR instead? I know you say that this is not recommended due to breaking motion detection and that this is not a 24/7 streaming camera, but I was just wondering what the rtsp simple server brings to the party when I already have another streaming server setup to deliver camera's into HA?

I don't mind installing that server if it is not bundled with your add-on, I am always just quite keen to run as few servers/services as possible.

Many thanks again for your hard work and bringing us this awesome plugin!

**Comment by tsightler** [comment]
The rtsp-simple-server code is part of the docker image or can be installed manually if using the standard install method.  In all cases the ring-mqtt starts and manages the rtsp-simple-server instance, there's nothing that needs to be done.

The rtsp-simple-server is just used as a way to provide access to Ring's proprietary data stream using an industry standard streaming protocol.  The entire process is explained fairly deeply in "How it works" section of the video streaming wiki, I'm not really sure what more I could possibly add here.

In the future I would ask that such questions be posted in the discussions section vs opening an issue, as is noted at the very top of the issue template.
