### ISSUE TITLE
location is disconnected

### ISSUE THREAD

**Issue by grasshide** [tsightler/ring-mqtt#5]
First of all thank you for the very quick response on the issue on the other repo!
I feel bad to report another problem with this code again. It seems it is somehow not working although it is constantly (every two seconds) polling for new events.
The only mqtt message I get is the one that reports "offline". No events are reported (motion or ding).
I only have one ring pro doorbell, nothing else. The code is running in a docker container.
Here is the debug log (I redacted and sorted it a bit):
`,
> ring-mqtt@1.1.0 start /srv,
> node ring-mqtt.js,
,
2020-01-02T10:34:10.287Z error Configuration file not found, try environment variables!,
2020-01-02T10:34:10.290Z ring Making request: {,
  "url": "https://oauth.ring.com/oauth/token",,
  "data": {,
    "client_id": "ring_official_android",,
    "scope": "client",,
    "grant_type": "password",,
    "password": "xxx",,
    "username": "xxx",
  },,
  "method": "POST",,
  "headers": {,
    "content-type": "application/json",,
    "2fa-support": "true",,
    "2fa-code": "",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:10.295Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/oauth/token',,
  method: 'POST',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     'Content-Type': 'application/json',,
     '2fa-support': 'true',,
     '2fa-code': '',,
     hardware_id: 'c46xxx277',,
     'User-Agent': 'axios/0.19.0',,
     'Content-Length': 136 },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'oauth.ring.com',,
  port: null,,
  nativeProtocols: ,
   { 'http:': ,
      { xxx } },
2020-01-02T10:34:10.798Z ring Making request: {,
  "url": "https://api.ring.com/clients_api/session",,
  "data": {,
    "device": {,
      "hardware_id": "c46xxx277",,
      "metadata": {,
        "api_version": 11,
      },,
      "os": "android",
    },
  },,
  "method": "POST",,
  "headers": {,
    "authorization": "Bearer eyJxxxKNw",,
    "content-type": "application/json",
  },
},
2020-01-02T10:34:10.800Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/clients_api/session',,
  method: 'POST',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     'Content-Type': 'application/json',,
     authorization: 'Bearer eyJxxxKNw',,
     'User-Agent': 'axios/0.19.0',,
     'Content-Length': 110 },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'api.ring.com',,
  port: null,,
  nativeProtocols: ,
   { 'http:': ,xxx } },
2020-01-02T10:34:11.144Z ring Making request: {,
  "method": "GET",,
  "url": "https://app.ring.com/rhq/v1/devices/v1/locations",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:11.145Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/rhq/v1/devices/v1/locations',,
  method: 'GET',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     authorization: 'Bearer eyJxxxKNw',,
     hardware_id: 'c46xxx277',,
     'Content-Type': 'application/x-www-form-urlencoded',,
     'User-Agent': 'axios/0.19.0' },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'app.ring.com',,
  port: null,,
  nativeProtocols: xxx,
2020-01-02T10:34:11.645Z ring Making request: {,
  "method": "GET",,
  "url": "https://api.ring.com/clients_api/ring_devices",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:11.645Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/clients_api/ring_devices',,
  method: 'GET',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     authorization: 'Bearer eyJxxxKNw',,
     hardware_id: 'c46xxx277',,
     'Content-Type': 'application/x-www-form-urlencoded',,
     'User-Agent': 'axios/0.19.0' },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'api.ring.com',,
  port: null,,
  nativeProtocols: xxx,
2020-01-02T10:34:12.088Z mqtt Connection established with MQTT broker, sending config/state information in 5 seconds.,
2020-01-02T10:34:14.054Z ring Making request: {,
  "method": "GET",,
  "url": "https://api.ring.com/clients_api/dings/active",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:14.055Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/clients_api/dings/active',,
  method: 'GET',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     authorization: 'Bearer eyJxxxKNw',,
     hardware_id: 'c46xxx277',,
     'Content-Type': 'application/x-www-form-urlencoded',,
     'User-Agent': 'axios/0.19.0' },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'api.ring.com',,
  port: null,,
  nativeProtocols: xxx,,
        get: [Function: get] } } },
2020-01-02T10:34:16.298Z ring Making request: {,
  "method": "GET",,
  "url": "https://api.ring.com/clients_api/dings/active",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:16.299Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/clients_api/dings/active',,
  method: 'GET',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     authorization: 'Bearer eyJxxxKNw',,
     hardware_id: 'c46xxx277',,
     'Content-Type': 'application/x-www-form-urlencoded',,
     'User-Agent': 'axios/0.19.0' },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'api.ring.com',,
  port: null,,
  nativeProtocols: ,
   { 'http:': ,xxx,,
        get: [Function: get] } } },
2020-01-02T10:34:17.096Z ring-mqtt Location 638xxxd94 is disconnected,
2020-01-02T10:34:18.542Z ring Making request: {,
  "method": "GET",,
  "url": "https://api.ring.com/clients_api/dings/active",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
2020-01-02T10:34:18.543Z follow-redirects options { protocol: 'https:',,
  maxRedirects: 21,,
  maxBodyLength: 10485760,,
  path: '/clients_api/dings/active',,
  method: 'GET',,
  headers: ,
   { Accept: 'application/json, text/plain, */*',,
     authorization: 'Bearer eyJxxxKNw',,
     hardware_id: 'c46xxx277',,
     'Content-Type': 'application/x-www-form-urlencoded',,
     'User-Agent': 'axios/0.19.0' },,
  agent: undefined,,
  auth: undefined,,
  hostname: 'api.ring.com',,
  port: null,,
  nativeProtocols: ,
   { 'http:': ,xxx,
2020-01-02T10:34:20.776Z ring Making request: {,
  "method": "GET",,
  "url": "https://api.ring.com/clients_api/dings/active",,
  "data": "",,
  "headers": {,
    "content-type": "application/x-www-form-urlencoded",,
    "authorization": "Bearer eyJxxxKNw",,
    "hardware_id": "c46xxx277",
  },
},
`

**Comment by tsightler** [comment]
I'm confident this is a duplicate of issue #3, so I'm going to close this.  Please see notes there.
