### ISSUE TITLE
Ring is blocking me?

### ISSUE THREAD

**Issue by talshum** [tsightler/ring-mqtt#5]
I suspect that every time I try to use the script RIng is blocking me. After launching it I'm unable to access my ring account from my phone or online. This time I got:

" error Couldn't create the API instance. This could be because ring.com changed their API again"

**Comment by tsightler** [comment]
I'm relatively confident this would not be due to the script.  If you were trying this today Ring was definitely having some issues.  My app was failing to connect to cameras, etc.  But my alarm was still working on the existing websocket.

**Comment by talshum** [comment]
I hope so, happened to me yesterday and today. So after two times I realized maybe it's the script?
1) do you know how does the API work? is it supported by Ring or a hack?
2) I was able to integrate your awesome script into hass.io add on - super hacky but it worked - thanks!

**Comment by tsightler** [comment]
Sure, the API is really quite simple at it's base.  It's certainly not supported by Ring as Ring refuses to provide an API, so it's reverse engineered from the app.  Basically you authenticate to get a token, then create a websocket connection via socket.io.  From that point, it's easy to communicate and do everything in real-time, which is perfect for an alarm (the API used by their camers/doorbells is an old school polling approach, and sucks!).  From Ring's perspective, the API connection should look just like the app.  While they could potentially implement methods to attempt to block it, I think it's unlikely they would bother and I've seen no indication of this.

However, I've been developing this script for about 3 months, and several times over that period I've seen various app issues authenticating or returning errors like you described.  They do not seem to be related to the script as they occurred at random times.  It was especially bad in the weeks just after Christmas.

I'm glad you were able to get it working with Hass.io, did you use an approach different than the docker image from rajansub that was already posted in the community thread?

https://github.com/rs1932/ring-alarm-hassio-addon

**Comment by talshum** [comment]
Thanks for the explanation!
Lol I didn’t realize rajansub based his script on yours. I thought it was only for the other one who I forgot their name.

Well, at least now I know how to build an add on :)


________________________________
