### ISSUE TITLE
Home Assistant - how to trigger the alarm_control_panel

### ISSUE THREAD

**Issue by raelix** [tsightler/ring-mqtt#508]
#### Describe the problem
Hi everyone, I'm trying to trigger the alarm (when armed_home or armed_away) from home assistant. 
The alarm_control_panel device has the trigger service which should allow triggering the alarm but on the ring-mqtt logs I just see ```Cannot set alarm mode: Unknown``` . I'm not sure what is the suggested way of triggering the alarm from home assistant.

With the trigger I would like to cause also the ```alarmState``` ```entry-delay``` for my door nuki sensor.

##### Describe your environment
ring-mqtt as addon on home assistant running on docker

Thanks in advance :)

**Comment by tsightler** [comment]
Ring-mqtt is limited to doing things that are available via the Ring API, which mostly means things available in the Ring app.  The only way to trigger the alarm in the Ring app, that I know of, is via panic switches, which you can make available in the addon with the enable_panic feature, however, I believe this only works with a Ring protect subscription.  I'm not aware of any other method to trigger the alarm via API.
