### ISSUE TITLE
Out of a sudden connection to Ring API broken

### ISSUE THREAD

**Issue by Stefan300381** [tsightler/ring-mqtt#510]
Hi,

today noticed that my doorbell didn't ring (the bell will ring once it received the correct mqtt message). 
So I restarted ring-mqtt and checked the logs. This is where it stalls, see below.
Any idea how to further troubleshoot the issue?

```
s6-rc: info: service legacy-services: stopping
2022-11-29T10:09:36.720Z ring-mqtt The ring-mqtt process is shutting down...
2022-11-29T10:09:38.723Z ring-mqtt Exit code: 0
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/ring-mqtt.sh
-------------------------------------------------------
| Ring-MQTT with Video Streaming                      |
| Docker Edition                                      |
|                                                     |
| For support questions please visit:                 |
| https://github.com/tsightler/ring-mqtt/discussions  |
-------------------------------------------------------
cont-init: info: /etc/cont-init.d/ring-mqtt.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ring-mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
-------------------------------------------------------
ring-mqtt.js version: 5.0.4
Node version v16.17.1
NPM version 8.10.0
git version 2.36.2
-------------------------------------------------------
Running ring-mqtt...
2022-11-29T10:09:54.403Z ring-mqtt Detected runmode: docker
2022-11-29T10:09:54.406Z ring-mqtt Configuration file: /data/config.json
2022-11-29T10:09:54.408Z ring-mqtt MQTT URL: mqtt://openhabian:********@192.168.2.9:1883
2022-11-29T10:09:55.717Z ring-mqtt Reading latest data from state file: /data/ring-state.json
2022-11-29T10:09:55.806Z ring-mqtt Attempting connection to Ring API using saved refresh token...
```

**Comment by tsightler** [comment]
First, I would make sure that's the full log.  Did you gather that from the command line or only from the UI.  The most common issue with freezing during startup is that some alarm or smart lighting hub/device is offline, but if it is really hanging at the line you have then that would imply that it can't reach the Ring API servers or Ring servers are not responding as expected.

**Comment by Stefan300381** [comment]
Thanks. I took the logdata from the docker container via portainer. Any other recommended way to access the full log?

**Comment by tsightler** [comment]
Yeah, sorry, I didn't notice that you were running Docker.  I'd guess Portainer log is probably accurate, but you can always use "docker logs" command to be 100% sure.  Some UIs batch log messages only every X number of lines so they cut off the last few lines.

Unfortunately, I don't know what else to do here, I guess you could try getting a new refresh token and see if that helps.  Ring's servers have had a lot of issues over the last week, lots of sporadic error messages and some periods of throttling, so maybe you are just throttled.  But if it's really failing at that line, there's literally only two commands between this message and the next message, establishing the API and a quick call to getProfile() which verifies the connection was made.  This code is basically unchanged for years and I've never had a single report of a hang at that spot.

The next step would be to enable full debugging (*), but just a warning, it's going to be a LOT of logs.

**Comment by Stefan300381** [comment]
Hi,

ffs ;-) Issue resolved by disabling the Synology firewall (which I enabled just recently). It had just one rule, to block incoming requests on port 80 and 443, so I didn't think about this at first. 

Actually I still have no clue why this interferes with outgoing requests from my docker containers. Anyway, disabled, runs fine. 

EDIT: For people using Synology firewall:
Synology firewall acts as a router between "WAN" and local "LANs". It treats 172.17.0.* (default network for docker images) as a "LAN" connected to it. Thus, since it's not "internal outbound" traffic, it blocks everything coming out of docker containers, unless explicitly allowed.
Source: https://community.synology.com/enu/forum/11/post/142221

Stefan
