### ISSUE TITLE
Addon configuration page won't let me add location id arrays

### ISSUE THREAD

**Issue by atownsend247** [tsightler/ring-mqtt#523]
### Describe the Bug

Upon initial configuration of the HA addon, you can enter the mqtt server address fine, but the options to add the location ids field whenever I enter anything and click away to save, it remove any value you entered into the location id box

### Steps to Reproduce

Install the ring-mqtt addon, go to the configuration tab, enter mqtt server id and location ids, then try to save.

### Expected Behavior

Should allow you add/amend location ids from the configuration page.

### Log Output

```shell
There doesn't seem to be anything in the log output that I could find that would suggest any issue with the UI input.
```

### Screenshots

I was going to attach the screenshot, but every time it removes focus from the page it removes the input.

### Config File

```shell
I only needed my mqtt address, everything else was left as default bar enabling cameras which was set to false.
```

### Install Type

Home Assistant supervised / Supervisor 2022.12.1 / Frontend 20221213.1 - latest

### Version

Home Assistant 2022.12.8

### Operating System

Debian

### Architecture

x86_64

### Machine Details

Virtual Machine / XCP-ng - XenServer

**Comment by atownsend247** [comment]
I'm actually thinking this is a Home Assistant UI bug, have reported it on that repo also, can be found here:

https://github.com/home-assistant/frontend/issues/14972

**Comment by tsightler** [comment]
I'd suggest just switching to YAML view and add whatever entries you need there.  I've never been able to figure out how to get this to work in the fancy HA "configuration UI" since HA started trying to make it "easier" by layering a UI over the existing YAML config.  IMO, editing YAML is already pretty easy, and it has always just worked, and still does even now.  If for some reason I'm doing something wrong in the addon config, feel free to submit a PR to address it, but as far as I can see it is compliant with the specifications defined in their addon development documentation.

**Comment by atownsend247** [comment]
TDIL, thanks for that :) why didn't I think to look for a yaml editor, well that solved my problem.

Regards
-Andrew

**Comment by tsightler** [comment]
And don't get me wrong, I'd be happy to make whatever change is required to get this to work correctly with the UI editor, but I've tried tinkering with the addon configuration schema for a while and just couldn't seem to find the combination that worked, even though it has worked fine for the YAML based editor for years, which also performs validation and uses the same schema.

**Comment by tsightler** [comment]
Took a quick look at several other plugins that use lists as part of their configuration, File Editor, Let's Encrypt, MariaDB, and SSH & Web Terminal.  These are maintained people that know a heck of lot more about Home Assistant than I do, and they all have the same non-working behavior when attempting to add items via the HA UI configuration mode, so I'm going to assume this is just a bug in HA that will eventually be fixed.  Current workaround is just to use YAML configuration mode.
