### ISSUE TITLE
Lost the ability to arm/disarm

### ISSUE THREAD

**Issue by sbtrey23** [tsightler/ring-mqtt#532]
### Describe the Bug

I've been using the Ring MQTT for about a month now and it's worked flawlessly. I've been able to use my full security system in HA. However, two days ago, the ability to arm/disarm the system has disappeared. There use to be entities that let me arm and disarm the house in both home and away mode. Now, the only entities for the alarm are turning on/off the panic buttons. My setup still works through the Ring app, so I'm assuming something happened with the MQTT (not sure if on my end or not). 

### Steps to Reproduce

Click the alarm, got to entities, the arm/disarm are missing

### Expected Behavior

It is expected that I would be able to arm/disarm my system. 

### Log Output

```shell
There are no relevant logs for this, as it is just something that is now missing. The MQTT otherwise still runs perfectly fine.
```

### Config File

```shell
NA
```

### Install Type

Addon

### Version

v5.0.5

### Operating System

Home Assistant OS

### Architecture

arm64

### Machine Details

Virtual Machine

**Comment by tsightler** [comment]
No logs, no bug.
