### ISSUE TITLE
I can see snapshots camera but not live streaming 

### ISSUE THREAD

**Issue by FIlcast-dev** [tsightler/ring-mqtt#545]
I followed the entire setup process and all my Ring devices have been detected and are working in HA. The only problem is that I can't see the camera's RTSP stream, just the snapshots.

These are the parameters I have.

[
![IMG_0434](https://user-images.githubusercontent.com/79178722/217810709-0e7eaf87-b724-413a-a583-f152fbdb5fa6.png)
![IMG_0435](https://user-images.githubusercontent.com/79178722/217810758-7b6d9192-e976-4757-ba72-34805b503a64.png)

some suggestion?
Thanks

**Comment by tsightler** [comment]
> The only problem is that I can't see the camera's RTSP stream, just the snapshots.

I'm afraid I don't know what this means.  As stated in the documentation the live and event stream cameras must be added manually to HA as there's no automatic way for them to be discovered.  Your provided screenshots of MQTT discovery, but that doesn't apply here.  The live stream URL shows the information needed to add the cameras to HA configuration.

**Comment by tsightler** [comment]
Closing due to no response.  Feel free to re-open if you want to provide more clarity on what you have done, or use the discussion forums for help.
