### ISSUE TITLE
Generic Binary Sensor added to RING is not creating the state entity in Home Assistant

### ISSUE THREAD

**Issue by rgb2017** [tsightler/ring-mqtt#553]
### Describe the Bug

Generic Binary Sensor Added in RING Not Creating State Entity 

### Steps to Reproduce

Added a Zooz ZSE41 Contact Sensor to RING

### Expected Behavior

Expecting to see the open/closed state of the sensor in Home Assistant

### Log Output

```shell
RING MQTT log...

2023-02-11T21:14:52.070Z ring-disc HASS config topic: homeassistant/binary_sensor/e54921a0-d83f-412c-b395-2bca0fd50aea/b68e0eb1-c9b2-4920-888d-1560cb3a0dd1_binary_sensor/config
2023-02-11T21:14:52.070Z ring-disc {
  name: 'New Contact',
  unique_id: 'b68e0eb1-c9b2-4920-888d-1560cb3a0dd1',
  state_topic: 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/b68e0eb1-c9b2-4920-888d-1560cb3a0dd1/binary_sensor/state',
  device_class: 'None',
  availability_topic: 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/b68e0eb1-c9b2-4920-888d-1560cb3a0dd1/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ 'b68e0eb1-c9b2-4920-888d-1560cb3a0dd1' ],
    name: 'New Contact',
    mf: 'Ring',
    mdl: 'Generic Binary Sensor'
  }
}


Home Assistant log error on initial discovery and on restarts....



2023-02-11 14:16:33.069 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'name': 'New Contact', 'unique_id': 'b68e0eb1-c9b2-4920-888d-1560cb3a0dd1', 'state_topic': 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/b68e0eb1-c9b2-4920-888d-1560cb3a0dd1/binary_sensor/state', 'device_class': 'None', 'availability_topic': 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/b68e0eb1-c9b2-4920-888d-1560cb3a0dd1/status', 'payload_available': 'online', 'payload_not_available': 'offline', 'device': {'identifiers': ['b68e0eb1-c9b2-4920-888d-1560cb3a0dd1'], 'name': 'New Contact', 'manufacturer': 'Ring', 'model': 'Generic Binary Sensor'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 334, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected BinarySensorDeviceClass or one of 'battery', 'battery_charging', 'carbon_monoxide', 'cold', 'connectivity', 'door', 'garage_door', 'gas', 'heat', 'light', 'lock', 'moisture', 'motion', 'moving', 'occupancy', 'opening', 'plug', 'power', 'presence', 'problem', 'running', 'safety', 'smoke', 'sound', 'tamper', 'update', 'vibration', 'window' for dictionary value @ data['device_class']
```

### Screenshots

![sensorCapture](https://user-images.githubusercontent.com/31419732/218282035-a959738b-1088-429b-8fc0-b6e1c87daf73.PNG)

### Config File

```shell
"integration_manifest": {
    "domain": "mqtt",
    "name": "MQTT",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/mqtt",
    "requirements": [
      "paho-mqtt==1.6.1"
    ],
    "dependencies": [
      "file_upload",
      "http"
    ],
    "codeowners": [
      "@emontnemery",
      "@jbouwh"
    ],
    "iot_class": "local_push",
    "quality_scale": "gold",
    "is_built_in": true
  },
  "data": {
    "connected": true,
    "mqtt_config": {
      "birth_message": {
        "topic": "homeassistant/status",
        "payload": "online",
        "qos": 0,
        "retain": false
      },
      "discovery": true,
      "discovery_prefix": "homeassistant",
      "port": 1883,
      "protocol": "3.1.1",
      "tls_version": "auto",
      "transport": "tcp",
      "will_message": {
        "topic": "homeassistant/status",
        "payload": "offline",
        "qos": 0,
        "retain": false
      },
      "keepalive": 60,
      "broker": "core-mosquitto",
      "username": "**REDACTED**",
      "password": "**REDACTED**",
      "ws_path": "/",
      "ws_headers": {}
    },
```

### Install Type

Home Assistant Add On

### Version

v5.1.3

### Operating System

Home Assistant OS

### Architecture

x86_64

### Machine Details

VMWare Virtual Machine

**Comment by tsightler** [comment]
Thanks for the report, interesting that it's never been reported before even though that code is largely unchanged for over a year.  I feel like HA documentation isn't very clear, it specifically lists "None" and, while it does say it doesn't "need" to be set, it doesn't say it can't be set, and it's in the list with all the values that can be set.

Oh well, it's listed as optional, so I'll just remove it.  You can try the dev branch and see if it works now.

**Comment by rgb2017** [comment]
Same issue after switching to the Dev branch.  Just to be sure, I deleted the sensor from Home Assistant and removed and added it again in the RING app. 
ring-mqtt.js version: 5.1.4-beta1

I don't see a change in the data device class. Here is the log detail which looks the same...

2023-02-11T22:28:32.814Z ring-disc HASS config topic: homeassistant/binary_sensor/e54921a0-d83f-412c-b395-2bca0fd50aea/f27d2ccd-71ed-452a-8b38-ce90ebd4785f_binary_sensor/config
2023-02-11T22:28:32.814Z ring-disc {
  name: 'New Contact',
  unique_id: 'f27d2ccd-71ed-452a-8b38-ce90ebd4785f',
  state_topic: 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/f27d2ccd-71ed-452a-8b38-ce90ebd4785f/binary_sensor/state',
  device_class: 'None',
  availability_topic: 'ring/e54921a0-d83f-412c-b395-2bca0fd50aea/alarm/f27d2ccd-71ed-452a-8b38-ce90ebd4785f/status',
  payload_available: 'online',
  payload_not_available: 'offline',
  device: {
    ids: [ 'f27d2ccd-71ed-452a-8b38-ce90ebd4785f' ],
    name: 'New Contact',
    mf: 'Ring',
    mdl: 'Generic Binary Sensor'
  }
}

**Comment by tsightler** [comment]
Sorry, looks like I had it set as default class and then also explicitly set for generic sensors.  I didn't realize that initially.  Hopefully it's fixed now.

**Comment by rgb2017** [comment]
That did the trick! The state was automatically added in Home Assistant after restarting RING-MQTT and I no longer see the device_class in the log data. Thank you for the quick fix!

**Comment by tsightler** [comment]
No problem, it will be included in the next release, whatever version that happens to be.  Thanks for the super clear bug report, it is so rare!

**Comment by tsightler** [comment]
Finally pushed 5.2.0 which includes this fix.  Thanks again for the clear report!
