### ISSUE TITLE
entity in HA status delay

### ISSUE THREAD

**Issue by tpbillund** [tsightler/ring-mqtt#574]
Hi.
When open or close a window, to get ON or OFF
2023-03-02T13:21:05.010Z ring-mqtt [Kontor Vindue] ring/fa0xxxxxx9/alarm/00xxxxx8c66e/contact/state OFF

Then it take 30 sec. before the entity in HA is shift the status - can I changes that, so it's not 30 sec. but maybe 5-10 sec. so I can use it to trigger a alarm status?

**Comment by tsightler** [comment]
There should be no delay in the status in HA, perhaps you are seeing some type of bad caching behavior in the UI?  If you are seeing a major delay you will have to troubleshoot the HA side of things, but that is outside of the scope of ring-mqtt.  For me, status updates in HA are near instant with the MQTT message.
