### ISSUE TITLE
Bug: Docker gives Lchown / subordinate IDs error after 5.0.5

### ISSUE THREAD

**Issue by cliffjao** [tsightler/ring-mqtt#590]
### Describe the Bug

Docker gives Lchown / subordinate IDs error after 5.0.5; last known good version was 5.0.5, can't upgrade without error.

### Steps to Reproduce

Docker pull and run tsightler/ring-mqtt

### Expected Behavior

No errors from Docker when starting up

### Log Output

```shell
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/app/ring-mqtt/node_modules/brorand/.npmignore" for UID 120012366, GID 120012366 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/ring-mqtt/node_modules/brorand/.npmignore: invalid argument
```

### Config File

```shell
{
    "mqtt_url": "mqtt://REDACTED@REDACTED:1883",
    "mqtt_options": "",
    "livestream_user": "",
    "livestream_pass": "",
    "disarm_code": "",
    "enable_cameras": false,
    "enable_modes": false,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ]
}
```

### Install Type

Docker

### Version

> 5.0.5

### Operating System

Debian LXC

### Architecture

x86_64

### Machine Details

Running via unprivileged LXC

**Comment by tsightler** [comment]
Sorry, but you'll have to figure this out yourself as this is not a problem with the container image, but the way you have elected to run it as running docker in an unpriviledged LXC container is fraught with problems.  You are of course welcome to do this if you want, however, I'm not going to spend my time troubleshoot problems with some hacky way of running Docker that goes explicitly against Docker's own recommendations.

If you can reproduce this issue with a more traditional and supported Docker install (unlikely since there are nearly 6000 instances of 5.1.3 and 5.2.0 already running out there), feel free to re-open.

**Comment by cliffjao** [comment]
Thanks for confirming no one else has ran into this issue on a standard install. For anyone that finds this through search in the future, I was able to fix this error by editing /etc/subuid and /etc/subgid on the **host** system (Proxmox in my case) to increase the range of UID & GID mappings to cover the range that the error pointed out.

```
$ cat /etc/subuid
root:100000:1000065536
$ cat /etc/subgid
root:100000:1000065536
```

**Comment by tsightler** [comment]
Thanks for coming back and sharing what you found as a solution for this issue and confirming that it was a change on the host and not the container itself.

**Comment by bit-bat** [comment]
I am having the same issue and it looks like the issue is stemming from npm image.
@cliffjao I tried setting the subguid and subuid on Proxmox host and it did not help me. Could you please share the steps you took so I can replicate? Thanks.

**Comment by cliffjao** [comment]
> I am having the same issue and it looks like the issue is stemming from npm image. @cliffjao I tried setting the subguid and subuid on Proxmox host and it did not help me. Could you please share the steps you took so I can replicate? Thanks.

All I did was change the subuid and subgid range on Proxmox host. What's your full setup like, also Docker within LXC within Proxmox? Can you show `cat /etc/subuid` and `cat /etc/subgid`?

**Comment by bit-bat** [comment]
Yes, I am running an unprivileged, nested LXC on Proxmox. Docker is running inside this LXC.

**On Proxmox**:

```
root@Proxmox:~# cat /etc/pve/lxc/104.conf
...
features: keyctl=1,nesting=1
unprivileged: 1
...

root@Proxmox:~# cat /etc/subgid
bitbat:100000:65536
root:100000:1000065536

root@Proxmox:~# cat /etc/subuid
bitbat:100000:65536
root:100000:1000065536
```

**On Docker**:
```
root@Docker:~# docker pull tsightler/ring-mqtt
Using default tag: latest
latest: Pulling from tsightler/ring-mqtt
f56be85fc22e: Already exists
caf81029db3b: Pull complete
4be377dff407: Extracting [==================================================>]  79.32MB/79.32MB
failed to register layer: failed to Lchown "/app/ring-mqtt/node_modules/brorand/.npmignore" for UID 120012366, GID 120012366 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/ring-mqtt/node_modules/brorand/.npmignore: invalid argument
```

**Comment by cliffjao** [comment]
> Yes, I am running an unprivileged, nested LXC on Proxmox. Docker is running inside this LXC.
> 
> **On Proxmox**:
> 
> ```
> root@Proxmox:~# cat /etc/pve/lxc/104.conf
> ...
> features: keyctl=1,nesting=1
> unprivileged: 1
> ...
> 
> root@Proxmox:~# cat /etc/subgid
> bitbat:100000:65536
> root:100000:1000065536
> 
> root@Proxmox:~# cat /etc/subuid
> bitbat:100000:65536
> root:100000:1000065536
> ```
> 
> **On Docker**:
> 
> ```
> root@Docker:~# docker pull tsightler/ring-mqtt
> Using default tag: latest
> latest: Pulling from tsightler/ring-mqtt
> f56be85fc22e: Already exists
> caf81029db3b: Pull complete
> 4be377dff407: Extracting [==================================================>]  79.32MB/79.32MB
> failed to register layer: failed to Lchown "/app/ring-mqtt/node_modules/brorand/.npmignore" for UID 120012366, GID 120012366 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/ring-mqtt/node_modules/brorand/.npmignore: invalid argument
> ```

Hm. I also expanded the UID/GID range in my LXC conf. Maybe that's also needed.

`lxc.idmap: u 0 100000 1000065536`
`lxc.idmap: g 0 100000 1000065536`


I believe the core problem here is that the UID/GID (120012366) for the .npmignore file is outside the default allowable range of 65536. So that's why I expanded the range from 65536 to 1000065536 in all the relevant places.
