### ISSUE TITLE
bi-directional audio for RING INTERCOM

### ISSUE THREAD

**Issue by pilot1981** [tsightler/ring-mqtt#612]
It’s possibile have BI-directional audio flow from RING INTERCOM?

my next step is to publish to HomeKit.

regards

**Comment by tsightler** [comment]
No, it's not possible as audio for intercom is not currently supported in ring-client-api and, more critically, ring-mqtt does not have any support for bi-directional audio for any device.

As you are looking to integrate with Homekit it would probably be better to add you vote to a project that is focused on Homekit integration like homebridge-ring or perhaps Scrypted.
