### ISSUE TITLE
Pending state not working

### ISSUE THREAD

**Issue by hamzah** [tsightler/ring-mqtt#616]
Hi,
I'm trying to get the bulb next to my keypad flash when the entry delay has started and turn off when it has ended. I've tried to set up this trigger:

``` platform: device
device_id: REDACTED
domain: alarm_control_panel
entity_id: alarm_control_panel.office_alarm
type: pending
```

But I get the following error:

`Message malformed: value must be one of ['armed_away', 'armed_home', 'armed_night', 'armed_vacation', 'arming', 'disarmed', 'triggered'] for dictionary value @ data['type']`

Has Ring-MQTT dropped support for the pending state? I'm running a RPi 3, using the add-on, with HA OS.

**Comment by tsightler** [comment]
Nothing has changed with alarm support in ring-mqtt for a very long time and no features have been dropped.

The error you are reporting is not from ring-mqtt, it is from Home Assistant as you are attempting to use the device level options for your trigger, but these are almost always more limited.  As I'm not a Home Assistant expert and, these days, barely even use it (just enough to keep the plugin working) I'm not the best person to ask for help with Home Assistant automations, but I personally would just use a state based trigger which will definitely offer the option of selecting "pending" state.

```
platform: state
entity_id:
  - alarm_control_panel.my_ring_alarm
to: pending
```

**Comment by hamzah** [comment]
This worked perfectly!

I'm not a big HA user either. Only set this box up to replace my routine hell from the Alexa App. Thanks for your help.
