### ISSUE TITLE
Run the bundled init-ring-token.js utility directly via the Docker command line to acquire the token

### ISSUE THREAD

**Issue by serbasan** [tsightler/ring-mqtt#618]
I try to run:

docker run -it --rm --mount type=bind,source=/home/dagos/ring-mqtt/data,target=/data --entrypoint /app/ring-mqtt/init-ring-mqtt.js tsightler/ring-mqtt

And I get the following:

docker run -it --rm --mount type=bind,source=/home/dagos/ring-mqtt/data,target=/data --entrypoint /app/ring-mqtt/init-ring-mq$
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exe$
ERRO[0000] error waiting for container: context canceled

I'm stuck as that step is needed to generate the ring-state.json file.

I hope help because I don't know what to do.

This runs perfectly "docker run --rm --mount type=bind,source=/home/dagos/ring-mqtt/data,target=/data tsightler/ring-mqtt"
but indicates that the old file is missing.

Thank you so much

#

**Comment by tsightler** [comment]
Can you please check for any type of copy/paste error when running the command.  The error message you posted makes it look like the end of the command was not processed due to an early line break.  It's hard to believe there is an actual problem with the code, because this is needed for all docker users and there have been zero other reports of this issue even though I know roughly 20% of users leverage the docker image directly.

**Comment by tsightler** [comment]
Based on a little research, this appears to be related to the Docker environment as there are many examples of this error all over the web with various solutions.  Unfortunately, I'm unable to help troubleshoot issues not directly related to the ring-mqtt code or Docker image itself.  I would suggest Googling this error message and looking at the various solutions presented.

One thing I would make sure if is that your Docker environment is current and that the host has enough resources to run the container.  Good luck!

**Comment by tsightler** [comment]
One common issue for stuff like this is attempting to run Docker on non-root or inside another container (like an LXC container on Proxmox).  You didn't share anything about your environment, but that might be something to look into.

**Comment by serbasan** [comment]
Your comments made it clear to me. I have tried on another server and it has worked perfectly. It is a problem of my environment.

Thank you so much.
