### ISSUE TITLE
Ding does not get triggered anymore

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [tsightler/ring-mqtt#627]
I have an automation that runs when last ding changes and the ding switch is on. It worked flawessly for quite a while, triggering with almost no delay. In the last few days though it just stopped working. What can I do? Thanks

**Comment by tsightler** [comment]
There seems to be an ongoing issue with notifications right now, perhaps some changes underneath that are causing notifications to fail.  I'm seeing it on my devices as well.

Unfortunately, these problems are not in ring-mqtt, but in underlying libraries on which ring-mqtt depends, and I don't have time to dig into them at all right now, so it will have to wait, unless someone else steps up to do the work.

**Comment by tsightler** [comment]
One thing you can try is going to the control center and removing all devices (you can potentially selectively leave you phones, etc), then re-authenticating in ring-mqtt after that.  This seems to have fixed it for my devices and is the accepted workaround when push notifications stop in ring-homebridge as well.

**Comment by Stefan300381** [comment]
what do you mean by control center or rather "reauthenticate"? is this a home assistant component? if so, I'm an openHAB user.

**Comment by tsightler** [comment]
No, nothing to do with HA, it refers to the [Ring Control Center](https://support.ring.com/hc/en-us/articles/360038142272-Ring-Control-Center-Information) and then you can go to Authorized Client Devices.  Remove all devices and re-authenticate all clients, including ring-mqtt (i.e. run the tool to acquire a new token).

**Comment by tsightler** [comment]
I performed this yesterday, removed all authorized devices, and then re-authenticated, and I've not missed a notification since that time.

**Comment by Stefan300381** [comment]
Not changing anything for me, nearly no detections but several „lost subscription to ding/motion events“ messages in the log

**Comment by MaxWinterstein** [comment]
Same thing for me here, had to remove all 'Authorized Devices' - except my phone and re-authenticate via HomeAssistnt Add-On. Now it works fine.

**Comment by tsightler** [comment]
> Not changing anything for me, nearly no detections but several „lost subscription to ding/motion events“ messages in the log

Did you remove all authorized devices?  I've not seen a case where this doesn't fix the issue so far.  Even Ring has basically the same instructions when notifications stop working on their Android app.

**Comment by YOZZOPANOZZO** [comment]
I can confirm that removing every authorized device except for your phone
fixes the issue. On ha I had to reinstall the addon in order to get it to
work again, but now it works fine 👍

**Comment by tsightler** [comment]
You shouldn't have needed to re-install the addon, just remove everything and then force a re-authentication.  I didn't reinstally the addon on either of my instances, just restarted the addon and selected force reathentication option from the web ui, and re-entered credentials.

**Comment by tsightler** [comment]
Since the OP has posted that it is working for him now, and there's nothing in ring-mqtt that could address this anyway, I'm closing this for now.  If you have this issue please perform the following steps:

1.  Using either the Ring app or Ring.com dashboard, go to the Ring Control Center
2. Select "Authorized Client Devices" and remove all devices (if you know for a fact a given device is your phone, you can leave that).
3. Restart ring-mqtt and re-authenticate to Ring servers using either the addon WebUI or the ring-mqtt CLI tool.
4. Check if notifications are working again.

**Comment by Stefan300381** [comment]
just one more question if that's OK. Should the UUID in the mqtt topic change, after reauthentication?

**Comment by tsightler** [comment]
@Stefan300381 The UUID will not change as those are based on the location and device ID, which are always the same.  If you fully remove all devices and re-authenticate, and you still have issues, feel free to open a new issue and provide logs.  I'm only closing this because this specific issue here seemed to be related to re-authenticating, while your issue might be different.

**Comment by Stefan300381** [comment]
@tsightler JFYI, once again I did reset the registered ring devices, this time INCLUDING my phone. now it seems all motion and ding events are detected successfully. thanks again for your help and this great project!

**Comment by tsightler** [comment]
@Stefan300381 Thanks for reporting back.  So far removing all devices has a 100% success rate in solving the issue.  I'm not sure what triggers this problem to initially occur though, maybe one day we will figure that out.  This was the first time it's ever happened to my personal account, and it impacted both my production and development instances, so definitely Ring was pushing out some kind of changes, but a reset seems to fix whatever it is.

**Comment by Stefan300381** [comment]
@tsightler very unfortunately today I have to admit that I was wrong. Today I missed again a few motion events :-( Nothing special in the logs. I understand that currently you are not able to change the situation. Just wanted to let you know.

**Comment by 3QL** [comment]
I had the same problem last week, no detection anymore. I registered again, it worked yesterday fine until the evening, but today again no notifications. The Ring app works fine. Restarting the ring-mqtt docker has no effect, camera and shapshot works.
Now every day again register again or has ring api a problem now?

**Comment by tsightler** [comment]
Please follow https://github.com/dgreif/ring/issues/1218.  Until we are able to determine a root cause and fix this issue in ring-client-api, it won't be fixed here.
