### ISSUE TITLE
Start failure

### ISSUE THREAD

**Issue by stain3565** [tsightler/ring-mqtt#65]
I believe I have followed instructions correctly but Start produced the following log:

Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec /run.sh: Exec format error
[cmd] /run.sh exited 126
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Any ideas?
Cheers

**Comment by tsightler** [comment]
Are you sure you have installed the latest version?  The error you are reporting appears to be from an old version of the addon.
