### ISSUE TITLE
unable to start addon

### ISSUE THREAD

**Issue by doriandejong** [tsightler/ring-mqtt#659]
### Describe the Bug

Unable to start addon due to error

### Steps to Reproduce

I updated to the lastest version(4.5.1), then I wasn't able to start the addon

### Expected Behavior

The addon would start like normally like pre v4.5.1

### Log Output

```shell
Click on start butten then i get error: "Image tsightler/ring-mqtt:5.4.1 does not exist for addon_03cabcc9_ring_mqtt"
Because addon is not started logs are unavailable
```

### Config File

```shell
addon config:

mqtt_url: mqtt://auto_username:auto_password@auto_hostname
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: false
enable_panic: false
branch: addon
debug: ring-*
location_ids: []


config.yaml(lines for the addon):

camera:
  # Ring live feed
  - platform: generic
    name: Ring Livestream
    stream_source: ** reducted **
    still_image_url: ** reducted **
```

### Install Type

Hass addon

### Version

v5.4.1

### Operating System

Hass os

### Architecture

arm64

### Machine Details

rpi 3b+

**Comment by tsightler** [comment]
This is almost certainly a HAOS error as it's HAOS, and not ring-mqtt, that controls the installation of the container images.  Well, technically it is docker.  I would suggest looking at the HAOS supervisor logs.  You could potentially correct the error with docker command line, but if you are not familiar with that then easiest thing is probably just to uninstall, re-install the ring-mqtt image, or restore a backup of older ring-mqtt addon and try to upgrade again.  Make sure you are not out of space.

**Comment by doriandejong** [comment]
Thanks for the quick response, question: with reinstalling the image doe you mean the adddon in HA?

**Comment by tsightler** [comment]
Yes, addons are nothing more than a little bit of metadata wrapped around a Docker image.  If the system says the image does not exist then, for some reason, the docker pull process failed to pull down the latest image.  At least that's the most common issue.

Assuming you took a backup before upgrading (you should always take a backup before upgrading any HA component), you can easily revert to the prior addon version and try to upgrade again.  Backups are in Settings...System...Backups menu path.

However, uninstalling and re-installing shouldn't lose anything except you will have to re-authenticate and maybe any custom changes to the config, which you can just save with a copy/paste.  The code uses persistent Ids for devices so they will all still be the same.

**Comment by doriandejong** [comment]
Thank you for the help i have reverted my backup and upgraded the addon again and it works now.
