### ISSUE TITLE
Ring 2FA Docker Link Not Working

### ISSUE THREAD

**Issue by bucks7756** [tsightler/ring-mqtt#67]
Re-installing on a new pc.  When I try to use the docker link to get my token, I get the following error:

docker run -it --rm ring-mqtt/ring-mqtt node_modules/ring-client-api/ring-auth-cli.js
Unable to find image 'ring-mqtt/ring-mqtt:latest' locally
docker: Error response from daemon: pull access denied for ring-mqtt/ring-mqtt,                     repository does not exist or may require 'docker login': denied: requested acces                    s to the resource is denied.

**Comment by tsightler** [comment]
That command is if you build the docker image locally from the included Dockerfile and tag it "ring-mqtt/ring-mqtt".  If you are pulling it from my Docker Hub repo you should use the name of the repo image so:

docker run -it --rm tsightler/ring-mqtt node_modules/ring-client-api/ring-auth-cli.js

I'll update the docs to be more clear.

**Comment by bucks7756** [comment]
Thanks,When I run that, nothing happens.  Am I missing something. 

    On Monday, March 23, 2020, 08:19:14 PM EDT, tsightler <notifications@github.com> wrote:  
 
 


That command is if you build the docker image locally and call it "ring-mqtt". If you are pulling it from my Docker Hub repo you should use the name of the repo image so:

docker run -it --rm tsightler/ring-mqtt node_modules/ring-client-api/ring-auth-cli.js

**Comment by tsightler** [comment]
Sorry, the new Dockerfile uses entrypoint instead of cmd so you have to override like this:

docker run -it --rm --entrypoint node_modules/ring-client-api/ring-auth-cli.js tsightler/ring-mqtt

That should work.  I'll update the docs.

**Comment by bucks7756** [comment]
Perfect.  That worked.  Thanks!
 

    On Tuesday, March 24, 2020, 11:53:34 AM EDT, tsightler <notifications@github.com> wrote:  
 
 


Sorry, the new Dockerfile uses entrypoint instead of cmd so you have to override like this:

docker run -it --rm --entrypoint node_modules/ring-client-api/ring-auth-cli.js tsightler/ring-mqtt

That should work. I'll update the docs.

**Comment by tsightler** [comment]
Thanks for the report and for confirming the fix.  I've updated the docs with the correct command line and will close this now.
