### ISSUE TITLE
Bug: systemId is not defined while trying to generate new token

### ISSUE THREAD

**Issue by Scope666** [tsightler/ring-mqtt#671]
### Describe the Bug

systemId is not defined error

### Steps to Reproduce

Generate new token

### Expected Behavior

No error

### Log Output

```shell
root@xbmcdown:/mnt/user/appdata/ring-mqtt# docker run -it --rm --mount type=bind,source=/mnt/user/appdata/ring-mqtt,target=/data --entrypoint /app/ring-mqtt/init-ring-mqtt.js tsightler/ring-mqtt
Reading latest data from state file: /data/ring-state.json
Email: ******@gmail.com
Password: ********
Username/Password was accepted, waiting for 2FA code to be entered.
2FA Code: 567259
State file /data/ring-state.json saved with updated refresh token.
Saving state file /data/ring-state.json failed with error: 
ReferenceError: systemId is not defined
    at main (file:///app/ring-mqtt/init-ring-mqtt.js:83:47)
```

### Config File

```shell
{
    "mqtt_url": "mqtt://192.168.1.200:1883",
    "mqtt_options": "",
    "livestream_user": "",
    "livestream_pass": "",
    "disarm_code": "",
    "enable_cameras": true,
    "enable_modes": true,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring",
    "location_ids": [
        ""
    ]
}
```

### Install Type

Docker - Unraid

### Version

v5.4.0

### Operating System

Unraid

### Architecture

x86_64

### Machine Details

12th Gen Intel® Core™ i7-12700 @ 2079 MHz

**Comment by Scope666** [comment]
Restarted ring-mqtt container, despite the error message above, it does seem to be authenticated ... strange.

**Comment by tsightler** [comment]
You actually [commented last week](https://github.com/tsightler/ring-mqtt/pull/663#issuecomment-1622904563) on the PR which fixes this issue.  It was cosmetic anyway, which is why it still worked, but bug report is not required as it's already fixed in the dev branch due to that PR.  Thanks!

**Comment by Scope666** [comment]
My bad, I didn't read far enough up in that PR ... anyway, glad you already found and fixed.    :-)
