### ISSUE TITLE
Token is not valid

### ISSUE THREAD

**Issue by giorgiomanieri** [tsightler/ring-mqtt#695]
I've installed Ring addon on Home assistant core. From 2 days the addon writes this in the logs and I can't control the Ring intercom from HA:
Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens

Ring server is ok and the app works normally.

**Comment by tsightler** [comment]
Please restart the addon.  Ring had a major, global outage 2 days ago but, generally, simply restarting the addon will fix it (note that this is separate from restarting HA as restarting HA does not restart addons).

**Comment by giorgiomanieri** [comment]
Ok. Fixed it
