### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [tsightler/ring-mqtt#7]
Hello! I was just reading this project and found it really great, but I also realized you don't have any logo so I was wondering if you'd want me to design one. I would love to contribute to your project, so if you'd want that, please let me know which specific things you'd like to be visually represented in the logo :)

**Comment by tsightler** [comment]
I don't think this project really needs a logo.  This is mostly just a personal project that I decided to share because I thought others might find it useful so there's not real reason to brand it at this time.
