### ISSUE TITLE
Feature request: Add panic button 

### ISSUE THREAD

**Issue by JOHLC** [tsightler/ring-mqtt#71]
Add a way to immediately sound the alarm in the event of an emergency.

Feature is available in the app
![Screenshot_20200419-070336](https://user-images.githubusercontent.com/63735432/79686125-026ae600-820c-11ea-8991-b32fd3fe7afc.png)

**Comment by tsightler** [comment]
This has been requested before.  My big concern is false alarms.  In the app you have to select panic, then drag a slider across the screen, it's clear, deliberate steps to activate the various alarms.  There's no method to implement such protections against false alarms via MQTT so it would just be a switch and I'm afraid this makes it too easy to create a false alarm.  Effectively it's extending the alarm perimeter far beyond the Ring ecosystem and that causes me some significant concern regarding liability for false alarms.

I've thought about various ways to address this, perhaps a configurable delay that defaults to say, 10 seconds.  That way you'd have at least a few seconds to turn it off without actually triggering the alarm in the case of an accidental activation.  I've considered requiring activating two switches, one to active the panic devices and additional switches indicate the type of alarm.  This more closely mirrors the app behavior, and could still be automated, but would provide at least some protection against false alarm activation.

The code to do any of this is pretty easy, and I'm not saying I won't implement it, but it's not currently a priority as there are other pressing functional issues that need to be addressed.

**Comment by hfcheng66** [comment]
I believe Ring has default 30 seconds buffer on their side already. Once the base station is alarming you can cancel it within 30 seconds and Ring response team won't call you.

**Comment by JOHLC** [comment]
Hello!

First let me thank you for your time and effort in this, very highly appreciated. 

I can understand the concern for false alarms. 

Stay safe and again thanks for your time!

**Comment by tsightler** [comment]
I now have the plumbing needing to add a "virtual" device like this so the plan is to include this in the 4.0.0 release which I hope to have complete in the next few weeks.  I pushed the first beta to the dev branch recently, but panic support isn't there yet, but it should be pretty easy with the new setup.

**Comment by JOHLC** [comment]
Awesome news!
Thanks for everything
