### ISSUE TITLE
Integrate with Apple HomeKit through Home Assistant

### ISSUE THREAD

**Issue by Patrick1610** [tsightler/ring-mqtt#714]
Hi! I don't know if this is the right place to ask, but I am looking for some help regarding the following setup:  

I have a Ring Pro, Home Assistant and Apple Home. From Home Assistant I can expose camera's to Homekit to automatically stream doorbells on AppleTV on a Ding event. This is a standard feature of HomeKit and Home Assistant allows to expose devices to HomeKit. I have been able to add Ring-MQTT successfully to Home Assistant, and I have created the Generic Camera using the links. This works perfectly! Also, when adding the Generic Camera to HomeKit I can live-view the stream there. 

My issue is as follows: On the Ring-MQTT (ring_pro_snapshot) device, I don't get a live stream, but on the Generic Camera I do. Only, in HomeKit the Generic camera is not shown as a doorbell with the option to stream on events, while the ring_pro_snapshot device is. 

How can I combine the two correctly so that I can stream to AppleTV on a ding from my Ring device? 
I understand that this is quite a specific situation. If any more information is needed please let me know! 

With kind regards, 
Patrick

**Comment by tsightler** [comment]
I'm going to switch this to a discussion, maybe somebody in the community will have some input, however, as this project is for ring-mqtt, and your question is really about Homekit and Home Assistant, I'm not sure.

I would personally suggest using a tool like Homebridge or Scrypted for your Homekit needs vs attempting to gateway from ring-mqtt -> Home Assistant -> Homekit.
