### ISSUE TITLE
Not seeing Alarm control panel to change modes of Ring via MQTT

### ISSUE THREAD

**Issue by JamieP83** [tsightler/ring-mqtt#728]
### Describe the Bug

All works great, all devices i have are showing up (34+) however im not seeing the alarm control panel to be able to change the state of the alarm (home/away). The "alarm panel" i do have is for the panic button - but this is not the one im looking for?

### Steps to Reproduce

Setup as per instructions

### Expected Behavior

An alarm panel to be able to set the mode 

### Log Output

```shell
will post if needed?
```

### Screenshots

![image](https://github.com/tsightler/ring-mqtt/assets/48566948/ad29928e-4e98-44a9-ad46-4c2be1cf85c4)
![image](https://github.com/tsightler/ring-mqtt/assets/48566948/9273d831-8119-45e7-adc4-5746c047893f)
![image](https://github.com/tsightler/ring-mqtt/assets/48566948/a572fe9d-a2df-403b-90ea-3fd199c64bd4)

### Config File

```shell
mqtt_url: mqtt://auto_username:auto_password@auto_hostname
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: true
enable_panic: true
branch: addon
debug: ring-*
location_ids: []
```

### Install Type

HA Addon

### Version

5.6.2

### Operating System

Home Assistant 2023.9.0 - Operating System 10.5

### Architecture

rpi64

### Machine Details

rpi64

**Comment by tsightler** [comment]
hmm...this is a super strange one.  Are you sure it's not the one you are looking for and just misnamed?  I'm thinking maybe an unexpected side effect from the stupid name updates I had to do in v5.6.0 and later due to changes in entity naming in HA.  I mean, you can always just rename the device/entity in HA.  Full logs would certainly help.

**Comment by JamieP83** [comment]
Hey
Maybe! I do also have a panic button and I don’t see that?
How do I grab full logs sorry? The link shown when raising the issue didn’t work


Thanks,
Jamie

Sent from my iPhone

On 9 Sep 2023, at 3:21 am, tsightler ***@***.***> wrote:

﻿

hmm...this is a super strange one. Are you sure it's not the one you are looking for and just misnamed? I'm thinking maybe an unexpected side effect from the stupid name updates I had to do in v5.6.0 and later due to changes in entity naming in HA. I mean, you can always just rename the device/entity in HA. Full logs would certainly help.

**Comment by tsightler** [comment]
I have no idea how panic switches are presented in the Ring API, the code has no explicit support for them so I don't fully understand how they could be presented in the UI.  Logs can be gathered here:

https://github.com/tsightler/ring-mqtt-ha-addon/blob/main/GET-LOGS.md

Alternatively, we could maybe start with just a data discovery.  For that you can install node on any system and run:

`npx -p ring-client-api ring-device-data-cli`

Then send the output.

**Comment by JamieP83** [comment]
Thanks for the quick replies
Will do tomorrow and share


Thanks,
Jamie

Sent from my iPhone

On 9 Sep 2023, at 3:14 pm, tsightler ***@***.***> wrote:

﻿

I have no idea how panic switches are presented in the Ring API, the code has no explicit support for them so I don't fully understand how they could be presented in the UI. Logs can be gathered here:

https://github.com/tsightler/ring-mqtt-ha-addon/blob/main/GET-LOGS.md

Alternatively, we could maybe start with just a data discovery. For that you can install node on any system and run:

npx -p ring-client-api ring-device-data-cli

Then send the output.

**Comment by JamieP83** [comment]
Hey
PFA the logs
[ring-mqtt.log.gz](https://github.com/tsightler/ring-mqtt/files/12570521/ring-mqtt.log.gz)

**Comment by JamieP83** [comment]
ah! when opening, thjat didnt work for some reason

also, when you mention about running "node" - is that something via nodeRed sorry? or something else?
appologies

**Comment by tsightler** [comment]
Node = [NodeJS](https://nodejs.org/), a Javascript runtime engine for building server side applications.  Node-Red is an application built on NodeJS, as is ring-mqtt.

**Comment by JamieP83** [comment]
Thanks
I have node red
How do I run that from within? What’s the object to use,


Thanks,
Jamie

Sent from my iPhone

On 10 Sep 2023, at 9:59 pm, tsightler ***@***.***> wrote:

﻿

Node = NodeJS<https://nodejs.org/>, a Javascript runtime engine for building server side applications. Node-Red is an application built on NodeJS, as is ring-mqtt.

**Comment by tsightler** [comment]
You just install NodeJS (I provided a link) on any system and run the command, that is all, there is not that much to it.  It doesn't have anything to do with Node-Red.  It sounds like you don't have much skill with the CLI, but that may mean that I am unable to help you as this project assumes a moderate understanding of system basics.

**Comment by tsightler** [comment]
I took a quick look at the file you did upload.  It only contains a single line "docker: command not found", which means you have not followed the instructions in the GET-LOGS.md file correctly.  You must follow the steps to gain access to the docker commands on Home Assistant OS, only then can you run the command to acquire logs.  Unfortunately, without these logs I will be unable to help further.

**Comment by tsightler** [comment]
Closing due to no response.
