### ISSUE TITLE
Issues running Ring-mqtt and another mqtt docker

### ISSUE THREAD

**Issue by Teryeahh** [tsightler/ring-mqtt#747]
I have been using the HA addon for a while, have been working all the time.
So this isnt exactly a direct issue with the addon. But the combination of the addon and homely-mqtt docker.

Some days ago I installed this docker on my unraid server: [https://github.com/yusijs/homely-mqtt]([https://github.com/yusijs/homely-mqtt)] to get info from my alarm system into Home Assistant.

First I only got 4 of the sensors in Home Assistant with mqtt. Tried reinstallation, restarts and so on.
Since I didn't find any obvious issues I started to try different things. I then uninstalled the Ring-mqtt addon. And all the devices from homely-mqtt popped into Home Assistant.

I then the next day tried to reinstall the Ring-mqtt addon.
All the entities from the homely-mqtt was still there. but the sensors did become unavailable now and then and didnt report changes.

Do you have any idea what I can do to make this work?

**Comment by tsightler** [comment]
As this is not an issue with this project I'm not sure how to help you.  It's just two projects that both happen to use MQTT, homely-mqtt uses different topic prefixes vs ring-mqtt so there should be no conflicts, just make sure they both use the same MQTT broker.  You can monitor the messages with any MQTT client (maybe something like MQTT explorer).  Good luck!
