### ISSUE TITLE
Error Configuration file could not be read.

### ISSUE THREAD

**Issue by d3m0n2000** [tsightler/ring-mqtt#757]
Hi all. 
I'm beginner and i try to install the docker.
if i use the command

docker run --rm --mount type=bind,source=/etc/ring-mqtt,target=/data,target=/data tsightler/ring-mqtt

i get the error:

2023-11-14T10:29:40.496Z ring-mqtt Detected runmode: docker
2023-11-14T10:29:40.500Z ring-mqtt Configuration file: /data/config.json
2023-11-14T10:29:45.328Z ring-mqtt Reading latest data from state file: /data/ring-state.json
2023-11-14T10:29:45.354Z ring-mqtt Unexpected token h in JSON at position 327
2023-11-14T10:29:45.357Z ring-mqtt Configuration file could not be read, check that it exist and is valid.
[10:29:45] WARNING: A critical error was detected, shutting down container...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

can someone help me?
what i did wrong?

config.json
{
    "mqtt_url": "mqtt://192.168.178.160:1883",
    "mqtt_options": "",
    "livestream_user": "",
    "livestream_pass": "",
    "disarm_code": "",
    "enable_cameras": true,
    "enable_modes": false,
    "enable_panic": false,
    "hass_topic": "homeassistant/status",
    "ring_topic": "ring_topic",
    "location_ids": [https://account.ring.com/account/dashboard?l=xxxxxxxx-xxxx-xxxx-b43d-910b4706137d]
}

**Comment by tsightler** [comment]
Well, location_ids should just be the id, not the full URL, so that's the most likely issue, but you also have a non-default ring_topic, although it should technically be fine.  In general, if you are a beginner, best thing to do is start with as close to defaults as possible, and then work your way through.

This would have been better asked in discussions Q&A vs opening a support issue so I'm going to transfer it there.
