### ISSUE TITLE
MyQ Garage door not status not showing in HA via this addin

### ISSUE THREAD

**Issue by iptvcld** [tsightler/ring-mqtt#765]
### Describe the Issue

MyQ Garage door not status not showing in HA via this addin

### Steps take so far

removed addin from HA and readded, all my other sensors comes in ok via HA but not the garage

### Log Output

```shell
NA
```

### Config File

```shell
NA
```

### Install Type

Home assisstant

### Version

latest

### Operating System

HA OS

**Comment by tsightler** [comment]
MyQ devices are not supported by this project as they are not available via the Ring API.
