### ISSUE TITLE
ESP8266 contact sensor

### ISSUE THREAD

**Issue by vazquezjm** [tsightler/ring-mqtt#77]
Would it possible to trigger Ring alarm using an esp8266 device with a contact switch, through either HA integration or mqtt?

**Comment by tsightler** [comment]
Not that I know of currently, the code base currently has no method to actually trigger alarms.  There is open feature request https://github.com/tsightler/ring-mqtt/issues/71 to implement support for the panic button feature in ring-mqtt that would allow alarms to be triggered via MQTT, but I haven't had time to implement that feature, although I think it's getting closer.
