### ISSUE TITLE
Choppy audio in Homekit

### ISSUE THREAD

**Issue by miwagner1** [tsightler/ring-mqtt#795]
### Describe the Bug

Choppy audio in Homekit

### Steps to Reproduce

ring-mqtt > go2rtc > Home Assistant > homekit

### Expected Behavior

audio to not be choppy

### Log Output

```shell
Go2rtc v1.8.5 - 2024-01-01 Fixes the issue

Add support Rockchip hardware transcoding #768 by @MarcA711
Add support OPUS codec for MPEG-TS source #788
Add log viewer to WebUI #780 by @skrashevich
Add support subtype for Tapo source #792
Add error for wrong HomeKit source #805
Add support H265 to FLV source #822
Ensure exit code is within valid range #785 by @skrashevich
Fix buggy SDP from D-Link cameras #771
Fix support FFmpeg device on Windows #794
Fix CORS support in WHEP/WHIP API #798 by @MPTres
Fix H265 support from OpenIPC project
Fix exec source leaves zombie processes after fail #814
Fix hardware profiles for H265 templates #809 by @MPTres
Fix OPUS choppy audio for HomeKit server #667 #843 by @civita
Fix mdns log message #843 by @civita
Fix support Aqara G2H #793 by @duncanleo
Fix panic on reconnect #828
```

### Config File

```shell
Go2rtc v1.8.5 - 2024-01-01 Fixes the issue

Add support Rockchip hardware transcoding #768 by @MarcA711
Add support OPUS codec for MPEG-TS source #788
Add log viewer to WebUI #780 by @skrashevich
Add support subtype for Tapo source #792
Add error for wrong HomeKit source #805
Add support H265 to FLV source #822
Ensure exit code is within valid range #785 by @skrashevich
Fix buggy SDP from D-Link cameras #771
Fix support FFmpeg device on Windows #794
Fix CORS support in WHEP/WHIP API #798 by @MPTres
Fix H265 support from OpenIPC project
Fix exec source leaves zombie processes after fail #814
Fix hardware profiles for H265 templates #809 by @MPTres
Fix OPUS choppy audio for HomeKit server #667 #843 by @civita
Fix mdns log message #843 by @civita
Fix support Aqara G2H #793 by @duncanleo
Fix panic on reconnect #828
```

### Install Type

docker

### Version

5.6.3

### Operating System

Fedora IoT

### Architecture

x86_64

### Machine Details

n100

**Comment by tsightler** [comment]
I don't really understand what you are posting.  You posted about go2rtc versions, but you can use whatever version of go2rtc you like, including the latest version, although I think that fix is only for the case where HomeKit is served directly from go2rtc, while you are using Home Assistant to expose the device to HomeKit.

Regardless, none of this has anything to do with ring-mqtt itself, it simply passes through the RTP packets containing Opus audio from the Ring cameras directly, without any manipulation at all.  Homekit has very specific requirements for Opus audio to work correctly without being choppy, so it's up to whatever is provides the bridge to Homekit to deal with that.
