### ISSUE TITLE
Support: keeps rebooting

### ISSUE THREAD

**Issue by aelsharawi** [tsightler/ring-mqtt#798]
### Describe the Issue

keeps on rebooting the plugin, 

### Steps take so far

disabled the camera solved the reboot (maybe the xaoim vacuum card have something to do as it ports the xaomia camera?)

### Log Output

```shell
2024-03-14T21:57:14.634Z ring-rtsp [go2rtc] ERR [rtsp] listen error="listen tcp :8554: bind: address already in use"
```

### Config File

```shell
mqtt_url: mqtt:/-----
mqtt_options: ""
livestream_user: ""
livestream_pass: ""
disarm_code: ""
enable_cameras: true
enable_modes: true
enable_panic: true
branch: addon
debug: ring-*
location_ids: []
```

### Install Type

Home assistant

### Version

5.6.3 

### Operating System

Home assistant OS

**Comment by tsightler** [comment]
Unless you have explicitly configured the power to be exposed in the network settings, it should not matter what other ports are used on the host as the go2rtc daemon only binds to the in-host docker network IP.  If you have exposed the port via network settings, then you'll have to make sure to use a port that does not conflict with anything else on the host.

**Comment by aelsharawi** [comment]
Im not an expert ..please explain how to start the troubleshooting? a code in ssh to expose the ports and apps that are using it?

**Comment by tsightler** [comment]
I'm afraid I don't really know how to help you, if you don't have basic knowledge of HA and how addons work with Docker based networking there's little chance of success and I just don't have time to walk people through the basic items like this that are technically outside of the scope of the addon itself.  I'm sorry.
