### ISSUE TITLE
Add keypad battery level

### ISSUE THREAD

**Issue by toscano** [tsightler/ring-mqtt#8]
First, let me say NICE JOB 👍! I was wondering if it were possible to add the keypad component, if only to monitor the battery level. Thanks.

**Comment by tsightler** [comment]
If you look at the readme this is already on the "possible future features" list.  Right now the biggest problem is determining how to surface the data.  I have to work within the platforms supported by the MQTT component, and the only one that makes any sense is probably the generic "Sensor" component, but it just seems weird to have a device that is nothing but a battery sensor.

What I was thinking is that maybe I could have a sensor device with just "OK" status and then perhaps "Tamper" and "On Battery" status, and then continue to report battery level as a JSON attribute. 
 Unfortunately, it will probably be several months before I have any available time to work on this capability and really think through it.

**Comment by tsightler** [comment]
Keypad battery level as well as more details such as the status of ac power, charging, chrips, power save setting, have been added to the 4.0.0-beta2 release available in the dev branch.  Hope to finish the work to release 4.0.0 final within the next 2 weeks, maybe sooner.
