### ISSUE TITLE
Error when camera set to true

### ISSUE THREAD

**Issue by cdiazfer** [tsightler/ring-mqtt#81]
Hi! First of all, thanks a lot for your amazing work! I just trying to configure ring mqtt but I have this error trying to start it:

(node:17007) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'publish' of undefined
    at Camera.publishCapability (/data/ring/ring-mqtt/devices/camera.js:164:25)
    at Camera.init (/data/ring/ring-mqtt/devices/camera.js:60:14)
    at cameras.forEach.camera (/data/ring/ring-mqtt/ring-mqtt.js:203:23)
    at Array.forEach (<anonymous>)
    at publishCameras (/data/ring/ring-mqtt/ring-mqtt.js:195:13)
    at publishLocation (/data/ring/ring-mqtt/ring-mqtt.js:123:17)
    at locations.forEach (/data/ring/ring-mqtt/ring-mqtt.js:82:17)
(node:17007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

I follow all your steps but I can´t catch the problem. I installed a few hours ago, so I have the last version.

Could you please assist?

Regards!

**Comment by tsightler** [comment]
Hi, does it work if you disable camera support?  Or do you only have cameras?

**Comment by cdiazfer** [comment]
Thanks for the quick reply!!!

i only have ring doorbell.  It seems that start registering motion sensor but the next step crash with the trace I sent before...

ring-mqtt    'ring/xxxxxxxxxxxxxxxx/camera/binary_sensor/xxxxxx/motion_state',
  ring-mqtt   device_class: 'motion' } +1ms

This came just before crashing.

Regards!

**Comment by tsightler** [comment]
It could be a bug with camera only setups, that's definitely not a common use case for the script at this time, although it should work.  The command line that is failing is the attempt to push to MQTT.  At the top of the logs do you see a connection to MQTT being established?

**Comment by cdiazfer** [comment]
Yes, it is connecting without problems. But the problem comes when try to publish.

Regards!

**Comment by tsightler** [comment]
I'm pretty sure I found the issue, there was a missing parameter in the publishLocations call when used with camera only setups that would cause exactly the behavior you are seeing.  I've pushed an update that should fix it if you could please redeploy and test.  Sorry about that.

**Comment by cdiazfer** [comment]
Wow! No matter! You don't have to worry about it! I only have to thanks you a lot for your uninterested help!!!

I will try and I give you feedback.

Regards!

**Comment by cdiazfer** [comment]
It's works! Now I see the log without problems and I see the sensors in home assistant.

Again, thanks a lot!

**Comment by tsightler** [comment]
Excellent, thanks for the report and sorry again for the bug, it slipped in with the update I pushed out just yesterday.

Just to make sure you are aware, since you are using Home Assistant, this addon isn't required for Ring cameras/doorbells on that platform as Home Assistant has a native support for Ring component that has more capabilities than this addon can provide.

**Comment by cdiazfer** [comment]
Thanks to you sir!!!

I know about this integration, but the ding binary sensor is not working so I take a chance with your fantastic work! I have the last version of home assistant, without hassio, and home assistant is not updating neither the ding nor the motion binary sensor.

Regards.

**Comment by cdiazfer** [comment]
Unfortunately, I have the same issue. The ding or motion sensor is not updating, I suppose it could be a ring API problem.

Thanks anyway!

**Comment by tsightler** [comment]
If you're having it with both setups that's certainly very odd.  Do you get notifications on your phone?  I use this integration heavily with my doorbell and mulitple Ring cameras and it's very reliable with motion reporting.

I'm going to close this case for now since the issue reported is resolved.

**Comment by cdiazfer** [comment]
Yes, I have phone notification without problems, but I don't know why but with integration API seems it's having problems. But anyway, the issue is resolved as you said.

Thanks a lot for your amazing quick response!
