### ISSUE TITLE
***IMPORTANT*** Do not upgrade the Home Assistant go2rtc addon to v1.9.0!!!

### ISSUE THREAD

**Issue by tsightler** [tsightler/ring-mqtt#828]
### Discussed in https://github.com/tsightler/ring-mqtt/discussions/827

<div type='discussions-op-text'>

<sup>Originally posted by **tsightler** April 30, 2024</sup>
I don't really know where to put this, but it's important that users not upgrade their go2rtc addon to v1.9.0 in Home Assistant.  If you do so, and then view a video, the session will never end and the stream will stay active continuously.  The only fix I've found so far is to downgrade the go2rtc addon back to v1.8.5. </div>

**Comment by DabblerIOT** [comment]
thank you

**Comment by alexreddy78** [comment]
> ### Discussed in #827
> Originally posted by **tsightler** April 30, 2024 I don't really know where to put this, but it's important that users not upgrade their go2rtc addon to v1.9.0 in Home Assistant. If you do so, and then view a video, the session will never end and the stream will stay active continuously. The only fix I've found so far is to downgrade the go2rtc addon back to v1.8.5.

Hi Tom, it’s fixed in 1.9.1. Webrtc session back to normal. I have no issue with above mentioned.
Regards

**Comment by tsightler** [comment]
Yes, seems to be fixed with 1.9.1 so closing this.
