### ISSUE TITLE
REPOSITORY LINK NOT WORKING

### ISSUE THREAD

**Issue by NefariusDeus** [tsightler/ring-mqtt#835]
### Describe the Bug

Hi, thanks for the work btw. The link for the repository addon isnt working. When i try to implement it it says: https://github.com/tsightler/ring-mqtt is not a valid add-on repository

### Steps to Reproduce

Trying to implement the addon repository 

### Expected Behavior

https://github.com/tsightler/ring-mqtt is not a valid add-on repository

### Log Output

```shell
https://github.com/tsightler/ring-mqtt is not a valid add-on repository
```

### Config File

```shell
No
```

### Install Type

Home assistant

### Version

12.3

### Operating System

Home assistant os

### Architecture

X86

### Machine Details

Raspberry Pi 4b

**Comment by tsightler** [comment]
The addon is not in the main repo, but in an addon specific repo:

https://github.com/tsightler/ring-mqtt-ha-addon

I'm confident the wiki documentation points to the correct repo for the addon.

**Comment by NefariusDeus** [comment]
Thank you!!! Am 14.05.2024 um 18:47 schrieb tsightler ***@***.***>:﻿
The addon is not in the main repo, but in a secondary repo:
https://github.com/tsightler/ring-mqtt-ha-addon
I'm confident the wiki documentation points to the correct repo for the addon.
