### ISSUE TITLE
Disarming not working when requested by a scene

### ISSUE THREAD

**Issue by KC-inDomus** [tsightler/ring-mqtt#935]
### Is there an existing issue for this?

- [X] I have searched all existing open/closed issues

### Is this really a bug or just a usage/support question?

- [X] I'm confident this is a bug.

### Have you read and followed any recommendations in the Support and Troubleshooting section of the wiki?

- [X] I have read the support wiki and followed any applicable steps.

### Did this issue start after an upgrade?

- [X] This not an upgrade issue or I have read the release notes and performed any applicable steps that match my issue.

### Are you prepared to respond and provide all relevant information (logs, screenshots, etc)

- [X] I am prepared to provide logs, answer questions, and respond in a reasonable timeframe.

### Describe the Bug

Disarming not working when requested by a scene

### Steps to Reproduce

Call disarm from Scene

### Expected Behavior

Should disable

### Log Output

```shell
WARNING (MainThread) [homeassistant.components.mqtt.alarm_control_panel] Wrong code entered for disarming
```

### Config File

```shell
scene:
- name: test
  entities:
    alarm_control_panel.alarm_name:
      state: disarmed
      code: 0123

Calling scene.turn_on for scene.test entity gives "wrong code".
Calling alarm_control_panel.alarm_disarm from action panel on webgui, this works:

action: alarm_control_panel.alarm_disarm
data:
  entity_id: alarm_control_panel.alarm_name
  code: 0123
```

### Install Type

Home Assistant Core@Docker

### Version

2024.11.2

### Operating System

Linux Debian

### Architecture

x86_64

### Machine Details

Mini PC

**Comment by tsightler** [comment]
Closing this as I don't see any way possible this is an addon bug.  Feels like it has to be a HA bug and I saw that you already opened an issue there.  If, for some reason, you have some proof that this is caused by the addon and not HA, feel free to reopen.

**Comment by tsightler** [comment]
Actually, I'm going to reopen and ask a few questions.  Do you have a code set in the ring-mqtt configuration?

**Comment by KC-inDomus** [comment]
> Actually, I'm going to reopen and ask a few questions. Do you have a code set in the ring-mqtt configuration?

the only code I had set is ring-app side.

**Comment by tsightler** [comment]
Then why are you including a code in the automation?  If you have no code configured in ring-mqtt then you don't need a code for the automations at all.  What happens if you just remove the code from the scene automation?

**Comment by KC-inDomus** [comment]
> Then why are you including a code in the automation? If you have no code configured in ring-mqtt then you don't need a code for the automations at all. What happens if you just remove the code from the scene automation?

just made a try. code is needed to arm and disarm, using action panel.
for example this don't work:

```
action: alarm_control_panel.alarm_disarm
data:
  entity_id: alarm_control_panel.alarm_name
```

instead, this work:

```
action: alarm_control_panel.alarm_disarm
data:
  entity_id: alarm_control_panel.alarm_name
  code: 0123
```

so, code seems to be needed.

**Comment by tsightler** [comment]
I don't know why it would be required in any case, all current versions of ring-mqtt set `code_disarm_required: false` if no code is set in the addon configuration.  This feels like yet another HA bug in how they handle codes.

**Comment by KC-inDomus** [comment]
> I don't know why it would be required in any case, all current versions of ring-mqtt set `code_disarm_required: false` if no code is set in the addon configuration. This feels like yet another HA bug in how they handle codes.

code_disarm_required: false ins't a bit insicure, above all?

**Comment by tsightler** [comment]
> code_disarm_required: false ins't a bit insicure, above all?

You said you didn't set a code in the addon config, so there is no code required for disarming, thus `code_disarm_required: false` is the only valid and correct setting.  The Ring app also doesn't require a code to disarm, is it insecure?  It assumes you are protected by your device authentication.  By default, the addon assumes you HA is secured from non-authenticated access as well, so no different.

If you want to use a code with ring-mqtt, you must set a code in the addon config and then it will set `code_disarm_required: true` which enforces use of a code in HA.

**Comment by KC-inDomus** [comment]
I apologise. was sure hadn't a code in my ring-mqtt config, but I had (btw, the code was right). Now I removed that entry, and now it's working fine both on action calling and scene calling.
the entire round is not clear to me btw, I'll go more in detail.

**Comment by tsightler** [comment]
OK, well, that re-enforces that this problem is 100% in HA, so I'm going to revert this back to closed.  Thanks for your quick responses, hopefully the HA team can address the issue.

**Comment by tsightler** [comment]
Took a quick look at the scene code in HA and I don't believe that it supports code option as it appears to be only a very basic proxy for state and there's no device/entity specific logic that I could see, so I believe it is just ignoring the code completely, thus why the service returns the error.  I think this boils down to a feature requests for HA if anything at all.

However, as an alternative, you can fairly easily link an automation to a scene change.  It's not possible to directly trigger an automation from a scene, however, any time an scene is activated it creates an event, and you can trigger on an event, so, based on your scene example above you can create an automation like this:

```
- alias: 'On test Activated'
  trigger:
    platform: event
    event_type: 'call_service'
    event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.test
  action:
actions:
  - action: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm_name
      code: 0123
```
