### ISSUE TITLE
Bug: No longer senses motion for Ring Doorbell v2

### ISSUE THREAD

**Issue by KruseLuds** [tsightler/ring-mqtt#949]
### Is there an existing issue for this?

- [X] I have searched all existing open/closed issues

### Is this really a bug or just a usage/support question?

- [X] I'm confident this is a bug.

### Have you read and followed any recommendations in the Support and Troubleshooting section of the wiki?

- [X] I have read the support wiki and followed any applicable steps.

### Did this issue start after an upgrade?

- [X] This not an upgrade issue or I have read the release notes and performed any applicable steps that match my issue.

### Are you prepared to respond and provide all relevant information (logs, screenshots, etc)

- [X] I am prepared to provide logs, answer questions, and respond in a reasonable timeframe.

### Describe the Bug

I use Ring-MQTT only to trigger automations based upon motion for a Ring Doorbell v2. It has stopped sending motion several weeks ago and I don't know why.

### Steps to Reproduce

Move in front of doorbell

### Expected Behavior

Motion should be detected

### Log Output

```shell
How do I get these?
```

### Config File

```shell
What config file for this? I have no settings for Ring-MQTT in my configuration.yaml file (that I know of)?
```

### Install Type

HAIS

### Version

Latest

### Operating System

HAOS

### Architecture

rPi5

### Machine Details

rPi5 8gig ram, running off an ssd.

**Comment by tsightler** [comment]
Sorry, but this isn't a useful bug report and I'm going to have close it.  Please make sure you have followed all of the steps in the [notification troubleshooting](https://github.com/tsightler/ring-mqtt/wiki/Support-&-Troubleshooting#no-motionding-state-updates-for-cameras-doorbells-and-intercoms) section from the wiki, but, to be very frank, if you don't even know how to find and copy logs of configs, then there's zero chance we can get to the technical level required to troubleshoot beyond what is in the wiki.
